export function shuffle<T>(values:T[],random=Math.random):T[]{const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function neighbors(index:number,width:number,height:number,diagonal=true){const out:number[]=[];const x=index%width,y=Math.floor(index/width);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if((!dx&&!dy)||(!diagonal&&Math.abs(dx)+Math.abs(dy)!==1))continue;const nx=x+dx,ny=y+dy;if(nx>=0&&nx<width&&ny>=0&&ny<height)out.push(ny*width+nx);}return out;}
export function createMines(width:number,height:number,count:number,first:number,random=Math.random){const safe=new Set([first,...neighbors(first,width,height)]);const positions=shuffle(Array.from({length:width*height},(_,i)=>i).filter(i=>!safe.has(i)),random).slice(0,count);const mines=new Set(positions);return Array.from({length:width*height},(_,i)=>mines.has(i)?-1:neighbors(i,width,height).filter(n=>mines.has(n)).length);}
export function revealMines(board:number[],revealed:boolean[],flags:boolean[],index:number,width:number,height:number){const next=[...revealed];const queue=[index];while(queue.length){const i=queue.pop()!;if(next[i]||flags[i])continue;next[i]=true;if(board[i]===0)queue.push(...neighbors(i,width,height).filter(n=>!next[n]&&!flags[n]));}return next;}
export function slidePuzzle(board:number[],index:number,size:number){const zero=board.indexOf(0);if(!neighbors(zero,size,size,false).includes(index))return board;const next=[...board];[next[index],next[zero]]=[next[zero],next[index]];return next;}
export function solvedPuzzle(board:number[]){return board.every((v,i)=>v===(i+1)%board.length);}
export function newPuzzle(size:number,random=Math.random){let board=Array.from({length:size*size},(_,i)=>(i+1)%(size*size));let previous=-1;for(let i=0;i<size*size*30;i++){const zero=board.indexOf(0),options=neighbors(zero,size,size,false).filter(n=>n!==previous);const index=options[Math.floor(random()*options.length)];board=slidePuzzle(board,index,size);previous=zero;}if(solvedPuzzle(board))board=slidePuzzle(board,board.length-2,size);return board;}
export function stepLife(board:number[],width:number,height:number,wrap:boolean){return board.map((cell,index)=>{let n=0;const x=index%width,y=Math.floor(index/width);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;let nx=x+dx,ny=y+dy;if(wrap){nx=(nx+width)%width;ny=(ny+height)%height;}if(nx>=0&&nx<width&&ny>=0&&ny<height)n+=board[ny*width+nx];}return n===3||(cell===1&&n===2)?1:0;});}
export const tetrominoes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]]];
export function rotatePiece(piece:number[][]){return piece[0].map((_,x)=>piece.map(row=>row[x]).reverse());}
export function pieceFits(board:number[],piece:number[][],x:number,y:number,width=10,height=20){return piece.every((row,dy)=>row.every((v,dx)=>!v||(x+dx>=0&&x+dx<width&&y+dy<height&&(y+dy<0||board[(y+dy)*width+x+dx]===0))));}
export function lockPiece(board:number[],piece:number[][],x:number,y:number,color:number,width=10){const next=[...board];piece.forEach((row,dy)=>row.forEach((v,dx)=>{if(v&&y+dy>=0)next[(y+dy)*width+x+dx]=color;}));return next;}
export function clearLines(board:number[],width=10){const rows=[];let lines=0;for(let y=0;y<board.length/width;y++){const row=board.slice(y*width,(y+1)*width);if(row.every(Boolean))lines++;else rows.push(...row);}return {board:[...Array(lines*width).fill(0),...rows],lines};}
export interface SnakeV2{body:number[];direction:number;food:number;over:boolean;score:number}
export const snakeObstacles=[126,127,128,129,130,269,270,271,272,273];
export function snakeStep(s:SnakeV2,requested:number,mode:number,size=20,random=Math.random):SnakeV2{if(s.over)return s;const direction=(requested+2)%4===s.direction?s.direction:requested;const vectors=[[0,-1],[1,0],[0,1],[-1,0]];let x=s.body[0]%size+vectors[direction][0],y=Math.floor(s.body[0]/size)+vectors[direction][1];if(mode===1){x=(x+size)%size;y=(y+size)%size;}const head=y*size+x,eating=head===s.food,occupied=eating?s.body:s.body.slice(0,-1);if(x<0||y<0||x>=size||y>=size||occupied.includes(head)||(mode===2&&snakeObstacles.includes(head)))return {...s,direction,over:true};const body=[head,...s.body];if(!eating)body.pop();const free=Array.from({length:size*size},(_,i)=>i).filter(i=>!body.includes(i)&&!(mode===2&&snakeObstacles.includes(i)));const food=eating?(free[Math.floor(random()*free.length)]??-1):s.food;return {body,direction,food,score:s.score+(eating?10:0),over:food===-1};}
export function circleRect(x:number,y:number,r:number,rx:number,ry:number,rw:number,rh:number){const nx=Math.max(rx,Math.min(x,rx+rw)),ny=Math.max(ry,Math.min(y,ry+rh));return (x-nx)**2+(y-ny)**2<=r*r;}
