export function encodeBase64(text:string){const bytes=new TextEncoder().encode(text);let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(raw);}
export function decodeBase64(text:string){const clean=text.replace(/\s/g,'');if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(clean))throw Error('Enter valid padded Base64.');return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(clean),c=>c.charCodeAt(0)));}
export function randomInt(max:number,fill=(a:Uint32Array)=>crypto.getRandomValues(a)){if(!Number.isSafeInteger(max)||max<1||max>0x100000000)throw Error('Invalid random range.');const limit=Math.floor(0x100000000/max)*max,a=new Uint32Array(1);do{fill(a);}while(a[0]>=limit);return a[0]%max;}
export const passwordSets={upper:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',lower:'abcdefghijklmnopqrstuvwxyz',digits:'0123456789',symbols:'!@#$%^&*()-_=+[]{};:,.?'};
export function makePassword(length:number,groups:string[],random=randomInt){if(!Number.isInteger(length)||length<4||length>128)throw Error('Choose a length from 4 to 128.');if(!groups.length)throw Error('Choose at least one character set.');const pool=groups.join(''),chars=groups.map(g=>g[random(g.length)]);while(chars.length<length)chars.push(pool[random(pool.length)]);for(let i=chars.length-1;i>0;i--){const j=random(i+1);[chars[i],chars[j]]=[chars[j],chars[i]];}return chars.join('');}
export function drawItems(items:string[],count:number,unique:boolean,random=randomInt){const pool=unique?[...new Set(items.map(s=>s.trim()).filter(Boolean))]:items.map(s=>s.trim()).filter(Boolean);if(!pool.length)throw Error('Add at least one candidate.');if(!Number.isInteger(count)||count<1||count>1000)throw Error('Draw between 1 and 1,000 items.');if(unique&&count>pool.length)throw Error('There are fewer unique candidates than requested results.');const out:string[]=[];for(let i=0;i<count;i++){const index=random(pool.length);out.push(pool[index]);if(unique)pool.splice(index,1);}return out;}
export const units:Record<string,Record<string,number>>={Length:{m:1,km:1000,cm:.01,mm:.001,in:.0254,ft:.3048,yd:.9144,mi:1609.344},Mass:{kg:1,g:.001,mg:.000001,lb:.45359237,oz:.028349523125},Temperature:{'°C':1,'°F':1,K:1},Area:{'m²':1,'km²':1e6,'cm²':.0001,'ft²':.09290304,acre:4046.8564224,hectare:10000},Volume:{L:1,mL:.001,'m³':1000,'US gal':3.785411784,'US cup':.2365882365}};
export function convertUnit(value:number,category:string,from:string,to:string){if(!Number.isFinite(value))throw Error('Enter a finite number.');if(!units[category]||!(from in units[category])||!(to in units[category]))throw Error('Choose valid units.');if(category==='Temperature'){const c=from==='°C'?value:from==='°F'?(value-32)*5/9:value-273.15;if(c< -273.15-1e-8)throw Error('Temperature is below absolute zero.');return to==='°C'?c:to==='°F'?c*9/5+32:c+273.15;}return value*units[category][from]/units[category][to];}
export function parseTimestamp(value:string,unit:'seconds'|'milliseconds'){if(!value.trim()||!Number.isFinite(Number(value)))throw Error('Enter a numeric timestamp.');const d=new Date(Number(value)*(unit==='seconds'?1000:1));if(!Number.isFinite(d.getTime()))throw Error('Timestamp is outside the supported date range.');return d;}
export function parseColor(value:string):[number,number,number]{const s=value.trim();if(/^#[\da-f]{3}$/i.test(s))return s.slice(1).split('').map(c=>parseInt(c+c,16)) as [number,number,number];if(/^#[\da-f]{6}$/i.test(s))return [1,3,5].map(i=>parseInt(s.slice(i,i+2),16)) as [number,number,number];const rgb=s.match(/^rgb\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*\)$/i);if(rgb){const values=rgb.slice(1).map(Number);if(values.every(v=>Number.isFinite(v)&&v>=0&&v<=255))return values.map(Math.round) as [number,number,number];}const hsl=s.match(/^hsl\(\s*(-?[\d.]+)\s*,\s*([\d.]+)%\s*,\s*([\d.]+)%\s*\)$/i);if(hsl){const [h,s,l]=hsl.slice(1).map(Number);if(![h,s,l].every(Number.isFinite)||s>100||l>100)throw Error('HSL saturation and lightness must be 0–100%.');const hue=((h%360)+360)%360/360,sat=s/100,light=l/100;const a=sat*Math.min(light,1-light);const channel=(n:number)=>{const k=(n+hue*12)%12;return Math.round((light-a*Math.max(-1,Math.min(k-3,9-k,1)))*255);};return [channel(0),channel(8),channel(4)];}throw Error('Use #aabbcc, rgb(170, 187, 204), or hsl(210, 25%, 73%).');}
export function colorFormats(rgb:[number,number,number]){const [r,g,b]=rgb.map(v=>v/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0;if(d)h=max===r?((g-b)/d)%6:max===g?(b-r)/d+2:(r-g)/d+4;h=(h*60+360)%360;const s=d===0?0:d/(1-Math.abs(2*l-1));return {hex:'#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join(''),rgb:`rgb(${rgb.join(', ')})`,hsl:`hsl(${Math.round(h)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`};}
