import { parseColor,colorFormats } from '../lib/utilities.ts';
import { paletteDocument,decodePalette,paletteCSS,contrast,hex,type PaletteDocument } from '../lib/image/palette.ts';
const root=document.getElementById('color-workshop');if(root)setup(root);
function setup(root:HTMLElement){
  const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(`color-${id}`) as T,field=(id:string)=>el<HTMLInputElement>(id);
  let palette=paletteDocument(['#ad99e5','#c6eaa5'],'First palette'),dirty=false,formats:Record<string,string>={};
  const status=(message:string,error=false)=>{el('status').textContent=message;el('status').dataset.error=String(error);};
  const act=(action:()=>void|Promise<void>)=>{try{Promise.resolve(action()).catch(error=>status(String(error),true));}catch(error){status(error instanceof Error?error.message:String(error),true);}};
  async function copy(text:string){try{await navigator.clipboard.writeText(text);status('Copied.');}catch{el('palette-output').textContent=text;status('Clipboard unavailable. Select and copy the displayed text manually.',true);}}
  function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function gradient(){try{const a=colorFormats(parseColor(field('a').value)),b=colorFormats(parseColor(field('b').value)),angle=Number(field('angle').value);if(!Number.isFinite(angle)||angle<0||angle>360)throw new Error('Angle must be 0–360.');const css=`background: linear-gradient(${angle}deg, ${a.hex}, ${b.hex});`;formats={hex:a.hex,rgb:a.rgb,hsl:a.hsl,css};field('picker').value=a.hex;el('angle-value').textContent=`${angle}°`;el('gradient').style.background=`linear-gradient(${angle}deg, ${a.hex}, ${b.hex})`;el('output').textContent=`First color\n${a.hex}\n${a.rgb}\n${a.hsl}\n\nSecond color\n${b.hex}\n${b.rgb}\n${b.hsl}\n\n${css}`;for(const b of root.querySelectorAll<HTMLButtonElement>('[data-color-copy]'))b.disabled=false;}catch(error){formats={};for(const b of root.querySelectorAll<HTMLButtonElement>('[data-color-copy]'))b.disabled=true;el('output').textContent='Correct the color input to create a current result.';throw error;}}
  function checkContrast(){try{const foreground=hex(field('foreground').value),background=hex(field('background').value),ratio=contrast(foreground,background);el('sample').style.color=foreground;el('sample').style.background=background;el('ratio').textContent=`Contrast ${ratio.toFixed(2)}:1 (thresholds use the unrounded value)`;el('normal').textContent=ratio>=4.5?'Pass':'Fail';el('large').textContent=ratio>=3?'Pass':'Fail';}catch(error){el('ratio').textContent='Enter two valid opaque colors.';el('normal').textContent=el('large').textContent='—';throw error;}}
  function refresh(){field('palette-name').value=palette.name;el('palette-output').textContent=paletteCSS(palette);el<HTMLButtonElement>('add').disabled=palette.colors.length>=8;const host=el('list');host.replaceChildren();palette.colors.forEach((color,index)=>{const card=document.createElement('article'),picker=document.createElement('input'),text=document.createElement('input'),label=document.createElement('label'),actions=document.createElement('div'),roles=document.createElement('div');picker.type='color';picker.value=color;picker.setAttribute('aria-label',`Pick swatch ${index+1}`);text.value=color;text.setAttribute('aria-label',`Swatch ${index+1}, HEX RGB or HSL`);label.textContent=`Swatch ${index+1}`;label.append(text);actions.className=roles.className='bench-toolbar';
    const change=(value:string)=>act(()=>{const next=hex(value);palette.colors[index]=next;dirty=true;refresh();status('Palette updated. Gradient and contrast remain unchanged.');});picker.addEventListener('change',()=>change(picker.value));text.addEventListener('change',()=>change(text.value));
    for(const [title,delta]of [['←',-1],['→',1]] as const){const button=document.createElement('button');button.textContent=title;button.setAttribute('aria-label',`Move swatch ${index+1} ${delta<0?'left':'right'}`);button.disabled=index+delta<0||index+delta>=palette.colors.length;button.addEventListener('click',()=>{[palette.colors[index],palette.colors[index+delta]]=[palette.colors[index+delta],palette.colors[index]];dirty=true;refresh();});actions.append(button);}
    const remove=document.createElement('button');remove.textContent='Remove';remove.disabled=palette.colors.length===1;remove.addEventListener('click',()=>{palette.colors.splice(index,1);dirty=true;refresh();});actions.append(remove);
    for(const [title,id]of [['Gradient A','a'],['Gradient B','b'],['Text','foreground'],['Background','background']]){const button=document.createElement('button');button.textContent=title;button.addEventListener('click',()=>act(()=>{field(id).value=color;if(id==='a'||id==='b')gradient();else checkContrast();status(`Swatch assigned to ${title.toLowerCase()}.`);}));roles.append(button);}card.append(picker,label,actions,roles);host.append(card);});}
  function replace(next:PaletteDocument){if(dirty&&!confirm('Replace this palette? Export JSON first to keep your edits.'))return;palette=structuredClone(next);dirty=false;refresh();status('Palette imported. Existing gradient and contrast colors were kept.');}
  for(const id of ['a','b','angle'])field(id).addEventListener('input',()=>act(gradient));field('picker').addEventListener('input',()=>act(()=>{field('a').value=field('picker').value;gradient();}));
  for(const button of root.querySelectorAll<HTMLButtonElement>('[data-color-copy]'))button.addEventListener('click',()=>act(async()=>{const result=formats[button.dataset.colorCopy!];if(result)await copy(result);}));
  el('reset').addEventListener('click',()=>act(()=>{field('a').value='#ad99e5';field('b').value='#c6eaa5';field('angle').value='135';gradient();}));
  for(const id of ['foreground','background'])field(id).addEventListener('input',()=>act(checkContrast));el('swap').addEventListener('click',()=>act(()=>{const a=field('foreground').value;field('foreground').value=field('background').value;field('background').value=a;checkContrast();}));
  field('palette-name').addEventListener('change',()=>{palette.name=field('palette-name').value.slice(0,80);dirty=true;});el('add').addEventListener('click',()=>{if(palette.colors.length<8){palette.colors.push('#808080');dirty=true;refresh();}});
  el('copy-all').addEventListener('click',()=>act(()=>copy(palette.colors.join('\n'))));el('copy-variables').addEventListener('click',()=>act(()=>copy(paletteCSS(palette))));el('download-css').addEventListener('click',()=>download(new Blob([paletteCSS(palette)],{type:'text/css'}),'palette.css'));
  el('export').addEventListener('click',()=>{download(new Blob([JSON.stringify(palette,null,2)],{type:'application/json'}),'palette.json');dirty=false;});el('import').addEventListener('click',()=>field('file').click());field('file').addEventListener('change',()=>act(async()=>{const file=field('file').files?.[0];field('file').value='';if(!file)return;if(file.size>16384)throw new Error('Palette file exceeds 16 KB.');replace(decodePalette(await file.text()));}));
  window.addEventListener('beforeunload',event=>{if(dirty)event.preventDefault();});gradient();checkContrast();refresh();
  const url=new URL(location.href),id=url.searchParams.get('transfer');if(id)act(async()=>{url.searchParams.delete('transfer');history.replaceState(null,'',url);const {receiveMedia}=await import('../lib/image/handoff.ts'),payload=await receiveMedia(id,'palette');if(payload.kind==='palette'){replace(payload.palette);dirty=true;}});
}
