import {FILE_LIMIT,decode,encode,clamp,type World,type WorldId,type Brush} from '../lib/worlds/model.ts';
import {createPelagic} from '../lib/worlds/pelagic.ts';
import {createEmber} from '../lib/worlds/ember.ts';
import {WorldClient} from '../lib/worlds/client.ts';
import type {Frame} from '../lib/worlds/runtime.ts';
import {WorldView} from '../lib/worlds/render.ts';
const root=document.getElementById('element-world');if(root)setup(root);
function setup(root:HTMLElement){
  const world=root.dataset.world as WorldId,sea=world==='pelagic',el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(`element-${id}`) as T,field=(id:string)=>el<HTMLInputElement>(id),host=el('stage'),abort=new AbortController(),{signal}=abort;
  let current:Frame={state:sea?createPelagic(17):createEmber(17),running:false,undo:0,redo:0},view:WorldView|undefined,ready=false,disposed=false,busy=false,dirty=false,revision=0,raf=0,tool=sea?'flow':'lava',pointer:number|undefined,lastPoint:{x:number;y:number}|undefined,lastPaint=0,cursor={x:.5,y:.5},chain=Promise.resolve(),pendingPoint:{x:number;y:number}|undefined,lastStats=-Infinity,lastControls='';
  const status=(text:string,error=false)=>{el('status').textContent=text;el('status').dataset.error=String(error);};
  const queue=(action:()=>Promise<unknown>|void)=>{chain=chain.then(async()=>{if(!disposed)await action();}).catch(error=>{if(!disposed)status(error instanceof Error?error.message:String(error),true);});return chain;};
  function changed(){lastStats=-Infinity;dirty=true;revision++;el('image-link').hidden=true;sync();}
  function fields(){lastStats=-Infinity;field('name').value=current.state.name;field('seed').value=String(current.state.seed);for(const input of root.querySelectorAll<HTMLInputElement>('[data-element-param]'))input.value=String((current.state.params as unknown as Record<string,number>)[input.dataset.elementParam!]);}
  function sync(){const controls=[current.running,current.undo,current.redo,busy,ready,dirty,tool,!!view,document.documentElement.dataset.motion].join(':');if(controls!==lastControls){lastControls=controls;el('play').textContent=current.running?'Pause':'Flow';el('play').setAttribute('aria-pressed',String(!current.running));for(const id of ['play','step','new','import','export','name','seed','quality','radius','strength','motion','reset-view'])el<HTMLButtonElement>(id).disabled=busy||!ready;for(const input of root.querySelectorAll<HTMLInputElement>('[data-element-param]'))input.disabled=busy||!ready;if(sea)field('kind').disabled=busy||!ready;el<HTMLButtonElement>('undo').disabled=busy||!ready||!current.undo;el<HTMLButtonElement>('redo').disabled=busy||!ready||!current.redo;for(const id of ['save','png','send'])el<HTMLButtonElement>(id).disabled=busy||!ready||!view;for(const b of root.querySelectorAll<HTMLButtonElement>('[data-element-tool]')){b.disabled=busy||!ready;b.setAttribute('aria-pressed',String(b.dataset.elementTool===tool));}el('dirty').textContent=dirty?'Unsaved edits · export a world file for a backup.':'No unexported edits · local copies stay on this device.';el('motion').textContent=`Motion: ${document.documentElement.dataset.motion==='reduced'?'Reduced':'Full'}`;for(const action of ['undo','redo'])el<HTMLButtonElement>(`quick-${action}`).disabled=el<HTMLButtonElement>(action).disabled;}const now=performance.now();if(now-lastStats<250)return;lastStats=now;const d=current.state;el('count').textContent=d.world==='pelagic'?`${d.creatures.filter(c=>c.kind==='jelly').length}/24 jellies · ${d.creatures.filter(c=>c.kind==='fish').length}/160 fish · ${d.creatures.filter(c=>c.kind==='plankton').length}/240 sparks · ${d.lights.length}/6 lights`:`128 × 128 cells · ${(d.tick/30).toFixed(1)} simulated seconds`;}
  function draw(){raf=0;if(disposed||document.hidden)return;view?.draw(current.state,current.running&&sea);if(current.running&&sea)raf=requestAnimationFrame(draw);}
  function schedule(){if(!raf&&!document.hidden&&!disposed)raf=requestAnimationFrame(draw);}
  const client=new WorldClient(frame=>{current=frame;view?.setFrame(frame.state);sync();schedule();},()=>status('Worker unavailable. Continuing locally from the last displayed state; undo history restarted.',true));
  function makeView(){view?.dispose();view=undefined;const quality=field('quality').value,low=quality==='low'||quality==='auto'&&(innerWidth<760||matchMedia('(pointer: coarse)').matches);try{view=new WorldView(host,world,low);view.setTool(tool);view.setFrame(current.state);view.mark(cursor.x,cursor.y,Number(field('radius').value),false);el('loading').hidden=true;schedule();}catch(error){el('loading').textContent='The picture could not start. World files can still be exported.';el('loading').hidden=false;status(String(error),true);}sync();}
  function end(){if(pointer===undefined)return;if(pendingPoint)brush(pendingPoint,false,true);pointer=undefined;lastPoint=undefined;pendingPoint=undefined;void queue(()=>client.request('end'));}
  function choose(next:string){end();tool=next;view?.setTool(tool);el('hint').textContent=sea?(tool==='flow'?'Drag to make a current. Life follows at its own pace.':tool==='add'?'Click to place life. Choose a species in Your sea.':tool==='light'?'Place a light. Fish gather; nearby jellyfish make room.':'Brush away creatures and lights.'):tool==='lava'?'Pour a little molten earth. Give it time to move.':tool==='heat'?'Warm a cooled surface until it flows again.':tool==='cool'?'Draw out the heat. Leave a dark, fractured memory.':'Lift away deposited material. The underlying terrain stays.';sync();}
  function brush(point:{x:number;y:number},initial=false,flush=false){cursor=point;pendingPoint=point;root.dataset.engaged='true';view?.mark(point.x,point.y,Number(field('radius').value));schedule();const now=performance.now(),radius=Number(field('radius').value),from=lastPoint??point;if(!initial&&!flush&&now-lastPaint<28)return;if(!initial&&sea&&(tool==='add'||tool==='light'))return;lastPaint=now;const distance=Math.hypot(point.x-from.x,point.y-from.y);if(!initial&&(distance===0||!flush&&tool!=='flow'&&distance<radius*.3))return;const count=Math.min(32,Math.max(1,Math.ceil(distance/(radius*.4)))),dx=distance?(point.x-from.x)/distance*.65:.25,dy=distance?(point.y-from.y)/distance*.65:0,brushes:Brush[]=[];for(let i=1;i<=count;i++)brushes.push({tool,x:from.x+(point.x-from.x)*i/count,y:from.y+(point.y-from.y)*i/count,radius,strength:Number(field('strength').value),kind:sea?field('kind').value as Brush['kind']:undefined,dx,dy});lastPoint=point;pendingPoint=undefined;revision++;void queue(async()=>{const result=await client.request('paint',brushes);if(client.lastPaintChanged)changed();if(typeof result==='string'&&result)status(result);});}
  host.addEventListener('pointerdown',e=>{if(!ready||busy||pointer!==undefined||e.button!==0||!view)return;const p=view.point(e.clientX,e.clientY);if(!p)return;host.focus();host.setPointerCapture(e.pointerId);pointer=e.pointerId;lastPoint=undefined;void queue(()=>client.request('begin'));brush(p,true);},{signal});
  host.addEventListener('pointermove',e=>{if(!ready||busy||!view)return;const p=view.point(e.clientX,e.clientY);if(!p)return;if(pointer===e.pointerId)brush(p);else if(pointer===undefined){cursor=p;view.mark(p.x,p.y,Number(field('radius').value));schedule();}},{signal});
  for(const type of ['pointerup','pointercancel','lostpointercapture'])host.addEventListener(type,e=>{const event=e as PointerEvent;if(event.pointerId!==pointer)return;if(type==='pointerup'){const p=view?.point(event.clientX,event.clientY);if(p)pendingPoint=p;}end();},{signal});host.addEventListener('pointerleave',()=>{if(pointer===undefined){view?.mark(cursor.x,cursor.y,1,false);schedule();}},{signal});host.addEventListener('contextmenu',e=>e.preventDefault(),{signal});
  for(const b of root.querySelectorAll<HTMLButtonElement>('[data-element-tool]'))b.addEventListener('click',()=>choose(b.dataset.elementTool!),{signal});
  function panelMode(open:boolean){const modal=open&&matchMedia('(max-width: 760px)').matches;el('panel').setAttribute('role',modal?'dialog':'complementary');el('panel').setAttribute('aria-modal',String(modal));el('backdrop').hidden=!modal;host.inert=modal;}
  window.addEventListener('resize',()=>panelMode(!el('panel').hidden),{signal});
  function togglePanel(open:boolean){end();panelMode(open);el('panel').hidden=!open;el('panel-toggle').setAttribute('aria-expanded',String(open));el(open?'panel-close':'panel-toggle').focus();}
  el('panel-toggle').addEventListener('click',()=>togglePanel(el('panel').hidden),{signal});el('panel-close').addEventListener('click',()=>togglePanel(false),{signal});el('backdrop').addEventListener('click',()=>togglePanel(false),{signal});el('panel').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();togglePanel(false);}if(e.key==='Tab'&&matchMedia('(max-width: 760px)').matches){const items=[...el('panel').querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled):not([type=hidden]):not([type=file]),select:not(:disabled),a:not([hidden]),summary')].filter(n=>!n.hidden),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}},{signal});
  for(const action of ['undo','redo'])el(`quick-${action}`).addEventListener('click',()=>el<HTMLButtonElement>(action).click(),{signal});
  field('radius').addEventListener('input',()=>{view?.mark(cursor.x,cursor.y,Number(field('radius').value));schedule();},{signal});
  const pause=()=>{end();void queue(()=>client.request(current.running?'pause':'run'));};
  el('play').addEventListener('click',pause,{signal});el('step').addEventListener('click',()=>{end();changed();void queue(()=>client.request('step'));},{signal});
  for(const action of ['undo','redo'] as const)el(action).addEventListener('click',()=>{end();changed();void queue(async()=>{await client.request(action);fields();});},{signal});
  host.addEventListener('keydown',e=>{if(e.target!==host||!ready||busy)return;if(['1','2','3','4'].includes(e.key)){e.preventDefault();choose((sea?['flow','add','light','remove']:['lava','heat','cool','remove'])[Number(e.key)-1]);}else if(e.key.startsWith('Arrow')){e.preventDefault();const n=e.shiftKey?.05:.012;cursor={x:clamp(cursor.x+(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0)),y:clamp(cursor.y+(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0))};view?.mark(cursor.x,cursor.y,Number(field('radius').value));schedule();}else if(e.key==='Enter'){e.preventDefault();if(pointer!==undefined)return;pointer=-1;void queue(()=>client.request('begin'));brush(cursor,true);end();}else if(e.key===' '){e.preventDefault();pause();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();el<HTMLButtonElement>(e.shiftKey?'redo':'undo').click();}},{signal});
  for(const input of root.querySelectorAll<HTMLInputElement>('[data-element-param]'))input.addEventListener('change',()=>{end();changed();void queue(()=>client.request('params',{[input.dataset.elementParam!]:Number(input.value)}));},{signal});field('name').addEventListener('change',()=>{changed();void queue(()=>client.request('name',field('name').value.slice(0,80)));},{signal});
  field('quality').addEventListener('change',makeView,{signal});el('reset-view').addEventListener('click',()=>{cursor={x:.5,y:.5};view?.resize();view?.mark(.5,.5,1,false);schedule();status('The full world is back in view.');},{signal});
  el('motion').addEventListener('click',()=>{end();const reduced=document.documentElement.dataset.motion!=='reduced';document.documentElement.dataset.motion=reduced?'reduced':'full';try{localStorage.setItem('ortunate:motion',reduced?'reduced':'full');}catch{}void queue(()=>client.request(reduced?'pause':'run'));sync();},{signal});
  function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function canReplace(){return !dirty||confirm('Replace this world? Save or export first to keep your edits.');}
  async function replace(d:World,saved=false){end();await client.load(d);dirty=!saved;revision++;fields();if(document.documentElement.dataset.motion!=='reduced'&&!document.hidden)await client.request('run');status('A new beginning. Make yourself at home.');sync();}
  el('new').addEventListener('click',()=>{end();void queue(async()=>{const seed=Number(field('seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295)throw new Error('Use a whole seed from 0 to 4294967295.');if(canReplace())await replace(sea?createPelagic(seed):createEmber(seed));});},{signal});
  function exclusive(action:(d:World)=>Promise<void>){if(busy||!ready)return;end();busy=true;sync();void queue(async()=>{const resume=current.running;try{const d=await client.request('snapshot') as World;await action(d);}finally{busy=false;if(!disposed){if(resume&&!document.hidden&&document.documentElement.dataset.motion!=='reduced')await client.request('run');sync();}}});}
  el('export').addEventListener('click',()=>exclusive(async d=>{download(new Blob([encode(d)],{type:'application/json'}),`${world}-${d.seed}.${world}.json`);dirty=false;status('Editable world exported, including the current simulation state.');}),{signal});
  el('png').addEventListener('click',()=>exclusive(async d=>{const blob=await view!.snapshot(d);if(disposed)return;download(blob,`${world}-${d.seed}.png`);status('1600 × 1000 PNG exported without editing overlays.');}),{signal});
  el('send').addEventListener('click',()=>exclusive(async d=>{el('image-link').hidden=true;const blob=await view!.snapshot(d),{sendMedia}=await import('../lib/image/handoff.ts'),id=await sendMedia({kind:'image',blob,name:`${world}-${d.seed}.png`});if(disposed)return;el<HTMLAnchorElement>('image-link').href=`/tools/image/?transfer=${id}`;el('image-link').hidden=false;status('Picture prepared for five minutes. Open Image Bench in a new tab.');}),{signal});
  el('import').addEventListener('click',()=>field('file').click(),{signal});field('file').addEventListener('change',()=>{const file=field('file').files?.[0];field('file').value='';if(!file)return;if(file.size>FILE_LIMIT){status('World files are limited to 2 MiB.',true);return;}const token=revision;void file.text().then(text=>{if(file.size>FILE_LIMIT)throw new Error('World files are limited to 2 MiB.');const d=decode(text,world);if(disposed||busy||token!==revision)return;void queue(async()=>{if(token===revision&&canReplace())await replace(d,true);});}).catch(error=>{if(!disposed)status(String(error),true);});},{signal});
  async function library(){const {listWorlds,removeWorld,restoreWorld}=await import('../lib/worlds/storage.ts'),records=await listWorlds(world);if(disposed)return;const container=el('library');container.replaceChildren();if(!records.length){container.textContent='No saved worlds yet. Save a new copy above.';return;}for(const record of records){const card=document.createElement('article'),image=document.createElement('img'),name=document.createElement('h4'),row=document.createElement('div'),open=document.createElement('button'),remove=document.createElement('button');card.className='element-library-item';image.src=record.thumbnail;image.alt='Saved world preview';image.loading='lazy';name.textContent=record.name;row.className='element-row';open.textContent='Open';remove.textContent='Remove';open.addEventListener('click',()=>{if(busy)return;end();void queue(async()=>{if(canReplace())await replace(restoreWorld(record,world),true);});});remove.addEventListener('click',()=>{if(busy||!confirm(`Remove “${record.name}”? Export a backup first; this cannot be undone.`))return;void queue(async()=>{await removeWorld(world,record.id);await library();status('Saved copy removed. The current world is unchanged.');});});row.append(open,remove);card.append(image,name,row);container.append(card);}}
  el('save').addEventListener('click',()=>exclusive(async d=>{const blob=await view!.snapshot(d,400),thumbnail=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Thumbnail export failed. Export your world file instead.'));reader.readAsDataURL(blob);}),{saveWorld}=await import('../lib/worlds/storage.ts');await saveWorld(d,thumbnail);if(disposed)return;dirty=false;await library();status('A new copy is saved on this device. Export a world file for a portable backup.');}),{signal});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){end();cancelAnimationFrame(raf);raf=0;void queue(()=>client.request('pause'));}else schedule();},{signal});window.addEventListener('blur',end,{signal});window.addEventListener('beforeunload',e=>{if(dirty)e.preventDefault();},{signal});const observer=new ResizeObserver(()=>{view?.resize();schedule();});observer.observe(host);window.addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);abort.abort();observer.disconnect();client.dispose();view?.dispose();});window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
  sync();void queue(async()=>{await client.load(current.state);ready=true;fields();makeView();if(document.documentElement.dataset.motion!=='reduced'&&!document.hidden)await client.request('run');});void library().catch(()=>{if(!disposed)el('library').textContent='Local library unavailable. Export world files to keep your work.';});
}
