import { BATCH_LIMIT,ImageEditor,defaultRecipe,transformedSize,resetTransform,fitCrop,outputName,validateRecipe,type ImageSourceInfo,type ImageRecipe,type ImageJobResult,type ImageFormat } from '../lib/image/model.ts';
import { inspectImage } from '../lib/image/inspect.ts';
import { ImageProcessor } from '../lib/image/client.ts';
import { paletteDocument,type Swatch } from '../lib/image/palette.ts';
import type { CropView } from '../lib/image/crop-view.ts';
interface Item {file:File;info?:ImageSourceInfo;result?:ImageJobResult;error?:string;exported:boolean;working?:boolean}
const root=document.getElementById('image-bench');if(root)setup(root);
function setup(root:HTMLElement){
  const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(`image-${id}`) as T,field=(id:string)=>el<HTMLInputElement>(id);
  let mode:'single'|'batch'='single',items:Item[]=[],editor:ImageEditor|undefined,view:CropView|undefined,revision=0,paletteRevision=0,busy=false,loading=false,disposed=false,dirty=false,zipBusy=false;
  let formats:ImageFormat[]=['image/png'],palette:Swatch[]=[],urls:string[]=[],before=false,debounce:ReturnType<typeof setTimeout>|undefined;
  const processor=new ImageProcessor(),paletteProcessor=new ImageProcessor(),canvas=el<HTMLCanvasElement>('canvas');
  const status=(message:string,error=false)=>{el('status').textContent=message;el('status').dataset.error=String(error);};
  const act=(action:()=>Promise<unknown>)=>{void action().catch(error=>{if(!disposed&&!/^(Operation|Archive) cancelled\.$/.test(error instanceof Error?error.message:''))status(error instanceof Error?error.message:'Operation failed.',true);});};
  const bytes=(n:number)=>n>=1048576?`${(n/1048576).toFixed(2)} MiB`:`${(n/1024).toFixed(1)} KiB`;
  function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function clearPreview(){for(const url of urls)URL.revokeObjectURL(url);urls=[];el<HTMLImageElement>('comparison-img').removeAttribute('src');el('result').hidden=true;}
  function clearPalette(){palette=[];paletteRevision++;paletteProcessor.cancel();el('swatches').replaceChildren();el('palette-link').hidden=true;}
  function cancel(silent=false){revision++;processor.cancel();paletteProcessor.cancel();paletteRevision++;if(debounce)clearTimeout(debounce);debounce=undefined;busy=false;zipBusy=false;for(const item of items)item.working=false;if(!silent)status('Cancelled. Completed batch results are still available.');sync();renderQueue();}
  function invalidate(auto=true){cancel(true);for(const item of items){item.result=undefined;item.exported=false;if(item.info)item.error=undefined;}clearPreview();clearPalette();dirty=!!items.length;sync();renderQueue();if(auto&&mode==='single'&&editor)debounce=setTimeout(()=>act(renderSingle),450);}
  function settings(recipe:ImageRecipe):ImageRecipe{return{...structuredClone(recipe),maxWidth:Number(field('max-width').value),maxHeight:Number(field('max-height').value),allowUpscale:field('upscale').checked,format:field('format').value as ImageFormat,mode:field('format').value==='image/png'?'quality':field('compression').value as 'quality'|'target',quality:Number(field('quality').value)/100,targetBytes:Number(field('target').value)*1024,background:field('background').value};}
  function syncSettings(r:ImageRecipe){for(const [id,value]of Object.entries({'max-width':r.maxWidth,'max-height':r.maxHeight,format:r.format,compression:r.mode,quality:r.quality*100,target:r.targetBytes/1024,background:r.background}))field(id).value=String(value);field('upscale').checked=r.allowUpscale;}
  function sync(){
    const single=mode==='single',result=items[0]?.result,r=editor?.recipe;
    el('single').hidden=!single;el('batch').hidden=single;el('palette-panel').hidden=!single;field('files').multiple=!single;el('open').textContent=single?'Choose an image ↗':'Choose up to 10 images ↗';el('mode-hint').textContent=single?'Precise crop, real encoded comparison, and colors to keep.':'Uniform resize and encoding. No hidden crop or transform.';
    for(const button of root.querySelectorAll<HTMLButtonElement>('[data-image-mode]')){button.setAttribute('aria-pressed',String(button.dataset.imageMode===mode));button.disabled=loading;}
    el<HTMLButtonElement>('open').disabled=loading;el<HTMLButtonElement>('render').disabled=!single||!editor||busy||loading;el<HTMLButtonElement>('cancel').disabled=!busy&&!zipBusy;el<HTMLButtonElement>('run-batch').disabled=single||!items.length||busy||loading;el<HTMLButtonElement>('zip').disabled=busy||zipBusy||!items.some(i=>i.result);el<HTMLButtonElement>('download').disabled=!result||busy;
    el<HTMLButtonElement>('undo').disabled=!editor?.undoStack.length||loading;el<HTMLButtonElement>('redo').disabled=!editor?.redoStack.length||loading;
    for(const id of ['extract','palette-json','send-palette'])el<HTMLButtonElement>(id).disabled=id==='extract'?!result||busy:!palette.length;
    const png=field('format').value==='image/png',target=field('compression').value==='target'&&!png;
    field('compression').disabled=png;el('quality-label').hidden=png||target;el('target-label').hidden=!target;el('background-label').hidden=field('format').value!=='image/jpeg';el('quality-value').textContent=`${field('quality').value}%`;el('compression-help').textContent=png?'PNG preserves pixels; quality and target-size controls do not apply.':target?'Searches the current dimensions, at most eight real encodes.':'Quality is interpreted by this browser’s encoder.';
    if(r)for(const key of ['x','y','width','height'] as const)field(`crop-${key}`).value=String(Number(r.crop[key].toFixed(2)));
    for(const id of ['ratio','crop-x','crop-y','crop-width','crop-height','rotate-left','rotate-right','flip-x','flip-y','reset-crop'])el<HTMLButtonElement>(id).disabled=!editor||loading;
  }
  function commit(r:ImageRecipe){if(!editor)return;try{if(editor.commit(r)){view?.update(editor.recipe);syncSettings(editor.recipe);invalidate();}}catch(error){status(String(error),true);}sync();}
  async function load(files:File[]){
    if(loading)return;if(!files.length)return;if(files.length>(mode==='single'?1:10))throw new Error(mode==='single'?'Single mode accepts one image. Choose Small batch for multiple files.':'Choose at most 10 images.');if(files.reduce((n,f)=>n+f.size,0)>BATCH_LIMIT)throw new Error('Batch inputs exceed 100 MiB.');if(dirty&&!confirm('Replace these images and edits? Download current results first to keep them.'))return;
    cancel(true);loading=true;sync();const token=revision;
    try{const next:Item[]=[];for(const file of files){try{next.push({file,info:await inspectImage(file),exported:false});}catch(error){if(mode==='single')throw error;next.push({file,error:String(error),exported:false});}if(token!==revision||disposed)return;}
      let image:ImageBitmap|HTMLImageElement|undefined;const first=next.find(i=>i.info);if(mode==='single'&&first?.info){const api=await import('../lib/image/process.ts');const original=await api.decode(first.file);try{const s=transformedSize(first.info,0),scale=Math.min(1,1600/s.width,1600/s.height);if(typeof createImageBitmap!=='undefined')image=await createImageBitmap(original,{resizeWidth:Math.max(1,Math.round(s.width*scale)),resizeHeight:Math.max(1,Math.round(s.height*scale)),resizeQuality:'high'});else image=original;}finally{if(image!==original)api.release(original);}if(token!==revision||disposed){if(image)api.release(image);return;}}
      cancel(true);clearPreview();clearPalette();view?.clear();items=next;editor=mode==='single'&&first?.info?new ImageEditor(first.info):undefined;
      if(first?.info){const r=editor?.recipe??defaultRecipe(first.info);if(!formats.includes(r.format))r.format='image/png';syncSettings(r);}field('ratio').value='free';if(view)view.ratio=null;
      if(editor&&image)view?.setImage(image,editor.info,editor.recipe);else if(image&&(image as ImageBitmap).close)(image as ImageBitmap).close();
      el('source-info').textContent=first?.info?`${first.file.name} · ${transformedSize(first.info,0).width} × ${transformedSize(first.info,0).height} · ${bytes(first.file.size)}`:'NO VALID IMAGE';dirty=true;renderQueue();status(mode==='single'?'Adjust the crop and output settings. A real encoded preview is being prepared.':'Queue ready. Shared settings apply without cropping or rotation.');
    }finally{loading=false;sync();}
    if(mode==='single'&&editor)await renderSingle();
  }
  async function renderSingle(){if(!editor||!items[0]||loading)return;const item=items[0],recipe=structuredClone(editor.recipe);cancel(true);clearPreview();clearPalette();item.result=undefined;const token=revision;busy=true;sync();status('Encoding locally…');try{const result=await processor.encode(item.file,recipe,true);if(token!==revision||disposed)return;item.result=result;item.error=undefined;showResult(result);status(result.metTarget?'Result ready. The displayed size is the actual encoded file size.':`Target not met. Smallest tried result: ${bytes(result.blob.size)}. Dimensions were not reduced.`,!result.metTarget);}finally{if(token===revision){busy=false;sync();}}}
  function showResult(result:ImageJobResult){clearPreview();urls=[URL.createObjectURL(result.before??result.blob),URL.createObjectURL(result.blob)];before=false;setComparison();el('result').hidden=false;el('result-info').textContent=`${result.width} × ${result.height} · ${result.blob.type.split('/')[1].toUpperCase()} · ${bytes(result.blob.size)}`;const delta=result.blob.size-items[0].file.size;el('result-detail').textContent=`${delta<=0?'Smaller':'Larger'} than original by ${bytes(Math.abs(delta))}. ${result.attempts} encoding attempt(s). ${result.quality===null?'Lossless PNG.':`Quality tried: ${Math.round(result.quality*100)}%.`} ${result.metTarget?'':'Target not met; this download is above the requested size.'}`;}
  function setComparison(){el<HTMLImageElement>('comparison-img').src=urls[before?0:1]??'';el<HTMLImageElement>('comparison-img').alt=before?'Same crop and dimensions before lossy encoding':'Actual decoded output file';el('before').setAttribute('aria-pressed',String(before));el('after').setAttribute('aria-pressed',String(!before));}
  function renderQueue(){const host=el('queue');host.replaceChildren();items.forEach((item,index)=>{const article=document.createElement('article'),title=document.createElement('h3'),detail=document.createElement('p'),actions=document.createElement('div');actions.className='bench-toolbar';title.textContent=item.file.name;detail.textContent=item.working?'Processing…':item.error??(item.result?`${bytes(item.file.size)} → ${bytes(item.result.blob.size)} · ${item.result.width} × ${item.result.height}${item.result.metTarget?'':' · TARGET NOT MET'}`:`${bytes(item.file.size)} · Ready`);const retry=document.createElement('button');retry.textContent=item.result?'Process again':'Process / retry';retry.disabled=busy||loading||!item.info;retry.addEventListener('click',()=>act(()=>runBatch([index])));actions.append(retry);if(item.result){const button=document.createElement('button');button.textContent='Download';button.addEventListener('click',()=>{download(item.result!.blob,names()[index]);item.exported=true;dirty=items.some(i=>i.info&&!i.exported);});actions.append(button);}article.append(title,detail,actions);host.append(article);});}
  function names(){const used=new Set<string>();return items.map(i=>outputName(i.file.name,(i.result?.blob.type??field('format').value) as ImageFormat,used));}
  async function runBatch(indices=items.map((_,i)=>i).filter(i=>!items[i].result)){
    if(busy||loading)return;for(const index of indices){const item=items[index];if(item.info)validateRecipe(settings(defaultRecipe(item.info)),item.info);}cancel(true);const token=revision;busy=true;sync();
    try{for(const index of indices){if(token!==revision||disposed)return;const item=items[index];if(!item.info)continue;item.result=undefined;item.error=undefined;item.working=true;renderQueue();status(`Processing ${index+1} / ${items.length}: ${item.file.name}`);try{const result=await processor.encode(item.file,settings(defaultRecipe(item.info)));if(token!==revision)return;const total=items.reduce((n,i)=>n+(i.result?.blob.size??0),0)+result.blob.size;if(total>BATCH_LIMIT)throw new Error('Completed results would exceed 100 MiB. Reduce dimensions or download and clear this batch.');item.result=result;item.exported=false;}catch(error){if(token!==revision)return;item.error=error instanceof Error?error.message:String(error);}item.working=false;renderQueue();}status('Batch finished. Download successful results; failed items can be retried.');}finally{if(token===revision){busy=false;sync();renderQueue();}}
  }
  for(const button of root.querySelectorAll<HTMLButtonElement>('[data-image-mode]'))button.addEventListener('click',()=>{if(button.dataset.imageMode===mode)return;if(dirty&&!confirm('Switch modes and clear these images? Download results first to keep them.'))return;cancel(true);clearPreview();clearPalette();view?.clear();items=[];editor=undefined;dirty=false;mode=button.dataset.imageMode as typeof mode;el('source-info').textContent='NO IMAGE YET';sync();renderQueue();});
  el('open').addEventListener('click',()=>field('files').click());field('files').addEventListener('change',()=>{const files=Array.from(field('files').files??[]);field('files').value='';act(()=>load(files));});
  const drop=el('drop');drop.addEventListener('dragover',e=>{e.preventDefault();drop.dataset.over='true';});drop.addEventListener('dragleave',()=>drop.dataset.over='false');drop.addEventListener('drop',e=>{e.preventDefault();drop.dataset.over='false';act(()=>load(Array.from(e.dataTransfer?.files??[])));});document.addEventListener('paste',e=>{if((e.target as HTMLElement)?.matches('input,textarea'))return;const files=Array.from(e.clipboardData?.files??[]);if(files.length){e.preventDefault();act(()=>load(files));}});
  for(const id of ['max-width','max-height','upscale','format','compression','quality','target','background'])field(id).addEventListener('change',()=>{if(editor){commit(settings(editor.recipe));}else invalidate(false);sync();});field('quality').addEventListener('input',()=>el('quality-value').textContent=`${field('quality').value}%`);
  field('ratio').addEventListener('change',()=>{if(!editor)return;const size=transformedSize(editor.info,editor.recipe.rotation),value=field('ratio').value,ratio=value==='free'?null:value==='original'?size.width/size.height:Number(value);if(view)view.ratio=ratio;commit({...editor.recipe,crop:fitCrop(size,ratio)});});
  for(const key of ['x','y','width','height'] as const)field(`crop-${key}`).addEventListener('change',()=>{if(!editor)return;field('ratio').value='free';if(view)view.ratio=null;commit({...editor.recipe,crop:{...editor.recipe.crop,[key]:Number(field(`crop-${key}`).value)}});});
  for(const [id,delta]of [['rotate-left',3],['rotate-right',1]] as const)el(id).addEventListener('click',()=>{if(editor){field('ratio').value='free';if(view)view.ratio=null;commit(resetTransform(editor.recipe,editor.info,{rotation:((editor.recipe.rotation+delta)%4) as ImageRecipe['rotation']}));view?.fit();}});
  for(const [id,key]of [['flip-x','flipX'],['flip-y','flipY']] as const)el(id).addEventListener('click',()=>{if(editor){field('ratio').value='free';if(view)view.ratio=null;commit(resetTransform(editor.recipe,editor.info,{[key]:!editor.recipe[key]}));}});
  el('reset-crop').addEventListener('click',()=>{if(editor){field('ratio').value='free';if(view)view.ratio=null;commit(resetTransform(editor.recipe,editor.info,{}));}});
  for(const id of ['undo','redo'] as const)el(id).addEventListener('click',()=>{if(editor?.[id]()){field('ratio').value='free';if(view)view.ratio=null;syncSettings(editor.recipe);view?.update(editor.recipe);invalidate();sync();}});
  el('fit').addEventListener('click',()=>view?.fit());el('actual').addEventListener('click',()=>view?.setZoom(1));el('zoom-in').addEventListener('click',()=>view?.zoomBy(1.25));el('zoom-out').addEventListener('click',()=>view?.zoomBy(.8));
  el('before').addEventListener('click',()=>{before=true;setComparison();});el('after').addEventListener('click',()=>{before=false;setComparison();});el('result-fit').addEventListener('click',()=>el('comparison').dataset.actual='false');el('result-actual').addEventListener('click',()=>el('comparison').dataset.actual='true');
  el('render').addEventListener('click',()=>act(renderSingle));el('cancel').addEventListener('click',()=>cancel());el('run-batch').addEventListener('click',()=>act(()=>runBatch()));
  el('clear').addEventListener('click',()=>{if(dirty&&!confirm('Clear these images? Unexported edits and results will be lost.'))return;cancel(true);clearPreview();clearPalette();view?.clear();items=[];editor=undefined;dirty=false;el('source-info').textContent='NO IMAGE YET';sync();renderQueue();status('Images cleared from this workspace. Original files were not changed.');});
  el('download').addEventListener('click',()=>{const item=items[0];if(item?.result){download(item.result.blob,names()[0]);item.exported=true;dirty=false;}});
  el('zip').addEventListener('click',()=>act(async()=>{if(zipBusy)return;const token=revision,filenames=names(),files=items.flatMap((item,i)=>item.result?[{name:filenames[i],blob:item.result.blob}]:[]);zipBusy=true;sync();try{const {zipResults}=await import('../lib/image/zip.ts');const blob=await zipResults(files,()=>{if(token!==revision||disposed)throw new Error('Archive cancelled.');});download(blob,'image-bench.zip');items.forEach(i=>{if(i.result)i.exported=true;});dirty=items.some(i=>i.info&&!i.exported);status('Completed images exported as a ZIP. Failed items were excluded.');}finally{if(token===revision){zipBusy=false;sync();}}}));
  function renderPalette(){el('swatches').replaceChildren();for(const swatch of palette){const card=document.createElement('article');card.className='bench-swatch';const color=document.createElement('i');color.style.background=swatch.hex;const body=document.createElement('div'),text=document.createElement('p'),button=document.createElement('button');text.textContent=`${swatch.hex} · RGB ${[1,3,5].map(i=>parseInt(swatch.hex.slice(i,i+2),16)).join(', ')} · ~${Math.round(swatch.share*100)}%`;button.textContent='Copy HEX';button.addEventListener('click',()=>act(async()=>{await navigator.clipboard.writeText(swatch.hex);status('Color copied.');}));body.append(text,button);card.append(color,body);el('swatches').append(card);}}
  el('extract').addEventListener('click',()=>act(async()=>{const result=items[0]?.result;if(!result)return;clearPalette();const token=revision,p=paletteRevision;status('Finding colors in the encoded result…');const colors=await paletteProcessor.palette(result.blob,Number(field('color-count').value));if(token!==revision||p!==paletteRevision||disposed)return;palette=colors;renderPalette();sync();status(colors.length?'Palette ready. You can refine it in Color Workshop.':'No visible pixels to extract. The image is transparent.');}));field('color-count').addEventListener('change',()=>{clearPalette();sync();});
  el('palette-json').addEventListener('click',()=>{if(palette.length)download(new Blob([JSON.stringify(paletteDocument(palette.map(s=>s.hex),'Image palette'),null,2)],{type:'application/json'}),'image-palette.json');});
  el('send-palette').addEventListener('click',()=>act(async()=>{if(!palette.length)return;const token=revision,p=paletteRevision,{sendMedia}=await import('../lib/image/handoff.ts');const id=await sendMedia({kind:'palette',palette:paletteDocument(palette.map(s=>s.hex),'Image palette')});if(token!==revision||p!==paletteRevision||disposed)return;const link=el<HTMLAnchorElement>('palette-link');link.href=`/tools/color/?transfer=${id}`;link.hidden=false;status('Palette prepared for five minutes. Open the link to continue in a new tab.');}));
  const observer=new ResizeObserver(()=>view?.resize());observer.observe(canvas);window.addEventListener('beforeunload',e=>{if(dirty)e.preventDefault();});window.addEventListener('pagehide',()=>{disposed=true;cancel(true);view?.dispose();clearPreview();observer.disconnect();items=[];});window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
  act(async()=>{loading=true;sync();try{try{const {CropView}=await import('../lib/image/crop-view.ts');if(disposed)return;view=new CropView(canvas,crop=>{if(editor)commit({...editor.recipe,crop});});}catch{status('Canvas preview unavailable. Use numeric crop controls.',true);}formats=await processor.formats();for(const option of el<HTMLSelectElement>('format').options)option.disabled=!formats.includes(option.value as ImageFormat);if(!formats.length)throw new Error('No supported image encoder was found.');}finally{loading=false;sync();}const url=new URL(location.href),id=url.searchParams.get('transfer');if(id){url.searchParams.delete('transfer');history.replaceState(null,'',url);const {receiveMedia}=await import('../lib/image/handoff.ts'),payload=await receiveMedia(id,'image');if(payload.kind==='image')await load([new File([payload.blob],payload.name,{type:payload.blob.type})]);}});
  sync();
}
