import { models, type ModelId } from '../lib/lab/definitions.ts';
import { growthValue, kernelValue } from '../lib/lab/engine.ts';
import { drawState } from '../lib/lab/render.ts';
import { decodeExperiment, encodeExperiment, MAX_FILE_BYTES, type Experiment, type Scan, type ScanSettings } from '../lib/lab/session.ts';
import { deleteExperiment, listExperiments, saveExperiment } from '../lib/lab/storage.ts';
import type { Frame, Reply } from '../lib/lab/runtime.ts';

const root = document.querySelector<HTMLElement>('[data-lab]');
if (root) setup(root);
function setup(root: HTMLElement) {
  const model = root.dataset.lab as ModelId, definition = models[model];
  const el = <T extends HTMLElement = HTMLElement>(id: string) => document.getElementById(`lab-${id}`) as T;
  const value = (id: string) => (el<HTMLInputElement | HTMLSelectElement>(id)).value;
  const status = (message: string, error = false) => { el('status').textContent = message; el('status').dataset.error = String(error); };
  const worker = new Worker(new URL('./lab.worker.ts', import.meta.url), { type: 'module' });
  let generation = 0, sequence = 0, latest: Frame | undefined, mode = 'single', scan: Scan | undefined, frameCount = 0, fpsStart = performance.now(), disposed = false, lastSize = 0, lastSeed = -1;
  const pending = new Map<number, { resolve: (data: any) => void; reject: (error: Error) => void; timer: ReturnType<typeof setTimeout> }>();
  const request = (command: string, data?: unknown): Promise<any> => new Promise((resolve, reject) => { const id = ++sequence; const timer = setTimeout(() => { pending.delete(id); reject(new Error('The simulation worker did not respond. Export a backup if possible, then reload.')); }, 30000); pending.set(id, { resolve, reject, timer }); worker.postMessage({ id, generation, command, data }); });
  const act = (action: () => Promise<unknown>) => { void action().catch(error => status(error instanceof Error ? error.message : 'Operation failed.', true)); };
  const canvasA = el<HTMLCanvasElement>('canvas-a'), canvasB = el<HTMLCanvasElement>('canvas-b');
  const format = (n: number) => Math.abs(n) >= 1000 ? n.toLocaleString('en', { maximumFractionDigits: 1 }) : Number(n.toPrecision(5)).toString();
  worker.onmessage = (event: MessageEvent<Reply>) => {    
const message = event.data; if (message.generation !== generation) return;
    if (message.type === 'reply') { const p = pending.get(message.id!); if (p) { clearTimeout(p.timer); pending.delete(message.id!); message.error ? p.reject(new Error(message.error)) : p.resolve(message.data); } return; }
    if (message.type === 'frame') { latest = message.data as Frame; render(); return; }
    if (message.error) { status(message.error, true); return; }
    const data = message.data; if (data.scan) { scan = data.scan; renderScan(); } const completed = data.index || 0, total = data.total || 1, fraction = data.steps ? data.done / data.steps : 0; el<HTMLProgressElement>('scan-progress').value = (completed + fraction) / total; el('scan-status').textContent = data.complete ? `${total} cells complete. Inspect a result or save this atlas.` : `${completed} / ${total} cells complete${data.steps ? ` · cell step ${data.done} / ${data.steps}` : ''}`;
  };
  worker.onerror = (event) => { event.preventDefault(); status('Simulation worker failed. Reload to restart; saved files are unaffected.', true); for (const p of pending.values()) { clearTimeout(p.timer); p.reject(new Error('Simulation worker failed.')); } pending.clear(); };

  function render() {    
if (!latest) return; const f = latest; drawState(canvasA, f.a, f.view, f.derivedA); if (f.b) drawState(canvasB, f.b, f.view, f.derivedB); el('figure-b').hidden = !f.b; el('compare-tools').hidden = !f.b;
    el('tick-a').textContent = `STEP ${f.a.tick.toLocaleString()}`; el('tick-b').textContent = `STEP ${f.b?.tick.toLocaleString() || 0}`; el('time').textContent = format(f.a.time); el('rate').textContent = f.running ? f.stepsPerSecond.toFixed(1) : '0'; el('compute').textContent = `${f.computeMs.toFixed(1)} ms`; el('run').textContent = f.running ? 'Pause Ⅱ' : 'Run ▶'; el('run-state').textContent = f.scanning ? 'SCANNING' : f.running ? 'RUNNING' : 'PAUSED';
    frameCount++; if (performance.now() - fpsStart > 1000) { el('fps').textContent = (frameCount * 1000 / (performance.now() - fpsStart)).toFixed(1); frameCount = 0; fpsStart = performance.now(); }
    for (const select of [el<HTMLSelectElement>('param-target'), el<HTMLSelectElement>('brush-target')]) { for (const option of Array.from(select.options)) if (option.value !== 'a') option.disabled = !f.b; if (!f.b) select.value = 'a'; }
    el<HTMLSelectElement>('view').value = String(f.view); if (lastSize !== f.a.size) { el<HTMLSelectElement>('grid').value = String(f.a.size); lastSize = f.a.size; } if (lastSeed !== f.a.seed) { el<HTMLInputElement>('seed').value = String(f.a.seed); lastSeed = f.a.seed; }
    for (const button of root.querySelectorAll<HTMLButtonElement>('button')) { const allowed = ['lab-export', 'lab-csv', 'lab-png', 'lab-save', 'lab-panel-toggle', 'lab-panel-close', 'lab-scan-csv'].includes(button.id) || button.dataset.command === 'cancelScan'; button.disabled = f.scanning && !allowed; }
    for (const input of root.querySelectorAll<HTMLInputElement | HTMLSelectElement>('input,select')) input.disabled = f.scanning && input.id !== 'lab-metric' && input.id !== 'lab-save-name';
    syncParams(); drawChart(); drawKernel();
  }
  const paramsContainer = el('params');
  for (const p of definition.params) {    
const label = document.createElement('label'); const row = document.createElement('span'); row.className = 'lab-param-label'; const text = document.createElement('span'); text.textContent = p.label; const numeric = document.createElement('input'); numeric.type = 'number'; numeric.min = String(p.min); numeric.max = String(p.max); numeric.step = String(p.step); numeric.value = String(p.value); numeric.dataset.param = p.key; numeric.setAttribute('aria-label', p.label); const range = document.createElement('input'); range.type = 'range'; range.min = numeric.min; range.max = numeric.max; range.step = numeric.step; range.value = numeric.value; range.dataset.param = p.key; range.setAttribute('aria-label', `${p.label} slider`); row.append(text, numeric); label.append(row, range); paramsContainer.append(label);
    for (const input of [range, numeric]) input.addEventListener('change', () => act(async () => { if (!latest) return; const target = value('param-target') as 'a' | 'b', state = target === 'a' ? latest.a : latest.b; if (!state) return; const params = { ...state.params, [p.key]: Number(input.value) }; await request('params', { target, params }); status(`${p.label} updated for ${target.toUpperCase()}.`); })); range.addEventListener('input', () => { numeric.value = range.value; });
  }
  function syncParams() { if (!latest) return; const p = (value('param-target') === 'b' ? latest.b : latest.a)?.params; if (!p) return; for (const input of paramsContainer.querySelectorAll<HTMLInputElement>('input[data-param]')) if (document.activeElement !== input) input.value = String(p[input.dataset.param!]); }
  el('param-target').addEventListener('change', () => { syncParams(); drawKernel(); });
  function drawChart() {    
if (!latest) return; const canvas = el<HTMLCanvasElement>('chart'), ctx = canvas.getContext('2d')!; const W = canvas.width, H = canvas.height, key = value('metric'), samples = latest.samples; ctx.clearRect(0, 0, W, H); ctx.font = '12px monospace'; const all = samples.flatMap(s => [s.a[key], s.b?.[key]]).filter((v): v is number => Number.isFinite(v)); let min = all.length ? Math.min(...all) : 0, max = all.length ? Math.max(...all) : 1; if (min === max) { min = Math.max(0, min - .01); max += .01; } const lo = samples[0]?.tick || 0, hi = Math.max(lo + 1, samples.at(-1)?.tick || 1); ctx.strokeStyle = '#28323e'; ctx.fillStyle = '#8091a4'; for (let j = 0; j < 3; j++) { const y = 15 + j * (H - 45) / 2; ctx.beginPath(); ctx.moveTo(64, y); ctx.lineTo(W - 12, y); ctx.stroke(); ctx.fillText(format(max - (max - min) * j / 2), 0, y + 4); } ctx.fillText(String(lo), 64, H - 6); ctx.fillText(`step ${hi}`, W - 120, H - 6);
    for (const [branch, color] of [['a', '#b2ddc7'], ['b', '#e6b775']] as const) { ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.beginPath(); let first = true; for (const s of samples) { const v = s[branch]?.[key]; if (v === undefined) { first = true; continue; } const x = 64 + (s.tick - lo) / (hi - lo) * (W - 80), y = 15 + (max - v) / (max - min) * (H - 45); if (first) { ctx.moveTo(x, y); first = false; } else ctx.lineTo(x, y); } ctx.stroke(); }
    el('metric-values').textContent = `A · ${key}: ${format(latest.metricsA[key] || 0)}${latest.metricsB ? `     B · ${key}: ${format(latest.metricsB[key] || 0)}` : ''}`;
  }
  function drawKernel() { if (model !== 'lenia' || !latest) return; const canvas = el<HTMLCanvasElement>('kernel'), ctx = canvas.getContext('2d')!, p = (value('param-target') === 'b' ? latest.b : latest.a)?.params; if (!p) return; ctx.clearRect(0, 0, 400, 130); ctx.strokeStyle = '#2a3941'; ctx.beginPath(); ctx.moveTo(0, 65); ctx.lineTo(400, 65); ctx.stroke(); for (const [color, fn] of [['#b2ddc7', (x: number) => kernelValue(x, p)], ['#e6b775', (x: number) => growthValue(x, p)]] as const) { ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.beginPath(); for (let i = 0; i < 400; i++) { const y = 65 - fn(i / 400) * 55; i ? ctx.lineTo(i, y) : ctx.moveTo(i, y); } ctx.stroke(); } }
  el('metric').addEventListener('change', drawChart);
  async function initialize(confirmChange = true) { if (confirmChange && !confirm('Create a new world? Unsaved changes and scan results will be replaced.')) return; const seed = Number(value('seed')); if (!Number.isInteger(seed) || seed < 0 || seed > 0xffffffff) throw new Error('Seed must be an integer from 0 to 4,294,967,295.'); generation++; for (const p of pending.values()) { clearTimeout(p.timer); p.reject(new Error('Experiment replaced.')); } pending.clear(); scan = undefined; el('scan-results').replaceChildren(); await request('init', { model, size: Number(value('grid')), seed, preset: Number(value('preset')) }); setModeUI('single'); status('Ready. Run the simulation, or paint a new initial condition.'); }
  el('initialize').addEventListener('click', () => act(() => initialize()));
  el('run').addEventListener('click', () => act(() => request(latest?.running ? 'pause' : 'run')));
  for (const button of root.querySelectorAll<HTMLButtonElement>('[data-command]')) button.addEventListener('click', () => act(async () => { await request(button.dataset.command!); if (button.dataset.command === 'checkpoint') status('Checkpoint captured in memory. Save or export for persistent storage.'); if (button.dataset.command === 'restoreCheckpoint') { const doc = await request('export') as Experiment; scan = doc.scan; el('scan-results').replaceChildren(); renderScan(); setModeUI(scan ? 'scan' : doc.b ? 'compare' : 'single'); status('Checkpoint restored and paused.'); } if (button.dataset.command === 'cancelScan') status('Scan stopped. Completed cells have been retained.'); }));
  function setModeUI(next: string) { mode = next; for (const b of root.querySelectorAll<HTMLButtonElement>('[data-mode]')) b.setAttribute('aria-pressed', String(b.dataset.mode === mode)); el('scan-panel').hidden = mode !== 'scan'; }
  for (const button of root.querySelectorAll<HTMLButtonElement>('[data-mode]')) button.addEventListener('click', () => act(async () => { const next = button.dataset.mode!; await request('pause'); if (next === 'compare' && !latest?.b) await request('compare'); if (next === 'single' && latest?.b) { if (!confirm('Leave A/B mode? B will be discarded. Export first if you want to keep it.')) return; await request('single'); } setModeUI(next); }));
  el('copy').addEventListener('click', () => act(async () => { if (confirm('Replace B with the complete current A state and establish a new branch point?')) await request('compare'); }));
  el('branch-reset').addEventListener('click', () => act(() => request('reset', true)));
  el('view').addEventListener('change', () => act(() => request('view', Number(value('view')))));
  el('panel-toggle').addEventListener('click', () => { const open = el('controls').classList.toggle('is-open'); el('panel-toggle').setAttribute('aria-expanded', String(open)); });
  el('panel-close').addEventListener('click', () => { el('controls').classList.remove('is-open'); el('panel-toggle').setAttribute('aria-expanded', 'false'); el('panel-toggle').focus(); });
  el('controls').addEventListener('keydown', event => { if (event.key === 'Escape') el('panel-close').click(); });

  for (const canvas of [canvasA, canvasB]) {
    let down = false, strokeReady: Promise<unknown> = Promise.resolve(), paintQueue: Promise<unknown> = Promise.resolve(), previous: { x: number; y: number } | undefined; let keyboard = { x: .5, y: .5 };
    const point = (event: PointerEvent) => { const rect = canvas.getBoundingClientRect(), side = Math.min(rect.width, rect.height); return { x: (event.clientX - rect.left - (rect.width - side) / 2) / side * canvas.width, y: (event.clientY - rect.top - (rect.height - side) / 2) / side * canvas.height }; };
    const paint = (x: number, y: number) => request('paint', { target: value('brush-target'), brush: { x, y, radius: Number(value('brush-radius')), kind: value('brush'), rotation: Number(document.getElementById('lab-rotation') ? (value('rotation')) : 0) } });
    canvas.addEventListener('pointerdown', event => { if (latest?.scanning) return; const p = point(event); if (p.x < 0 || p.y < 0 || p.x >= canvas.width || p.y >= canvas.height) return; event.preventDefault(); canvas.focus(); canvas.setPointerCapture(event.pointerId); down = true; previous = p; strokeReady = paintQueue.then(() => request('paintStart')); paintQueue = strokeReady.then(() => paint(p.x, p.y)); act(() => paintQueue); });
    canvas.addEventListener('pointermove', event => { if (!down) return; const p = point(event); p.x = Math.max(0, Math.min(canvas.width - 1, p.x)); p.y = Math.max(0, Math.min(canvas.height - 1, p.y)); const start = previous || p; previous = p; const steps = Math.min(40, Math.max(1, Math.ceil(Math.hypot(p.x - start.x, p.y - start.y) / Math.max(1, Number(value('brush-radius')) / 2)))); paintQueue = paintQueue.then(async () => { for (let i = 1; i <= steps; i++)await paint(start.x + (p.x - start.x) * i / steps, start.y + (p.y - start.y) * i / steps); }); act(() => paintQueue); });
    const end = () => { if (!down) return; down = false; previous = undefined; paintQueue = paintQueue.then(() => request('pause')); act(() => paintQueue); }; canvas.addEventListener('pointerup', end); canvas.addEventListener('pointercancel', end); canvas.addEventListener('lostpointercapture', end);
    canvas.addEventListener('keydown', event => { if ([' ', 'Enter', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)) event.preventDefault(); if (event.key === ' ') act(() => request(latest?.running ? 'pause' : 'run')); else if (event.key === 'Enter') act(async () => { await request('paintStart'); await paint(keyboard.x * canvas.width, keyboard.y * canvas.height); await request('pause'); }); else if (event.key.startsWith('Arrow')) { keyboard.x = Math.max(0, Math.min(.999, keyboard.x + (event.key === 'ArrowRight' ? .02 : event.key === 'ArrowLeft' ? -.02 : 0))); keyboard.y = Math.max(0, Math.min(.999, keyboard.y + (event.key === 'ArrowDown' ? .02 : event.key === 'ArrowUp' ? -.02 : 0))); status(`Keyboard brush: ${Math.round(keyboard.x * canvas.width)}, ${Math.round(keyboard.y * canvas.height)}. Enter paints to ${value('brush-target').toUpperCase()}.`); } });
  }
  const scanAxes = el('scan-axes');
  for (let axis = 0; axis < 2; axis++) { const row = document.createElement('div'); row.className = 'lab-scan-axis'; row.dataset.axis = String(axis); for (const [key, title] of [['key', 'Parameter'], ['min', 'From'], ['max', 'To'], ['count', 'Samples']]) { const label = document.createElement('label'); label.textContent = title; const input = key === 'key' ? document.createElement('select') : document.createElement('input'); input.id = `lab-axis-${axis}-${key}`; if (input instanceof HTMLSelectElement) { for (const p of definition.params) { const opt = document.createElement('option'); opt.value = p.key; opt.textContent = p.label; input.append(opt); } input.value = definition.axes[axis]; input.addEventListener('change', () => axisDefaults(axis)); } else { input.type = 'number'; if (key === 'count') { input.min = '2'; input.max = '5'; input.step = '1'; input.value = '3'; } } label.append(input); row.append(label); } scanAxes.append(row); axisDefaults(axis); }
  function axisDefaults(axis: number) { const p = definition.params.find(p => p.key === value(`axis-${axis}-key`))!; const spread = p.step === 1 ? 1 : (p.max - p.min) * .04; for (const key of ['min', 'max']) { const input = el<HTMLInputElement>(`axis-${axis}-${key}`); input.min = String(p.min); input.max = String(p.max); input.step = 'any'; input.value = String(Number(Math.max(p.min, Math.min(p.max, p.value + (key === 'min' ? -spread : spread))).toFixed(5))); } if (p.step === 1) { el<HTMLInputElement>(`axis-${axis}-min`).value = String(p.min); el<HTMLInputElement>(`axis-${axis}-max`).value = String(p.max); el<HTMLInputElement>(`axis-${axis}-count`).value = String(Math.min(5, p.max - p.min + 1)); } }
  el('scan-dim').addEventListener('change', () => { (scanAxes.children[1] as HTMLElement).hidden = value('scan-dim') === '1'; });
  el('scan-start').addEventListener('click', () => act(async () => { const settings: ScanSettings = { steps: Number(value('scan-steps')), axes: Array.from({ length: Number(value('scan-dim')) }, (_, i) => ({ key: value(`axis-${i}-key`), min: Number(value(`axis-${i}-min`)), max: Number(value(`axis-${i}-max`)), count: Number(value(`axis-${i}-count`)) })) }; await request('scan', settings); scan = undefined; el('scan-results').replaceChildren(); el<HTMLProgressElement>('scan-progress').value = 0; status('Scan running. Interactive controls are paused; completed cells are kept if you cancel.'); }));
  function renderScan() { if (!scan) return; const container = el('scan-results'); container.replaceChildren(); for (const [index, cell] of scan.results.entries()) { const card = document.createElement('article'); card.className = 'lab-scan-cell'; const c = document.createElement('canvas'); drawState(c, cell.state, 0); c.setAttribute('aria-label', `Scan result ${index + 1}`); const body = document.createElement('div'), params = document.createElement('p'), metrics = document.createElement('p'); params.textContent = scan.settings.axes.map(a => `${a.key} ${format(cell.params[a.key])}`).join(' · '); metrics.textContent = Object.entries(cell.metrics).slice(0, 3).map(([key, v]) => `${key}: ${format(v)}`).join(' · '); body.append(params, metrics); for (const target of ['a', 'b']) { const button = document.createElement('button'); button.textContent = target === 'a' ? 'Inspect / load A' : 'Replace B'; button.addEventListener('click', () => act(async () => { await request('loadCell', { index, target }); setModeUI(target === 'a' ? 'single' : 'compare'); status(`Loaded scan cell ${index + 1} into ${target.toUpperCase()}.`); canvasA.scrollIntoView({ block: 'center', behavior: 'auto' }); })); body.append(button); } card.append(c, body); container.append(card); } }

  function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  const csv = (rows: (string | number)[][]) => rows.map(row => row.map(v => `"${String(v).replaceAll('"', '""')}"`).join(',')).join('\r\n');
  el('export').addEventListener('click', () => act(async () => { const doc = await request('export') as Experiment; download(new Blob([encodeExperiment(doc)], { type: 'application/json' }), `${model}-${doc.a.tick}.lab.json`); status('Complete experiment exported, including retained measurements and scan results.'); }));
  el('csv').addEventListener('click', () => act(async () => { const doc = await request('export') as Experiment, keys = [...definition.metrics], rows: (string | number)[][] = [['step', 'branch', ...keys]]; for (const s of doc.samples) for (const b of ['a', 'b'] as const) if (s[b]) rows.push([s.tick, b.toUpperCase(), ...keys.map(k => s[b]![k] ?? '')]); download(new Blob([csv(rows)], { type: 'text/csv' }), `${model}-retained-metrics.csv`); }));
  el('scan-csv').addEventListener('click', () => { if (!scan) { status('Run a scan first.', true); return; } const keys = scan.settings.axes.map(a => a.key), metrics = [...definition.metrics]; download(new Blob([csv([['cell', 'seed', 'startStep', 'endStep', ...keys, ...metrics], ...scan.results.map((c, i) => [i + 1, scan!.source.seed, scan!.source.tick, c.state.tick, ...keys.map(k => c.params[k]), ...metrics.map(k => c.metrics[k])])])], { type: 'text/csv' }), `${model}-scan.csv`); });
  el('png').addEventListener('click', () => { if (!latest) return; const output = document.createElement('canvas'), n = latest.a.size; output.width = latest.b ? n * 2 : n; output.height = n; const ctx = output.getContext('2d')!; ctx.drawImage(canvasA, 0, 0); if (latest.b) ctx.drawImage(canvasB, n, 0); output.toBlob(blob => { if (blob) download(blob, `${model}-${latest!.a.tick}.png`); }, 'image/png'); });
  el('import').addEventListener('click', () => el<HTMLInputElement>('file').click());
  async function restore(doc: Experiment) { if (doc.a.model !== model) throw new Error(`This is a ${doc.a.model} experiment. Open its Lab page first.`); if (!confirm('Replace the current experiment? Unsaved changes will be lost.')) return; await request('import', doc); scan = doc.scan; el('scan-results').replaceChildren(); renderScan(); setModeUI(scan ? 'scan' : doc.b ? 'compare' : 'single'); status('Experiment restored and paused.'); }
  el<HTMLInputElement>('file').addEventListener('change', () => act(async () => { const input = el<HTMLInputElement>('file'), file = input.files?.[0]; input.value = ''; if (!file) return; if (file.size > MAX_FILE_BYTES) throw new Error('File exceeds the 64 MB limit.'); const doc = decodeExperiment(await file.text()); await restore(doc); }));
  async function refreshSaves() { const container = el('saves'); try { const records = (await listExperiments()).filter(s => s.model === model); container.replaceChildren(); for (const record of records) { const row = document.createElement('div'); row.className = 'lab-save-row'; const load = document.createElement('button'); load.textContent = record.name; load.title = `Saved ${new Date(record.updated).toLocaleString()}`; load.addEventListener('click', () => act(() => restore(record.experiment))); const remove = document.createElement('button'); remove.textContent = '×'; remove.setAttribute('aria-label', `Delete ${record.name}`); remove.addEventListener('click', () => act(async () => { if (confirm(`Delete local save “${record.name}”? This cannot be undone.`)) { await deleteExperiment(record.id); await refreshSaves(); } })); row.append(load, remove); container.append(row); } } catch (error) { container.textContent = error instanceof Error ? error.message : 'Local storage unavailable.'; } }
  el('save').addEventListener('click', () => act(async () => { const doc = await request('export') as Experiment; await saveExperiment(value('save-name'), doc); await refreshSaves(); status('Experiment saved on this device. Export a file for a portable backup.'); }));
  document.addEventListener('visibilitychange', () => { if (document.hidden && !disposed) { act(() => request('pause')); status('Paused while the tab is hidden. Resume manually.'); } });
  window.addEventListener('pagehide', () => { disposed = true; worker.terminate(); for (const p of pending.values()) { clearTimeout(p.timer); p.reject(new Error('Page closed.')); } pending.clear(); });
  window.addEventListener('pageshow', event => { if (event.persisted) location.reload(); });
  setInterval(() => { if (!latest?.running && !latest?.scanning) el('fps').textContent = '0'; }, 1500);
  act(() => initialize(false)); void refreshSaves();
}
