import {garden,decode,encode,validate,History,sow,erase,advance,pulse,inside,clamp,LIMIT,type Garden,type Species,type Pulse} from '../lib/windward/model.ts';
import {orbit,zoom,SimulationClock} from '../lib/windward/controls.ts';
import {Garden2DView,type GardenRenderer} from '../lib/windward/view-2d.ts';
const host=document.getElementById('wind-scene');if(host)setup(host);
function setup(host:HTMLElement){
  const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(`wind-${id}`) as T,field=(id:string)=>el<HTMLInputElement>(id);
  let doc=garden(),view:GardenRenderer|undefined,tool='wind',pulses:Pulse[]=[],paused=document.documentElement.dataset.motion==='reduced',dirty=false,disposed=false,loading=false,busy=false,graphicsAvailable=false,revision=0,viewGeneration=0,frame=0,last=0,stroke=false,gesture=false,lastPaint:{x:number;z:number}|undefined,lastBreeze=0,cursor={x:0,z:0},cameraChanged=false,pendingPaint:{x:number;z:number}|undefined;
  const history=new History(),clock=new SimulationClock(),abort=new AbortController(),{signal}=abort,pointers=new Map<number,{x:number;y:number}>();
  const status=(message:string,error=false)=>{el('status').textContent=message;el('status').dataset.error=String(error);};
  const act=(action:()=>void|Promise<void>)=>{try{Promise.resolve(action()).catch(error=>{if(!disposed)status(error instanceof Error?error.message:String(error),true);});}catch(error){status(error instanceof Error?error.message:String(error),true);}};
  function changed(){dirty=true;revision++;el('image-link').hidden=true;sync();}
  function sync(){for(const id of ['species','radius','direction','strength','light','name','seed','camera','pause','motion'])el<HTMLButtonElement>(id).disabled=busy;el('count').textContent=`${doc.plants.length.toLocaleString()} / 1,024 planted`;el('dirty').textContent=dirty?'Unsaved edits · export a garden file to keep them.':'No unexported edits · local copies stay on this device.';el<HTMLButtonElement>('undo').disabled=!history.undoStack.length||busy;el<HTMLButtonElement>('redo').disabled=!history.redoStack.length||busy;for(const action of ['undo','redo'])el<HTMLButtonElement>(`quick-${action}`).disabled=el<HTMLButtonElement>(action).disabled;el('pause').textContent=paused?'Grow':'Pause';el('pause').setAttribute('aria-pressed',String(paused));el<HTMLButtonElement>('step').disabled=!paused||busy;el('motion').textContent=`Motion: ${document.documentElement.dataset.motion==='reduced'?'Reduced':'Full'}`;for(const id of ['png','send','save'])el<HTMLButtonElement>(id).disabled=!view||!graphicsAvailable||loading||busy;for(const id of ['new','import','export'])el<HTMLButtonElement>(id).disabled=busy;field('quality').disabled=busy||loading;field('renderer').disabled=busy;for(const button of document.querySelectorAll<HTMLButtonElement>('[data-wind-tool]'))button.setAttribute('aria-pressed',String(button.dataset.windTool===tool));}
  function fields(){field('name').value=doc.name;field('seed').value=String(doc.seed);field('direction').value=String(doc.environment.direction);field('strength').value=String(doc.environment.strength);field('light').value=doc.environment.light;el('direction-value').textContent=`${doc.environment.direction}°`;sync();}
  function draw(force=false){view?.draw(doc,pulses,0,force);}
  function animate(now:number){frame=0;if(disposed||document.hidden||!view||!graphicsAvailable)return;const dt=last?Math.min(.1,(now-last)/1000):0;last=now;const steps=clock.steps(now,!paused&&!busy);for(let i=0;i<steps;i++)pulses=advance(doc,pulses);view.draw(doc,pulses,paused?0:dt);if(!paused&&!busy)frame=requestAnimationFrame(animate);}
  function run(){cancelAnimationFrame(frame);frame=0;last=0;clock.reset();draw();if(view&&graphicsAvailable&&!paused&&!busy&&!document.hidden&&!disposed)frame=requestAnimationFrame(animate);}
  function endStroke(){if(pendingPaint){const p=pendingPaint;pendingPaint=undefined;paint(p.x,p.z,true,true);pendingPaint=undefined;}if(stroke){stroke=false;if(history.commit(doc))changed();}if(cameraChanged){cameraChanged=false;changed();}lastPaint=undefined;}
  function resetPointers(){endStroke();pointers.clear();gesture=false;}
  function selectTool(next:string){resetPointers();tool=next;el('hint').textContent=next==='wind'?'Move across the meadow to stir the grass. Hold to leave a stronger breeze.':next==='sow'?'Draw a patch of life. Choose flowers, fine grass or feather grass in Your garden.':next==='erase'?'Brush away your planting. The original meadow stays.':'Drag to turn your little world. Scroll or pinch to move closer.';sync();}
  function panelMode(open:boolean){const modal=open&&matchMedia('(max-width: 760px)').matches;el('panel').setAttribute('role',modal?'dialog':'complementary');el('panel').setAttribute('aria-modal',String(modal));el('backdrop').hidden=!modal;host.inert=modal;}
  window.addEventListener('resize',()=>panelMode(!el('panel').hidden),{signal});
  function setPanel(open:boolean){resetPointers();panelMode(open);el('panel').hidden=!open;el('panel-toggle').setAttribute('aria-expanded',String(open));if(open)el('panel-close').focus();else el('panel-toggle').focus();}
  function paint(x:number,z:number,held=true,flush=false){if(busy||!view||!graphicsAvailable||!inside(x,z))return;document.documentElement.dataset.windEngaged='true';cursor={x,z};view.mark(x,z,Number(field('radius').value));if(tool==='wind'){const now=performance.now();if(now-lastBreeze>60){pulse(pulses,x,z,held?1.8:.7);lastBreeze=now;draw(true);}return;}if(!held||!['sow','erase'].includes(tool))return;const radius=Number(field('radius').value);pendingPaint={x,z};if(lastPaint&&(Math.hypot(x-lastPaint.x,z-lastPaint.z)===0||!flush&&Math.hypot(x-lastPaint.x,z-lastPaint.z)<radius*.35))return;if(!stroke){history.begin(doc);stroke=true;}const from=lastPaint??{x,z},steps=Math.min(128,Math.max(1,Math.ceil(Math.hypot(x-from.x,z-from.z)/(radius*.4))));for(let i=1;i<=steps;i++){const px=from.x+(x-from.x)*i/steps,pz=from.z+(z-from.z)*i/steps;if(tool==='sow')sow(doc,px,pz,radius,field('species').value as Species);else erase(doc,px,pz,radius);}lastPaint={x,z};pendingPaint=undefined;if(tool==='sow'&&doc.plants.length>=LIMIT)status('The garden holds 1,024 plants. Erase a patch to make room.');draw(true);sync();}
  host.addEventListener('pointerdown',e=>{if(busy||!view)return;host.focus();host.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>1){endStroke();gesture=true;return;}gesture=false;if(e.button===2||tool==='observe'||e.pointerType==='touch')return;const p=view.point(e.clientX,e.clientY);if(p)paint(p.x,p.z);},{signal});
  host.addEventListener('pointermove',e=>{if(busy||!view)return;const old=pointers.get(e.pointerId);if(old){if(pointers.size===2){const other=[...pointers.entries()].find(([id])=>id!==e.pointerId)![1],before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);document.documentElement.dataset.windEngaged='true';orbit(doc.camera,(e.clientX-old.x)*.5,(e.clientY-old.y)*.5);if(after>5&&before>5)zoom(doc.camera,before/after);cameraChanged=true;draw();}else if(!gesture&&(e.buttons===2||tool==='observe')){document.documentElement.dataset.windEngaged='true';orbit(doc.camera,e.clientX-old.x,e.clientY-old.y);cameraChanged=true;draw();}else if(!gesture){const p=view.point(e.clientX,e.clientY);if(p)paint(p.x,p.z);}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});}else if(e.pointerType==='mouse'){const p=view.point(e.clientX,e.clientY);if(p){cursor={x:p.x,z:p.z};view.mark(p.x,p.z,Number(field('radius').value),tool!=='observe');if(tool==='wind')paint(p.x,p.z,false);else draw();}}},{signal});
  const pointerEnd=(e:PointerEvent)=>{if(e.type==='pointerup'&&e.button===0&&pointers.has(e.pointerId)&&pointers.size===1&&!gesture&&!cameraChanged&&tool!=='observe'){const p=view?.point(e.clientX,e.clientY);if(p)paint(p.x,p.z,true,true);}pointers.delete(e.pointerId);endStroke();if(!pointers.size)gesture=false;};host.addEventListener('pointerup',pointerEnd,{signal});host.addEventListener('pointercancel',pointerEnd,{signal});host.addEventListener('lostpointercapture',pointerEnd,{signal});host.addEventListener('pointerleave',()=>{if(!pointers.size){view?.mark(cursor.x,cursor.z,1,false);draw();}},{signal});host.addEventListener('contextmenu',e=>e.preventDefault(),{signal});
  host.addEventListener('wheel',e=>{if(!view||busy)return;e.preventDefault();zoom(doc.camera,Math.exp(e.deltaY*.001));changed();draw();},{passive:false,signal});
  function undo(redo=false){resetPointers();doc=redo?history.redo(doc):history.undo(doc);pulses=[];changed();fields();draw(true);}
  host.addEventListener('keydown',e=>{if(e.target!==host||busy)return;if(['1','2','3','4'].includes(e.key)){e.preventDefault();selectTool(['wind','sow','erase','observe'][Number(e.key)-1]);}else if(e.key.startsWith('Arrow')){e.preventDefault();const n=e.shiftKey?.7:.2,x=cursor.x+(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0),z=cursor.z+(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0);if(inside(x,z))cursor={x,z};view?.mark(cursor.x,cursor.z,Number(field('radius').value));draw();}else if(e.key==='Enter'){e.preventDefault();paint(cursor.x,cursor.z);endStroke();}else if(e.key===' '){e.preventDefault();paused=!paused;sync();run();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);}},{signal});
  window.addEventListener('blur',resetPointers,{signal});document.addEventListener('visibilitychange',()=>{resetPointers();run();},{signal});
  for(const button of document.querySelectorAll<HTMLButtonElement>('[data-wind-tool]'))button.addEventListener('click',()=>selectTool(button.dataset.windTool!),{signal});
  el('panel-toggle').addEventListener('click',()=>setPanel(el('panel').hidden),{signal});el('panel-close').addEventListener('click',()=>setPanel(false),{signal});el('panel').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();setPanel(false);}},{signal});
  for(const action of ['undo','redo'])el(`quick-${action}`).addEventListener('click',()=>el<HTMLButtonElement>(action).click(),{signal});
  field('radius').addEventListener('input',()=>{view?.mark(cursor.x,cursor.z,Number(field('radius').value),tool!=='observe');draw();},{signal});
  el('backdrop').addEventListener('click',()=>setPanel(false),{signal});
  el('panel').addEventListener('keydown',e=>{if(e.key==='Tab'&&matchMedia('(max-width: 760px)').matches){const items=[...el('panel').querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled):not([type=file]),select:not(:disabled),a:not([hidden]),summary')].filter(n=>!n.hidden),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}},{signal});
  el('pause').addEventListener('click',()=>{paused=!paused;sync();run();},{signal});el('step').addEventListener('click',()=>{if(!paused||busy)return;for(let i=0;i<30;i++)pulses=advance(doc,pulses);changed();draw(true);},{signal});el('undo').addEventListener('click',()=>undo(),{signal});el('redo').addEventListener('click',()=>undo(true),{signal});
  for(const id of ['direction','strength','light']){field(id).addEventListener('input',()=>{if(busy)return;endStroke();history.begin(doc);if(id==='light')doc.environment.light=field(id).value as Garden['environment']['light'];else if(id==='direction'){doc.environment.direction=clamp(Number(field(id).value),0,360);el('direction-value').textContent=`${doc.environment.direction}°`;}else doc.environment.strength=clamp(Number(field(id).value),0,1);changed();if(paused)draw(true);},{signal});field(id).addEventListener('change',()=>{history.commit(doc);sync();if(paused)draw(true);},{signal});}
  field('name').addEventListener('change',()=>{history.begin(doc);doc.name=field('name').value.slice(0,80);history.commit(doc);changed();},{signal});
  el('camera').addEventListener('click',()=>{doc.camera={azimuth:.55,polar:1.04,distance:20};changed();draw();},{signal});
  el('motion').addEventListener('click',()=>{const reduced=document.documentElement.dataset.motion!=='reduced';document.documentElement.dataset.motion=reduced?'reduced':'full';try{localStorage.setItem('ortunate:motion',reduced?'reduced':'full');}catch{/* preference is optional */}paused=reduced;sync();run();},{signal});
  function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function canReplace(){return !dirty||confirm('Replace this garden? Save a copy or export a garden file first to keep your edits.');}
  function replace(next:Garden,saved=false){validate(next);resetPointers();doc=structuredClone(next);pulses=[];history.clear();dirty=!saved;revision++;fields();draw(true);run();status('A new little place. Make yourself at home.');}
  el('new').addEventListener('click',()=>act(()=>{const seed=Number(field('seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295)throw new Error('Use a whole seed from 0 to 4294967295.');if(canReplace())replace(garden(seed));}),{signal});
  el('export').addEventListener('click',()=>act(()=>{endStroke();download(new Blob([encode(doc)],{type:'application/json'}),`windward-${doc.seed}.windward.json`);dirty=false;sync();status('Editable garden exported. Keep this file to return to the same planting.');}),{signal});
  el('import').addEventListener('click',()=>field('file').click(),{signal});field('file').addEventListener('change',()=>act(async()=>{const file=field('file').files?.[0];field('file').value='';if(!file)return;const token=revision;if(file.size>1048576)throw new Error('Garden files are limited to 1 MiB.');const next=decode(await file.text());if(disposed||busy||token!==revision)return;if(canReplace())replace(next,true);}),{signal});
  async function exclusive(action:()=>Promise<void>){if(busy||loading)return;endStroke();busy=true;sync();run();try{await action();}finally{busy=false;if(!disposed){sync();run();}}}
  async function png(size=1600){if(!view)throw new Error('The view is unavailable. Export an editable garden file instead.');return view.snapshot(doc,size);}
  el('png').addEventListener('click',()=>act(()=>exclusive(async()=>{const blob=await png();if(disposed)return;download(blob,`windward-${doc.seed}.png`);status('1600 × 1000 PNG exported without editing overlays. Export a garden file to keep it editable.');})),{signal});
  el('send').addEventListener('click',()=>act(()=>exclusive(async()=>{el('image-link').hidden=true;const blob=await png(),{sendMedia}=await import('../lib/image/handoff.ts'),id=await sendMedia({kind:'image',blob,name:`windward-${doc.seed}.png`});if(disposed)return;el<HTMLAnchorElement>('image-link').href=`/tools/image/?transfer=${id}`;el('image-link').hidden=false;status('Snapshot prepared for five minutes. Open Image Bench in a new tab.');})),{signal});
  async function library(){const {listGardens,removeGarden}=await import('../lib/windward/storage.ts'),records=await listGardens();if(disposed)return;const container=el('library');container.replaceChildren();if(!records.length){container.textContent='No saved gardens yet. Save a new copy above.';return;}for(const record of records){const article=document.createElement('article'),title=document.createElement('h4'),image=document.createElement('img'),buttons=document.createElement('div'),open=document.createElement('button'),remove=document.createElement('button');article.className='wind-library-item';title.textContent=record.name;image.alt='Saved garden preview';image.src=record.thumbnail;image.loading='lazy';buttons.className='wind-row';open.textContent='Open';remove.textContent='Remove';open.addEventListener('click',()=>act(()=>{if(!busy&&canReplace())replace(record.garden,true);}));remove.addEventListener('click',()=>act(async()=>{if(busy||!confirm(`Remove saved copy “${record.name}”? Export a backup first; deletion cannot be undone.`))return;await removeGarden(record.id);await library();status('Saved copy removed. The current garden was not changed.');}));buttons.append(open,remove);article.append(image,title,buttons);container.append(article);}}
  el('save').addEventListener('click',()=>act(()=>exclusive(async()=>{const snapshot=structuredClone(doc),blob=await png(400),thumbnail=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Thumbnail creation failed. Export the garden file instead.'));reader.readAsDataURL(blob);}),{saveGarden}=await import('../lib/windward/storage.ts');await saveGarden(snapshot,thumbnail);if(disposed)return;dirty=false;sync();await library();status('A new copy is saved on this device. Export JSON for a portable backup.');})),{signal});
  async function loadView(force2D=false){
    const generation=++viewGeneration;loading=true;graphicsAvailable=false;cancelAnimationFrame(frame);view?.dispose();view=undefined;document.documentElement.dataset.gardenReady='false';el('placeholder').hidden=false;el('retry').hidden=true;el('loading').textContent='The grass is finding its feet…';sync();
    const quality=field('quality').value,low=quality==='low'||quality==='auto'&&(matchMedia('(pointer: coarse)').matches||innerWidth<760);
    let fallback=force2D,reason='';
    try{
      if(!force2D&&field('renderer').value!=='2d'){
        try{let timer:ReturnType<typeof setTimeout>|undefined;const module=await Promise.race([import('../lib/windward/view.ts'),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('3D module loading timed out.')),8000);})]).finally(()=>clearTimeout(timer));const {GardenView}=module;if(disposed||generation!==viewGeneration)return;
          view=new GardenView(host,doc,low?'low':'high',()=>{if(disposed||generation!==viewGeneration)return;act(()=>loadView(true));});
        }catch(error){if(disposed||generation!==viewGeneration)return;fallback=true;reason=error instanceof Error?error.message:String(error);}
      }
      if(!view){view=new Garden2DView(host,doc,low?'low':'high');document.documentElement.dataset.gardenRenderer='2d';}
      else document.documentElement.dataset.gardenRenderer='3d';
      if(disposed||generation!==viewGeneration){view.dispose();view=undefined;return;}
      graphicsAvailable=true;el('placeholder').hidden=true;document.documentElement.dataset.gardenReady='true';el('renderer-note').textContent=document.documentElement.dataset.gardenRenderer==='2d'?'2D illustration · Canvas · no WebGL required':'3D garden · WebGL';
      if(fallback){status('The 3D view could not load. Your garden is now running in 2D; planting, saving and exports still work.');el('renderer-note').title=reason;}
      else{status(document.documentElement.dataset.gardenRenderer==='2d'?'2D storybook view ready. Same garden, a lighter touch.':'Garden ready. You can switch to the lighter 2D view in Your garden.');el('renderer-note').title='';}
      run();
    }catch(error){status('The garden view could not start. Your document is safe; export it or retry after reloading.',true);el('loading').textContent=error instanceof Error?error.message:'The view could not start.';el('retry').hidden=false;}
    finally{if(generation===viewGeneration){loading=false;sync();}}
  }
  field('renderer').addEventListener('change',()=>{try{localStorage.setItem('ortunate:windward-view',field('renderer').value);}catch{}act(()=>loadView());},{signal});
  field('quality').addEventListener('change',()=>act(()=>loadView()),{signal});el('retry').addEventListener('click',()=>act(loadView),{signal});
  const resize=new ResizeObserver(()=>{view?.resize();draw();});resize.observe(host);window.addEventListener('beforeunload',event=>{endStroke();if(dirty)event.preventDefault();},{signal});window.addEventListener('pagehide',()=>{disposed=true;viewGeneration++;cancelAnimationFrame(frame);resize.disconnect();abort.abort();view?.dispose();view=undefined;});window.addEventListener('pageshow',event=>{if(event.persisted)location.reload();});
  try{const preference=localStorage.getItem('ortunate:windward-view');if(preference&&['auto','2d','3d'].includes(preference))field('renderer').value=preference;}catch{}fields();act(loadView);act(async()=>{try{await library();}catch{el('library').textContent='Local library unavailable. Export garden files to keep your work.';}});
}
