import { transformedSize,moveCrop,type ImageRecipe,type ImageSourceInfo,type Rect } from './model.ts';
import { drawRecipe,release } from './process.ts';
export class CropView {
  private context:CanvasRenderingContext2D;private image?:ImageBitmap|HTMLImageElement;private info?:ImageSourceInfo;private recipe?:ImageRecipe;private zoom=0;private offset={x:0,y:0};private width=1;private height=1;private drag?:{start:{x:number;y:number};crop:Rect;handle:string;pan:{x:number;y:number}};private abort=new AbortController();private space=false;
  canvas:HTMLCanvasElement;ratio:number|null=null;private change:(crop:Rect)=>void;
  constructor(canvas:HTMLCanvasElement,change:(crop:Rect)=>void){this.canvas=canvas;this.change=change;const c=canvas.getContext('2d');if(!c)throw new Error('Canvas unavailable. Numeric crop controls remain available.');this.context=c;const {signal}=this.abort;
    canvas.addEventListener('pointerdown',e=>{if(!this.recipe)return;canvas.focus();canvas.setPointerCapture(e.pointerId);const p=this.point(e.clientX,e.clientY),c=this.recipe.crop,t=14/this.scale();let handle='move';for(const [key,x,y]of [['nw',c.x,c.y],['ne',c.x+c.width,c.y],['sw',c.x,c.y+c.height],['se',c.x+c.width,c.y+c.height]] as [string,number,number][])if(Math.hypot(p.x-x,p.y-y)<t)handle=key;if(this.space||e.button===2)handle='pan';this.drag={start:p,crop:{...c},handle,pan:{...this.offset}};},{signal});
    canvas.addEventListener('pointermove',e=>{if(!this.drag||!this.recipe||!this.info)return;const d=this.drag,p=this.point(e.clientX,e.clientY),dx=p.x-d.start.x,dy=p.y-d.start.y,b=transformedSize(this.info,this.recipe.rotation);if(d.handle==='pan'){this.offset.x+=dx*this.scale();this.offset.y+=dy*this.scale();this.draw();return;}
      let c:Rect;if(d.handle==='move')c=moveCrop(d.crop,dx,dy,b);else{const west=d.handle.includes('w'),north=d.handle.includes('n'),anchorX=west?d.crop.x+d.crop.width:d.crop.x,anchorY=north?d.crop.y+d.crop.height:d.crop.y;let width=Math.max(1,Math.min(west?anchorX:b.width-anchorX,west?anchorX-p.x:p.x-anchorX)),height=Math.max(1,Math.min(north?anchorY:b.height-anchorY,north?anchorY-p.y:p.y-anchorY));if(this.ratio){height=Math.min(height,width/this.ratio);width=height*this.ratio;if(width<1||height<1)return;}c={x:west?anchorX-width:anchorX,y:north?anchorY-height:anchorY,width,height};}this.recipe={...this.recipe,crop:c};this.draw();},{signal});
    const end=(e:PointerEvent)=>{if(!this.drag||!this.recipe)return;const drag=this.drag;this.drag=undefined;if(e.type==='pointerup'&&drag.handle!=='pan')this.change(this.recipe.crop);else if(drag.handle!=='pan'){this.recipe.crop=drag.crop;this.draw();}};
    canvas.addEventListener('pointerup',end,{signal});canvas.addEventListener('pointercancel',end,{signal});canvas.addEventListener('lostpointercapture',end,{signal});canvas.addEventListener('contextmenu',e=>e.preventDefault(),{signal});
    canvas.addEventListener('keydown',e=>{if(e.key===' '){this.space=true;e.preventDefault();}if(!this.recipe||!this.info||!e.key.startsWith('Arrow'))return;e.preventDefault();const n=e.shiftKey?10:1;this.change(moveCrop(this.recipe.crop,e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0,e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0,transformedSize(this.info,this.recipe.rotation)));},{signal});canvas.addEventListener('keyup',e=>{if(e.key===' ')this.space=false;},{signal});canvas.addEventListener('blur',()=>{this.space=false;},{signal});canvas.addEventListener('wheel',e=>{if(document.activeElement!==canvas)return;e.preventDefault();this.setZoom(this.scale()*Math.exp(-e.deltaY*.001));},{passive:false,signal});this.resize();
  }
  setImage(image:ImageBitmap|HTMLImageElement,info:ImageSourceInfo,recipe:ImageRecipe){if(this.image)release(this.image);this.image=image;this.info=info;this.recipe=structuredClone(recipe);this.fit();}
  update(recipe:ImageRecipe){this.drag=undefined;this.recipe=structuredClone(recipe);this.draw();}
  private scale(){if(this.zoom)return this.zoom;if(!this.info||!this.recipe)return 1;const s=transformedSize(this.info,this.recipe.rotation);return Math.min((this.width-30)/s.width,(this.height-30)/s.height);}
  private origin(){const s=this.info&&this.recipe?transformedSize(this.info,this.recipe.rotation):{width:1,height:1},scale=this.scale();return{x:(this.width-s.width*scale)/2+this.offset.x,y:(this.height-s.height*scale)/2+this.offset.y};}
  private point(x:number,y:number){const r=this.canvas.getBoundingClientRect(),o=this.origin(),s=this.scale();return{x:(x-r.left-o.x)/s,y:(y-r.top-o.y)/s};}
  fit(){this.zoom=0;this.offset={x:0,y:0};this.draw();}
  setZoom(value:number){this.zoom=Math.max(.01,Math.min(8,value));this.draw();}
  zoomBy(factor:number){this.setZoom(this.scale()*factor);}
  resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);this.width=Math.max(40,r.width);this.height=Math.max(40,r.height);this.canvas.width=Math.round(this.width*d);this.canvas.height=Math.round(this.height*d);this.context.setTransform(d,0,0,d,0,0);this.draw();}
  draw(){const c=this.context;c.clearRect(0,0,this.width,this.height);c.fillStyle='#131b21';c.fillRect(0,0,this.width,this.height);if(!this.image||!this.info||!this.recipe)return;const r=this.recipe,b=transformedSize(this.info,r.rotation),s=this.scale(),o=this.origin();c.save();c.translate(o.x,o.y);drawRecipe(c,this.image,this.info,{...r,format:'image/png',crop:{x:0,y:0,...b}},b.width*s,b.height*s);const x=r.crop.x*s,y=r.crop.y*s,w=r.crop.width*s,h=r.crop.height*s;c.fillStyle='#0009';c.fillRect(0,0,b.width*s,y);c.fillRect(0,y+h,b.width*s,b.height*s-y-h);c.fillRect(0,y,x,h);c.fillRect(x+w,y,b.width*s-x-w,h);c.strokeStyle='#e6cf9d';c.lineWidth=1.5;c.strokeRect(x,y,w,h);c.strokeStyle='#fff5';c.lineWidth=.5;for(let i=1;i<3;i++){c.beginPath();c.moveTo(x+w*i/3,y);c.lineTo(x+w*i/3,y+h);c.moveTo(x,y+h*i/3);c.lineTo(x+w,y+h*i/3);c.stroke();}c.fillStyle='#ead9b8';for(const [px,py]of [[x,y],[x+w,y],[x,y+h],[x+w,y+h]])c.fillRect(px-4,py-4,8,8);c.restore();}
  clear(){if(this.image)release(this.image);this.image=undefined;this.info=undefined;this.recipe=undefined;this.drag=undefined;this.draw();}
  dispose(){this.abort.abort();this.clear();}
}
