import { FILE_LIMIT } from './model.ts';
import { validatePalette,type PaletteDocument } from './palette.ts';
export type Payload={kind:'image';blob:Blob;name:string}|{kind:'palette';palette:PaletteDocument};
export interface Transfer {id:string;createdAt:number;payload:Payload}
export function validTransfer(value:unknown,now=Date.now()):value is Transfer {const r=value as Transfer;if(!r||typeof r.id!=='string'||!Number.isFinite(r.createdAt)||r.createdAt>now||now-r.createdAt>300000||!r.payload)return false;try{if(r.payload.kind==='palette'){validatePalette(r.payload.palette);return true;}return r.payload.kind==='image'&&r.payload.blob instanceof Blob&&r.payload.blob.size<=FILE_LIMIT&&typeof r.payload.name==='string'&&r.payload.name.length<=160;}catch{return false;}}
function open():Promise<IDBDatabase>{if(typeof indexedDB==='undefined')return Promise.reject(new Error('Temporary storage unavailable. Download and import the file instead.'));return new Promise((resolve,reject)=>{const r=indexedDB.open('ortunate-media-transfer',1);r.onupgradeneeded=()=>r.result.createObjectStore('transfers',{keyPath:'id'});r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=r.onblocked=()=>reject(new Error('Temporary storage unavailable. Download and import the file instead.'));});}
async function transact<T>(action:(store:IDBObjectStore,done:(value:T)=>void)=>void):Promise<T>{const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('transfers','readwrite'),store=tx.objectStore('transfers');let value:T;const cursor=store.openCursor();cursor.onsuccess=()=>{const c=cursor.result;if(c){if(!validTransfer(c.value))c.delete();c.continue();}else action(store,v=>{value=v;});};tx.oncomplete=()=>{db.close();resolve(value);};tx.onerror=tx.onabort=()=>{db.close();reject(new Error('Temporary transfer failed. Export and import manually.'));};});}
export async function sendMedia(payload:Payload){const record:Transfer={id:crypto.randomUUID(),createdAt:Date.now(),payload};if(!validTransfer(record))throw new Error('Invalid transfer.');await transact<void>((s,done)=>{s.put(record).onsuccess=()=>done();});return record.id;}
export async function receiveMedia(id:string,kind:Payload['kind']){if(!/^[a-f0-9-]{36}$/.test(id))throw new Error('Invalid transfer link.');return transact<Payload|undefined>((s,done)=>{const r=s.get(id);r.onsuccess=()=>{const record=r.result as Transfer|undefined;if(!validTransfer(record)||record.payload.kind!==kind){done(undefined);return;}s.delete(id);done(record.payload);};}).then(value=>{if(!value)throw new Error('Transfer expired, already used, or intended for another tool. Import the file manually.');return value;});}
