import { orientedSize,transformedSize,outputSize,validateRecipe,type ImageSourceInfo,type ImageRecipe,type ImageJobResult,type ImageFormat } from './model.ts';
import { inspectImage } from './inspect.ts';
import { chooseEncoding } from './encode.ts';
import { extractPalette } from './palette.ts';
type Surface=HTMLCanvasElement|OffscreenCanvas;
export function surface(width:number,height:number):Surface{if(typeof OffscreenCanvas!=='undefined')return new OffscreenCanvas(width,height);const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;return canvas;}
export function blobOf(canvas:Surface,format:ImageFormat,quality=.85):Promise<Blob>{if('convertToBlob'in canvas)return canvas.convertToBlob({type:format,quality});return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Image encoding failed. Try smaller dimensions.')),format,quality));}
export async function decode(blob:Blob){if(typeof createImageBitmap!=='undefined')return createImageBitmap(blob,{imageOrientation:'from-image',colorSpaceConversion:'default'});if(typeof document==='undefined')throw new Error('Image decoding requires the main-thread fallback.');const url=URL.createObjectURL(blob),image=new Image();try{image.src=url;await image.decode();return image;}finally{URL.revokeObjectURL(url);}}
export function release(image:ImageBitmap|HTMLImageElement){if('close'in image)image.close();}
export function drawRecipe(context:CanvasRenderingContext2D|OffscreenCanvasRenderingContext2D,image:CanvasImageSource,info:ImageSourceInfo,recipe:ImageRecipe,width:number,height:number){
  const original=orientedSize(info),size=transformedSize(info,recipe.rotation),crop=recipe.crop;context.save();context.clearRect(0,0,width,height);if(recipe.format==='image/jpeg'){context.fillStyle=recipe.background;context.fillRect(0,0,width,height);}context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.scale(width/crop.width,height/crop.height);context.translate(-crop.x,-crop.y);context.translate(size.width/2,size.height/2);context.scale(recipe.flipX?-1:1,recipe.flipY?-1:1);context.rotate(recipe.rotation*Math.PI/2);context.drawImage(image,-original.width/2,-original.height/2,original.width,original.height);context.restore();
}
export async function processImage(blob:Blob,recipe:ImageRecipe,before=false,check=()=>{}):Promise<ImageJobResult>{
  const info=await inspectImage(blob);validateRecipe(recipe,info);check();const image=await decode(blob),out=outputSize(recipe);let canvas:Surface|undefined;
  try{check();canvas=surface(out.width,out.height);const size=orientedSize(info);if(image.width!==size.width||image.height!==size.height)throw new Error('This browser decoded a different orientation. Convert the image to PNG before retrying.');const context=canvas.getContext('2d') as CanvasRenderingContext2D|OffscreenCanvasRenderingContext2D|null;if(!context)throw new Error('Canvas is unavailable.');drawRecipe(context,image,info,recipe,out.width,out.height);const result=await chooseEncoding(q=>blobOf(canvas!,recipe.format,q),recipe.format,recipe.mode,recipe.quality,recipe.targetBytes,check);check();const original=before?await blobOf(canvas,'image/png'):undefined;check();return{...result,...out,before:original};}finally{release(image);if(canvas)canvas.width=canvas.height=1;}
}
export async function imagePalette(blob:Blob,count:number,check=()=>{}){const image=await decode(blob);let canvas:Surface|undefined;try{check();const scale=Math.min(1,256/image.width,256/image.height);canvas=surface(Math.max(1,Math.round(image.width*scale)),Math.max(1,Math.round(image.height*scale)));const c=canvas.getContext('2d') as CanvasRenderingContext2D|OffscreenCanvasRenderingContext2D|null;if(!c)throw new Error('Canvas is unavailable.');c.drawImage(image,0,0,canvas.width,canvas.height);return extractPalette(c.getImageData(0,0,canvas.width,canvas.height).data,count);}finally{release(image);if(canvas)canvas.width=canvas.height=1;}}
export async function supportedFormats(){const canvas=surface(1,1),supported:ImageFormat[]=[];for(const format of ['image/png','image/jpeg','image/webp'] as ImageFormat[])try{if((await blobOf(canvas,format)).type===format)supported.push(format);}catch{/* unsupported encoder */}return supported;}
