import {test} from 'node:test';
import assert from 'node:assert/strict';
import {moveBoard,canMove,validBoard,validChain,mergeChain,canLink,adjacent} from '../src/lib/game2048.ts';
import {createMines,revealMines,neighbors,newPuzzle,slidePuzzle,solvedPuzzle,stepLife,rotatePiece,pieceFits,lockPiece,clearLines,tetrominoes,snakeStep,snakeObstacles,circleRect} from '../src/lib/arcade-rules.ts';
import {encodeBase64,decodeBase64,parseTimestamp,parseColor,colorFormats,makePassword,passwordSets,drawItems,convertUnit,randomInt} from '../src/lib/utilities.ts';
import {games,utilities,visuals} from '../src/data/catalog.ts';
import {advanceWarp,newWarpMotion} from '../src/lib/motion.ts';
test('warp acceleration and release keep position continuous even after a long run',()=>{
 let state={...newWarpMotion(),phase:1000};
 const accelerated=advanceWarp(state,1/60,true,1,1);
 assert.ok(accelerated.phase>state.phase&&accelerated.phase-state.phase<.01);
 assert.ok(accelerated.speed>.12&&accelerated.speed<.64);
 assert.ok(accelerated.x>.5&&accelerated.x<1);
 state=accelerated;for(let i=0;i<120;i++)state=advanceWarp(state,1/60,true,1,1);
 const released=advanceWarp(state,1/60,false,.5,.5);
 assert.ok(released.phase>state.phase&&released.phase-state.phase<.02);
 assert.ok(released.speed<state.speed&&released.speed>.12);
 assert.deepEqual(advanceWarp(state,0,false,0,0),state);
});
test('warp integration is independent of frame rate',()=>{
 let fast=newWarpMotion(),slow=newWarpMotion();
 for(let i=0;i<60;i++)fast=advanceWarp(fast,1/60,true,.8,.2);
 for(let i=0;i<30;i++)slow=advanceWarp(slow,1/30,true,.8,.2);
 assert.ok(Math.abs(fast.phase-slow.phase)<1e-10);
 assert.ok(Math.abs(fast.speed-slow.speed)<1e-10);
});
test('catalog contains 8 games, 10 tools, and 12 distinct studies with real variants',()=>{assert.equal(games.length,8);assert.equal(utilities.length,10);assert.equal(visuals.length,12);for(const group of [games,utilities,visuals])assert.equal(new Set(group.map(e=>e.slug)).size,group.length);assert.ok(games.every(g=>g.modes.length>=2));assert.ok(visuals.every(g=>g.modes.length>=2));});
test('5x5 slides and end detection use actual board dimensions',()=>{const b=Array(25).fill(0);b[0]=2;b[20]=2;const moved=moveBoard(b,'down',5);assert.equal(moved.board[20],4);assert.equal(moved.score,4);assert.equal(validBoard(moved.board,5),true);assert.equal(validBoard(moved.board),false);assert.equal(canMove(b,5),true);const full=Array.from({length:25},(_,i)=>(Math.floor(i/5)+i%5)%2?2:4);assert.equal(canMove(full,5),false);});
test('same-number links accept diagonals and reject repeats, gaps and mixed values',()=>{const b=Array(25).fill(2);assert.equal(validChain(b,[0,6,12],'same'),true);assert.equal(validChain(b,[0,1,0],'same'),false);assert.equal(validChain(b,[0,3],'same'),false);b[1]=4;assert.equal(validChain(b,[0,1],'same'),false);assert.equal(adjacent(4,5,5,true),false);});
test('same-number merge rounds the sum up and drops/refills without mutation',()=>{const b=Array(25).fill(2),merged=mergeChain(b,[0,1,2],'same',5,()=>0)!;assert.equal(merged.score,8);assert.equal(merged.board[2],8);assert.equal(merged.board.length,25);assert.ok(merged.board.every(Boolean));assert.equal(b[2],2);assert.equal(mergeChain(b,[0],'same'),null);});
test('doubling chains require the running sum at each step',()=>{const b=Array(25).fill(2);b[2]=4;b[3]=8;b[4]=16;assert.equal(validChain(b,[0,1,2,3,4],'doubling'),true);assert.equal(mergeChain(b,[0,1,2,3,4],'doubling',5,()=>0)!.score,32);assert.equal(validChain(b,[0,1,6],'doubling'),false);assert.equal(canLink(Array.from({length:25},(_,i)=>2**(i+1))),false);assert.equal(canLink(b),true);});
test('snake wraps, ignores reversals and collides with variant obstacles',()=>{const base={body:[19,18,17],direction:1,food:50,score:0,over:false};assert.equal(snakeStep(base,1,0).over,true);assert.equal(snakeStep(base,1,1).body[0],0);assert.equal(snakeStep({...base,body:[10,9]},3,0).direction,1);assert.equal(snakeStep({...base,body:[snakeObstacles[0]-1],direction:1},1,2).over,true);});
test('tetris rotation, wall collision, locking and simultaneous line clears',()=>{assert.deepEqual(rotatePiece([[1,1,1,1]]),[[1],[1],[1],[1]]);const empty=Array(200).fill(0);assert.equal(pieceFits(empty,tetrominoes[0],7,0),false);assert.equal(pieceFits(empty,tetrominoes[1],0,19),false);const b=lockPiece(empty,tetrominoes[1],0,18,2);assert.equal(b[180],2);assert.equal(b[191],2);const full=[...Array(180).fill(0),...Array(20).fill(1)];const cleared=clearLines(full);assert.equal(cleared.lines,2);assert.equal(cleared.board.length,200);assert.ok(cleared.board.every(v=>v===0));});
test('breakout circle collision catches edges and misses distant bricks',()=>{assert.equal(circleRect(5,5,2,6,3,10,10),true);assert.equal(circleRect(0,0,2,6,3,10,10),false);});
test('all mine difficulties protect first reveal and its neighborhood',()=>{for(const [w,h,n]of [[9,9,10],[16,16,40],[30,16,99]]){const first=Math.floor(w*h/2);const b=createMines(w,h,n,first);assert.equal(b.filter(v=>v===-1).length,n);for(const i of [first,...neighbors(first,w,h)])assert.notEqual(b[i],-1);assert.equal(b[first],0);const flags=Array(w*h).fill(false);flags[first+1]=true;const r=revealMines(b,Array(w*h).fill(false),flags,first,w,h);assert.equal(r[first],true);assert.equal(r[first+1],false);assert.ok(r.every((v,i)=>!v||b[i]>=0));}});
test('puzzle shuffles preserve solvability and illegal moves are unchanged',()=>{for(const size of [3,4])for(let repeat=0;repeat<20;repeat++){const b=newPuzzle(size);assert.equal(solvedPuzzle(b),false);assert.equal(new Set(b).size,size*size);const numbers=b.filter(Boolean);let inversions=0;for(let i=0;i<numbers.length;i++)for(let j=i+1;j<numbers.length;j++)if(numbers[i]>numbers[j])inversions++;assert.equal(size%2?inversions%2:(inversions+size-Math.floor(b.indexOf(0)/size))%2,size%2?0:1);assert.equal(slidePuzzle(b,-1,size),b);}});
test('life blinker oscillates and wrapped edges create neighbors',()=>{const b=Array(25).fill(0);[11,12,13].forEach(i=>b[i]=1);const next=stepLife(b,5,5,false);assert.deepEqual(next.flatMap((v,i)=>v?[i]:[]),[7,12,17]);assert.deepEqual(stepLife(next,5,5,false),b);const corners=Array(25).fill(0);[0,4,20].forEach(i=>corners[i]=1);assert.equal(stepLife(corners,5,5,true)[24],1);assert.equal(stepLife(corners,5,5,false)[24],0);});
test('Unicode Base64 roundtrips and malformed encodings fail',()=>{const text='Hello, 宇宙 🌌\n\u0000';assert.equal(decodeBase64(encodeBase64(text)),text);assert.throws(()=>decodeBase64('!invalid'));assert.throws(()=>decodeBase64('/w=='));assert.equal(decodeBase64(''), '');});
test('timestamp unit conversion and invalid range handling',()=>{assert.equal(parseTimestamp('1750000000','seconds').getTime(),parseTimestamp('1750000000000','milliseconds').getTime());assert.equal(parseTimestamp('0','seconds').toISOString(),'1970-01-01T00:00:00.000Z');assert.throws(()=>parseTimestamp('','seconds'));assert.throws(()=>parseTimestamp('1e30','seconds'));});
test('color formats agree across HEX RGB HSL and validate bounds',()=>{assert.deepEqual(parseColor('#f00'),[255,0,0]);assert.deepEqual(parseColor('hsl(120, 100%, 50%)'),[0,255,0]);assert.equal(colorFormats(parseColor('rgb(0, 0, 255)')).hex,'#0000ff');assert.throws(()=>parseColor('rgb(256,0,0)'));assert.throws(()=>parseColor('hsl(0, 150%, 50%)'));});
test('temperature and physical conversion handles exact reference points',()=>{assert.equal(convertUnit(32,'Temperature','°F','°C'),0);assert.equal(convertUnit(0,'Temperature','°C','K'),273.15);assert.ok(Math.abs(convertUnit(1,'Length','mi','km')-1.609344)<1e-10);assert.throws(()=>convertUnit(-1,'Temperature','K','°C'));assert.throws(()=>convertUnit(NaN,'Mass','kg','lb'));});
test('password generation includes every selected set and respects bounds',()=>{const groups=Object.values(passwordSets);for(let i=0;i<20;i++){const p=makePassword(24,groups);assert.equal(p.length,24);assert.ok([...p].every(c=>groups.join('').includes(c)));for(const group of groups)assert.ok([...p].some(c=>group.includes(c)));}assert.throws(()=>makePassword(3,groups));assert.throws(()=>makePassword(20,[]));});
test('random draw deduplicates candidates and rejects impossible requests',()=>{assert.deepEqual(drawItems(['a','a','b'],2,true,()=>0),['a','b']);assert.deepEqual(drawItems(['a'],3,false,()=>0),['a','a','a']);assert.throws(()=>drawItems(['a','a'],2,true));assert.throws(()=>drawItems([],1,true));});
test('secure random integer rejects biased tail values',()=>{let calls=0;const n=randomInt(10,a=>{a[0]=calls++===0?4294967295:17;return a;});assert.equal(n,7);assert.equal(calls,2);});
