import test from 'node:test';
import assert from 'node:assert/strict';
import { inspectBytes } from '../src/lib/image/inspect.ts';
import { defaultRecipe,ImageEditor,orientedSize,transformedSize,resetTransform,outputSize,fitCrop,moveCrop,validateRecipe,outputName,type ImageSourceInfo } from '../src/lib/image/model.ts';
import { chooseEncoding } from '../src/lib/image/encode.ts';
import { extractPalette,contrast,paletteDocument,decodePalette,paletteCSS } from '../src/lib/image/palette.ts';
import { validTransfer,sendMedia,receiveMedia } from '../src/lib/image/handoff.ts';
import { zipResults } from '../src/lib/image/zip.ts';
import { unzipSync } from 'fflate';
import { drawRecipe } from '../src/lib/image/process.ts';
import { ImageProcessor } from '../src/lib/image/client.ts';

const info:ImageSourceInfo={format:'image/png',width:1200,height:800,orientation:1,bytes:100};
const join=(...arrays:Uint8Array[])=>new Uint8Array(Buffer.concat(arrays));
const chunk=(kind:string,data:Uint8Array)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(kind,4);b.set(data,8);return b;};
function png(width=1200,height=800,extra:Uint8Array[]=[]) {const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;return join(new Uint8Array([137,80,78,71,13,10,26,10]),chunk('IHDR',header),...extra,chunk('IEND',new Uint8Array()));}
function tiff(orientation:number){const b=Buffer.alloc(26);b.write('II');b.writeUInt16LE(42,2);b.writeUInt32LE(8,4);b.writeUInt16LE(1,8);b.writeUInt16LE(0x112,10);b.writeUInt16LE(3,12);b.writeUInt32LE(1,14);b.writeUInt16LE(orientation,18);return b;}
function jpeg(orientation:number){const segment=(marker:number,data:Uint8Array)=>{const b=Buffer.alloc(data.length+4);b[0]=255;b[1]=marker;b.writeUInt16BE(data.length+2,2);b.set(data,4);return b;};return join(new Uint8Array([255,216]),segment(0xe1,join(Buffer.from('Exif\0\0'),tiff(orientation))),segment(0xe1,Buffer.from('XMP unrelated metadata')),segment(0xc0,new Uint8Array([8,3,32,4,176,3])),new Uint8Array([255,217]));}
function webp(animated=false){const b=Buffer.alloc(30);b.write('RIFF');b.writeUInt32LE(22,4);b.write('WEBPVP8X',8);b.writeUInt32LE(10,16);b[20]=animated?2:0;b[24]=99;b[27]=49;return b;}

test('image headers sniff actual bytes and honor EXIF without XMP overriding it',()=>{assert.equal(inspectBytes(png()).width,1200);assert.equal(inspectBytes(webp()).height,50);for(let orientation=1;orientation<=8;orientation++){const result=inspectBytes(jpeg(orientation));assert.equal(result.orientation,orientation);assert.deepEqual(orientedSize(result),orientation>=5?{width:800,height:1200}:{width:1200,height:800});}assert.equal(inspectBytes(png(1200,800,[chunk('eXIf',tiff(6))])).orientation,6);});
test('image headers reject animations, oversized dimensions and truncation',()=>{assert.throws(()=>inspectBytes(png(1,1,[chunk('acTL',new Uint8Array(8))])),/Animated/);assert.throws(()=>inspectBytes(webp(true)),/Animated/);assert.throws(()=>inspectBytes(png(6000,6000)),/24 million/);assert.throws(()=>inspectBytes(png().slice(0,25)),/Truncated/);for(const text of ['GIF89a','<svg/>','heic'])assert.throws(()=>inspectBytes(Buffer.from(text)),/static/);});
test('recipe resize is aspect preserving and prevents enlargement by default',()=>{const r=defaultRecipe(info);r.maxWidth=600;r.maxHeight=600;assert.deepEqual(outputSize(r),{width:600,height:400});r.maxWidth=r.maxHeight=2400;assert.deepEqual(outputSize(r),{width:1200,height:800});r.allowUpscale=true;assert.deepEqual(outputSize(r),{width:2400,height:1600});r.maxWidth=r.maxHeight=8192;assert.throws(()=>validateRecipe(r,info),/16 million/);});
test('crop transforms reset atomically and undo restores crop and orientation',()=>{const e=new ImageEditor(info);e.commit({...e.recipe,crop:fitCrop(info,1)});const prior=structuredClone(e.recipe);e.commit(resetTransform(e.recipe,info,{rotation:1,flipX:true}));assert.deepEqual(e.recipe.crop,{x:0,y:0,width:800,height:1200});e.undo();assert.deepEqual(e.recipe,prior);e.redo();assert.equal(e.recipe.flipX,true);assert.deepEqual(transformedSize({...info,orientation:6},1),{width:1200,height:800});});
test('history is capped, bad crops are rejected without mutation, movement clamps',()=>{const e=new ImageEditor(info);for(let i=0;i<60;i++)e.commit({...e.recipe,maxWidth:600+i});assert.equal(e.undoStack.length,50);const prior=structuredClone(e.recipe);assert.throws(()=>e.commit({...e.recipe,crop:{x:-1,y:0,width:20,height:20}}));assert.deepEqual(e.recipe,prior);assert.deepEqual(moveCrop({x:20,y:20,width:100,height:100},9999,-9999,info),{x:1100,y:0,width:100,height:100});});
test('draw recipe uses same geometry and JPEG matte before transformed source',()=>{const calls:any[]=[];const c=new Proxy({}, {get:(_,key)=>(...args:any[])=>calls.push([key,...args]),set:()=>true});const r={...defaultRecipe(info),format:'image/jpeg' as const,rotation:1 as const,crop:{x:10,y:20,width:100,height:200}};drawRecipe(c as any,{} as any,info,r,50,100);assert.ok(calls.findIndex(c=>c[0]==='fillRect')<calls.findIndex(c=>c[0]==='drawImage'));assert.deepEqual(calls.find(c=>c[0]==='rotate'),['rotate',Math.PI/2]);assert.deepEqual(calls.filter(c=>c[0]==='scale')[0],['scale',.5,.5]);assert.equal(calls.at(-1)[0],'restore');});
const encoded=(size:number,type='image/jpeg')=>new Blob([new Uint8Array(size)],{type});
test('target encoding performs at most eight attempts and chooses highest measured fitting quality',async()=>{const tried:{q:number;size:number}[]=[];const result=await chooseEncoding(async q=>{const size=Math.round(q*10000);tried.push({q,size});return encoded(size);},'image/jpeg','target',.85,5000);assert.equal(result.attempts,8);assert.equal(result.quality,Math.max(...tried.filter(t=>t.size<=5000).map(t=>t.q)));assert.ok(result.metTarget);});
test('unreachable target returns smallest actual attempt without changing dimensions',async()=>{let n=0;const sizes=[1000,900,950,600,800,750,700,650];const result=await chooseEncoding(async()=>encoded(sizes[n++]),'image/jpeg','target',.85,100);assert.equal(result.blob.size,600);assert.equal(result.metTarget,false);assert.equal(n,8);});
test('PNG has no quality search and encoding detects MIME substitution and cancellation',async()=>{const result=await chooseEncoding(async()=>encoded(500,'image/png'),'image/png','target',.85,1);assert.equal(result.attempts,1);assert.equal(result.quality,null);await assert.rejects(chooseEncoding(async()=>encoded(10,'image/png'),'image/webp','quality',.85,100),/cannot encode/);let checks=0;await assert.rejects(chooseEncoding(async()=>encoded(10),'image/jpeg','quality',.85,100,()=>{if(++checks===2)throw new Error('cancelled');}),/cancelled/);});
test('palette extraction is deterministic, alpha weighted and ignores invisible pixels',()=>{const pixels=new Uint8ClampedArray([255,0,0,255,0,0,255,128,0,255,0,0,0,255,0,25]);const p=extractPalette(pixels,8);assert.equal(p.length,2);assert.equal(p[0].hex,'#ff0000');assert.ok(Math.abs(p[0].share-255/383)<1e-10);assert.deepEqual(extractPalette(pixels,8),p);assert.deepEqual(extractPalette(new Uint8ClampedArray(4),3),[]);assert.throws(()=>extractPalette(pixels,9));});
test('palette files validate version, limits and CSS safety; contrast uses unrounded ratios',()=>{const p=paletteDocument(['#f00','rgb(0,0,255)']);assert.deepEqual(decodePalette(JSON.stringify(p)),p);assert.match(paletteCSS(p),/--swatch-1: #ff0000/);assert.throws(()=>decodePalette(' '.repeat(16385)),/16 KB/);assert.throws(()=>paletteDocument(Array(9).fill('#fff')));assert.throws(()=>decodePalette(JSON.stringify({...p,version:2})));assert.equal(contrast('#000','#fff'),21);assert.equal(contrast('#fff','#fff'),1);assert.ok(contrast('#777','#fff')<4.5);assert.ok(contrast('#767676','#fff')>4.5);});
test('output names are unique, safe, and use actual encoding extension; ZIP round trips completed blobs',async()=>{const used=new Set<string>();const a=outputName('../A.png','image/jpeg',used),b=outputName('../a.png','image/jpeg',used);assert.ok(!/[\\/]/.test(a));assert.notEqual(a.toLowerCase(),b.toLowerCase());assert.match(b,/-2.jpg$/);const archive=await zipResults([{name:a,blob:new Blob(['one'])},{name:b,blob:new Blob(['two'])}]);const entries=unzipSync(new Uint8Array(await archive.arrayBuffer()));assert.equal(new TextDecoder().decode(entries[a]),'one');await assert.rejects(zipResults([{name:'../bad',blob:new Blob()}]),/Invalid/);await assert.rejects(zipResults([]),/No completed/);await assert.rejects(zipResults([{name:'a.png',blob:new Blob(['x'])}],()=>{throw new Error('cancel');}),/cancel/);});
test('temporary handoff expires in five minutes and unavailable storage has manual fallback',async()=>{const now=1000000,payload={kind:'palette' as const,palette:paletteDocument(['#fff'])};assert.ok(validTransfer({id:'x',createdAt:now-300000,payload},now));assert.equal(validTransfer({id:'x',createdAt:now-300001,payload},now),false);assert.equal(validTransfer({id:'x',createdAt:now+1,payload},now),false);await assert.rejects(sendMedia(payload),/Download and import/);await assert.rejects(receiveMedia('bad','image'),/Invalid/);});

test('image worker cancellation rejects old work and ignores late messages',async()=>{
  const saved=['Worker','OffscreenCanvas','createImageBitmap'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)] as const),workers:any[]=[];
  class WorkerAdapter {onmessage:any;onerror:any;message:any;terminated=false;constructor(){workers.push(this);}postMessage(message:any){this.message=message;}terminate(){this.terminated=true;}}
  try{Object.assign(globalThis,{Worker:WorkerAdapter,OffscreenCanvas:class{},createImageBitmap:()=>{}});const p=new ImageProcessor(),first=p.formats(),rejected=assert.rejects(first,/cancelled/),second=p.formats();workers[0].onmessage({data:{id:workers[0].message.id,result:['stale']}});workers[1].onmessage({data:{id:workers[1].message.id,result:['image/png']}});await rejected;assert.deepEqual(await second,['image/png']);assert.ok(workers.every(w=>w.terminated));p.cancel();}finally{for(const [key,descriptor]of saved)if(descriptor)Object.defineProperty(globalThis,key,descriptor);else Reflect.deleteProperty(globalThis,key);}
});
test('worker construction failure falls back and MIME capability probing checks actual output',async()=>{
  const saved=['Worker','OffscreenCanvas','createImageBitmap'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)] as const);
  class CanvasAdapter {async convertToBlob(options:any){return new Blob(['encoded'],{type:options.type==='image/webp'?'image/png':options.type});}}
  try{Object.assign(globalThis,{Worker:class{constructor(){throw new Error('Worker blocked');}},OffscreenCanvas:CanvasAdapter,createImageBitmap:()=>{}});assert.deepEqual(await new ImageProcessor().formats(),['image/png','image/jpeg']);}finally{for(const [key,descriptor]of saved)if(descriptor)Object.defineProperty(globalThis,key,descriptor);else Reflect.deleteProperty(globalThis,key);}
});
