import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import * as model from '../src/lib/image/model.ts';
import * as palette from '../src/lib/image/palette.ts';
import * as utilities from '../src/lib/utilities.ts';

// Event-level adapters only: no browser automation or simulated codec claims.
function harness(kind:'image'|'color'){
  class Element extends EventTarget {
    dataset:Record<string,string>={};children:Element[]=[];style:any={};hidden=false;disabled=false;checked=false;value='';textContent='';className='';files:any[]=[];options:any[]=[];attributes:Record<string,string>={};
    append(...children:Element[]){this.children.push(...children);}replaceChildren(...children:Element[]){this.children=children;}setAttribute(k:string,v:string){this.attributes[k]=v;}removeAttribute(k:string){delete this.attributes[k];}click(){if(!this.disabled)this.dispatchEvent(new Event('click'));}matches(){return false;}
    querySelectorAll(selector:string){return this.children.filter(e=>selector==='[data-image-mode]'?!!e.dataset.imageMode:selector==='[data-color-copy]'?!!e.dataset.colorCopy:false);}
  }
  const root=new Element(),ids=new Map<string,Element>([[kind==='image'?'image-bench':'color-workshop',root]]),blobs:Blob[]=[],jobs:{resolve:(v:any)=>void;reject:(e:Error)=>void}[]=[],timers=new Map<number,()=>void>();let seq=0;
  const markup=readFileSync(new URL(`../src/pages/tools/${kind}.astro`,import.meta.url),'utf8');
  for(const [,id]of markup.matchAll(/id="((?:image|color)-[^"]+)"/g)){if(ids.has(id))continue;const e=new Element();ids.set(id,e);root.append(e);}
  const el=(id:string)=>ids.get(`${kind}-${id}`)!;
  if(kind==='image')for(const key of ['x','y','width','height'])ids.set(`image-crop-${key}`,new Element());
  const defaults=kind==='image'?{'max-width':'1600','max-height':'1600',format:'image/png',compression:'quality',quality:'85',target:'250',background:'#ffffff',ratio:'free','color-count':'5'}:{a:'#ad99e5',b:'#c6eaa5',angle:'135',foreground:'#000000',background:'#ffffff'};
  for(const [id,value]of Object.entries(defaults))el(id).value=value;
  for(const value of kind==='image'?['single','batch']:['hex','rgb','hsl','css']){const e=new Element();e.dataset[kind==='image'?'imageMode':'colorCopy']=value;root.append(e);}
  class Processor {pending?:{resolve:(v:any)=>void;reject:(e:Error)=>void};async formats(){return['image/png','image/jpeg','image/webp'];}encode(){return new Promise((resolve,reject)=>{const job={resolve,reject};this.pending=job;jobs.push(job);});}cancel(){this.pending?.reject(new Error('Operation cancelled.'));this.pending=undefined;}async palette(){return[{hex:'#ff0000',share:1}];}}
  class View {ratio=null;clear(){}update(){}setImage(){}fit(){}resize(){}dispose(){}setZoom(){}zoomBy(){}}
  const document=Object.assign(new Element(),{getElementById:(id:string)=>ids.get(id),createElement:()=>new Element()}),window=new Element();
  const dependencies:Record<string,any>={'../lib/image/model.ts':model,'../lib/image/palette.ts':palette,'../lib/utilities.ts':utilities,'../lib/image/client.ts':{ImageProcessor:Processor},'../lib/image/crop-view.ts':{CropView:View},'../lib/image/inspect.ts':{inspectImage:async(file:File)=>{if(file.name==='bad.png')throw new Error('Bad image');return{format:'image/png',width:1200,height:800,orientation:1,bytes:file.size};}},'../lib/image/process.ts':{decode:async()=>({width:1200,height:800,close(){}}),release(){}},'../lib/image/handoff.ts':{sendMedia:async()=> 'test-token'},'../lib/image/zip.ts':{zipResults:async()=>new Blob(['zip'])}};
  class TestURL extends URL {static createObjectURL(blob:Blob){blobs.push(blob);return 'blob:test';}static revokeObjectURL(){}}
  const context={Error,exports:{},require:(id:string)=>{assert.ok(id in dependencies,id);return dependencies[id];},document,window,Event,Blob,File,TextEncoder,structuredClone,URL:TestURL,location:{href:'http://localhost/tools/',reload(){}},history:{replaceState(){}},navigator:{clipboard:{writeText:async()=>{throw new Error('denied');}}},confirm:()=>true,ResizeObserver:class{observe(){}disconnect(){}},createImageBitmap:async()=>({width:1200,height:800,close(){}}),setTimeout:(fn:()=>void)=>{const id=++seq;timers.set(id,fn);return id;},clearTimeout:(id:number)=>timers.delete(id)};
  const source=ts.transpileModule(readFileSync(new URL(`../src/scripts/${kind==='image'?'image-bench':'color-workshop'}.ts`,import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;vm.runInNewContext(source,context);
  return{el,root,window,jobs,blobs,change:(id:string,value:string,event='change')=>{el(id).value=value;el(id).dispatchEvent(new Event(event));},load:(names:string[])=>{el('files').files=names.map(name=>new File(['test'],name));el('files').dispatchEvent(new Event('change'));},finish:(index:number)=>jobs[index].resolve({blob:new Blob(['result'],{type:'image/png'}),width:1200,height:800,quality:null,attempts:1,metTarget:true}),close:()=>window.dispatchEvent(new Event('pagehide'))};
}
const flush=()=>new Promise<void>(resolve=>setImmediate(resolve));
test('image UI: replacement cancels stale encodes and a failed replacement does not lock controls',async()=>{const h=harness('image');await flush();h.load(['first.png']);await flush();assert.equal(h.jobs.length,1);h.load(['bad.png']);await flush();assert.equal(h.el('render').disabled,false);assert.match(h.el('status').textContent,/Bad image/);h.el('render').click();await flush();h.finish(1);await flush();assert.equal(h.el('download').disabled,false);h.change('max-width','600');assert.equal(h.el('download').disabled,true);assert.equal(h.el('result').hidden,true);h.close();});
test('image UI: batch cancellation retains completed downloads and allows individual retry',async()=>{const h=harness('image');await flush();h.root.querySelectorAll('[data-image-mode]')[1].click();h.load(['one.png','two.png']);await flush();h.el('run-batch').click();await flush();h.finish(0);await flush();assert.equal(h.jobs.length,2);h.el('cancel').click();await flush();assert.equal(h.el('zip').disabled,false);assert.equal(h.el('queue').children[0].children[2].children.length,2);const retry=h.el('queue').children[1].children[2].children[0];retry.click();await flush();h.finish(2);await flush();assert.equal(h.el('queue').children[1].children[2].children.length,2);h.close();});
test('color UI: importing palette keeps gradient and contrast until explicitly assigned',async()=>{const h=harness('color');h.el('file').files=[new File([JSON.stringify(palette.paletteDocument(['#ff0000','#0000ff']))],'palette.json')];h.el('file').dispatchEvent(new Event('change'));await flush();assert.equal(h.el('a').value,'#ad99e5');assert.equal(h.el('foreground').value,'#000000');h.el('list').children[0].children[3].children[0].click();assert.equal(h.el('a').value,'#ff0000');h.el('list').children[1].children[3].children[2].click();assert.equal(h.el('foreground').value,'#0000ff');});
test('color UI: invalid inputs invalidate copy; denied clipboard exposes manual text; palette caps at eight',async()=>{const h=harness('color');h.change('a','bad','input');assert.ok(h.root.querySelectorAll('[data-color-copy]').every(e=>e.disabled));h.el('reset').click();assert.ok(h.root.querySelectorAll('[data-color-copy]').every(e=>!e.disabled));h.el('copy-all').click();await flush();assert.match(h.el('status').textContent,/Clipboard unavailable/);assert.match(h.el('palette-output').textContent,/#ad99e5/);for(let i=0;i<10;i++)h.el('add').click();assert.equal(h.el('list').children.length,8);assert.equal(h.el('add').disabled,true);const event=new Event('beforeunload',{cancelable:true});h.window.dispatchEvent(event);assert.ok(event.defaultPrevented);});
