import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Worker } from 'node:worker_threads';
import { LabEngine, makeKernel } from '../src/lib/lab/engine.ts';
import { defaults, type ModelId } from '../src/lib/lab/definitions.ts';
import { Convolver } from '../src/lib/lab/fft.ts';
import { LabSession, combinations, decodeExperiment, encodeExperiment, validateExperiment, type Experiment } from '../src/lib/lab/session.ts';
import { createRuntime, type Reply } from '../src/lib/lab/runtime.ts';
import { pixels } from '../src/lib/lab/render.ts';
import { listExperiments } from '../src/lib/lab/storage.ts';

for (const model of ['reaction', 'sand', 'lenia'] as ModelId[]) {
  test(`${model}: deterministic seed, snapshot continuation and finite bounded fields`, () => {
    const a = new LabEngine(model, 128, 123), b = new LabEngine(model, 128, 123); a.step(12); b.step(12); assert.deepEqual(a.snapshot(), b.snapshot()); const resumed = LabEngine.from(a.snapshot()); a.step(10); resumed.step(10); assert.deepEqual(a.snapshot(), resumed.snapshot()); for (const [k, f] of a.state.fields.entries()) for (const v of f) assert.ok(Number.isFinite(v) && v >= 0 && v <= (model === 'sand' ? (k === 0 ? 7 : 1000) : 1));
  });
  test(`${model}: full file round trip reproduces A/B continuation`, () => { const s = new LabSession(model, 128, 42); s.step(7); s.compare(); s.step(5); const json = encodeExperiment(s.export()), copy = new LabSession(model, 128, 8); copy.restore(decodeExperiment(json)); s.step(8); copy.step(8); assert.deepEqual(copy.export(), s.export()); });
}
test('Gray–Scott barriers have zero flux and preserve their own fields', () => { const e = new LabEngine('reaction', 128, 1); e.paint({ x: 64, y: 64, radius: 5, kind: 'Barrier', rotation: 0 }); const before = e.snapshot(); e.step(30); for (let i = 0; i < before.fields[2].length; i++)if (before.fields[2][i]) { assert.equal(e.state.fields[0][i], before.fields[0][i]); assert.equal(e.state.fields[1][i], before.fields[1][i]); } });
test('non-reactive sand scenarios conserve each material exactly', () => { for (const preset of [0, 1]) { const e = new LabEngine('sand', 128, 77, preset), before = e.metrics(); e.step(150); for (const material of ['sand', 'water', 'stone', 'wood']) assert.equal(e.metrics()[material], before[material]); assert.equal(e.metrics().reactions, 0); } });
test('Lenia FFT circular convolution matches a direct convolution', () => { const n = 16, p = { ...defaults('lenia'), radius: 5 }, kernel = makeKernel(n, p), field = Float32Array.from({ length: n * n }, (_, i) => (i * 17 % 31) / 31), actual = new Convolver(kernel, n).apply(field); for (let y = 0; y < n; y++)for (let x = 0; x < n; x++) { let expected = 0; for (let ky = 0; ky < n; ky++)for (let kx = 0; kx < n; kx++)expected += kernel[ky * n + kx] * field[((y - ky + n) % n) * n + (x - kx + n) % n]; assert.ok(Math.abs(actual[y * n + x] - expected) < 1e-11); } });
test('authentic Orbium remains localized and alive for 1000 steps', () => { const e = new LabEngine('lenia', 128, 1); e.step(1000); const m = e.metrics(); assert.ok(m.mass > 50 && m.mass < 100, `mass ${m.mass}`); assert.ok(m.area > .005 && m.area < .025); });
test('A/B shares exact ticks and random state until a targeted intervention', () => { const s = new LabSession('sand', 128, 2, 1); s.step(5); s.compare(); s.step(20); assert.deepEqual(s.a.snapshot(), s.b!.snapshot()); const before = s.a.snapshot(); s.paintStart(); s.paint({ x: 30, y: 30, radius: 4, kind: 'Stone', rotation: 0 }, 'b'); assert.deepEqual(s.a.snapshot(), before); assert.notDeepEqual(s.a.snapshot(), s.b!.snapshot()); s.undoPaint(); assert.deepEqual(s.a.snapshot(), s.b!.snapshot()); s.step(1); assert.equal(s.a.state.tick, s.b!.state.tick); });
test('rendering and exporting do not advance simulation or consume randomness', () => { const s = new LabSession('lenia', 128, 9); const before = s.export(); pixels(s.a.state, 0); s.a.updatePotential(); pixels(s.a.state, 1, s.a.potential); encodeExperiment(s.export()); assert.deepEqual(s.export(), before); });
test('branch reset restores complete state and recent paint undo does not rewind time', () => { const s = new LabSession('reaction', 128, 8); s.step(13); s.compare(); const branch = s.a.snapshot(); s.step(7); s.reset(true); assert.deepEqual(s.a.snapshot(), branch); s.paintStart(); s.paint({ x: 20, y: 20, radius: 3, kind: 'Seed', rotation: 0 }, 'both'); s.step(); const state = s.a.snapshot(); s.undoPaint(); assert.deepEqual(s.a.snapshot(), state); });
test('parameter scans generate uniformly sampled bounded combinations', () => { const settings = { steps: 100, axes: [{ key: 'feed', min: .04, max: .06, count: 3 }, { key: 'kill', min: .05, max: .07, count: 5 }] }; assert.equal(combinations('reaction', settings).length, 15); assert.throws(() => combinations('reaction', { ...settings, steps: 99 })); assert.throws(() => combinations('sand', { steps: 100, axes: [{ key: 'gravity', min: 1, max: 4, count: 3 }] })); assert.throws(() => combinations('lenia', { steps: 100, axes: [{ key: 'mu', min: .1, max: .2, count: 6 }] })); });
test('imports reject corrupt data without replacing the current experiment', () => { const s = new LabSession('reaction', 128, 3), before = s.export(); const invalid: Experiment = structuredClone(before); invalid.a.fields[0][0] = NaN; assert.throws(() => s.restore(invalid)); assert.deepEqual(s.export(), before); assert.throws(() => decodeExperiment('{not json')); assert.throws(() => decodeExperiment(encodeExperiment({ ...before, version: 2 } as unknown as Experiment))); const bad = structuredClone(before); bad.a.size = 256; assert.throws(() => validateExperiment(bad)); const broken = structuredClone(before); broken.a.params.feed = 1; assert.throws(() => validateExperiment(broken)); });
test('metrics history retains only the most recent 2000 samples', () => { const s = new LabSession('reaction', 128, 1); for (let i = 1; i < 2100; i++) { s.a.state.tick = i * 10; s.sample(); } assert.equal(s.samples.length, 2000); assert.equal(s.samples[0].tick, 1000); });
test('unavailable IndexedDB gives a recoverable error', async () => { await assert.rejects(listExperiments(), /unavailable/); const s = new LabSession('sand', 128, 1); assert.equal(decodeExperiment(encodeExperiment(s.export())).format, 'ortunate-lab'); });
test('runtime rejects stale generations and pause cancels scheduled work', async () => { const messages: Reply[] = [], runtime = createRuntime(message => messages.push(structuredClone(message))); runtime.handle({ id: 1, generation: 2, command: 'init', data: { model: 'sand', size: 128, seed: 1, preset: 0 } }); runtime.handle({ id: 2, generation: 1, command: 'step' }); runtime.handle({ id: 3, generation: 2, command: 'export' }); assert.equal(messages.find(m => m.id === 3)?.data.a.tick, 0); runtime.handle({ id: 4, generation: 2, command: 'run' }); runtime.handle({ id: 5, generation: 2, command: 'pause' }); await new Promise(r => setTimeout(r, 30)); runtime.handle({ id: 6, generation: 2, command: 'export' }); assert.equal(messages.find(m => m.id === 6)?.data.a.tick, 0); runtime.dispose(); });
test('runtime scan cancellation preserves finished cells and leaves interactive state untouched', async () => { const messages: Reply[] = [], runtime = createRuntime(message => messages.push(structuredClone(message))); runtime.handle({ id: 1, generation: 1, command: 'init', data: { model: 'reaction', size: 128, seed: 1, preset: 0 } }); runtime.handle({ id: 2, generation: 1, command: 'scan', data: { steps: 10000, axes: [{ key: 'feed', min: .04, max: .06, count: 2 }] } }); await new Promise(r => setTimeout(r, 30)); runtime.handle({ id: 3, generation: 1, command: 'cancelScan' }); runtime.handle({ id: 4, generation: 1, command: 'export' }); const state = messages.find(m => m.id === 4)!.data; assert.equal(state.a.tick, 0); assert.ok(state.scan.results.length < 2); await new Promise(r => setTimeout(r, 30)); runtime.handle({ id: 5, generation: 1, command: 'export' }); assert.deepEqual(messages.find(m => m.id === 5)!.data, state); runtime.dispose(); });
test('worker-thread adapter executes scans identically to individual runs', async () => {
  const runtimeURL = new URL('../src/lib/lab/runtime.ts', import.meta.url).href;
  const source = `import {parentPort} from 'node:worker_threads'; import {createRuntime} from ${JSON.stringify(runtimeURL)}; const runtime=createRuntime(m=>parentPort.postMessage(m));parentPort.on('message',m=>runtime.handle(m));`;
  const worker = new Worker(new URL(`data:text/javascript,${encodeURIComponent(source)}`));
  try {    
let seq = 0; const request = (command: string, data?: unknown) => new Promise<any>((resolve, reject) => { const id = ++seq; const timer = setTimeout(() => { worker.off('message', receive); reject(new Error('Worker timeout')); }, 10000); const receive = (m: Reply) => { if (m.type === 'reply' && m.id === id) { clearTimeout(timer); worker.off('message', receive); m.error ? reject(new Error(m.error)) : resolve(m.data); } }; worker.on('message', receive); worker.postMessage({ id, generation: 1, command, data }); });
    await request('init', { model: 'sand', size: 128, seed: 17, preset: 1 }); const completed = new Promise<void>((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Scan timeout')), 10000); worker.on('message', (m: Reply) => { if (m.type === 'scan' && m.data?.complete) { clearTimeout(timer); resolve(); } }); }); await request('scan', { steps: 100, axes: [{ key: 'spread', min: .2, max: .8, count: 2 }] }); await completed; const doc = await request('export') as Experiment; assert.equal(doc.scan!.results.length, 2); for (const cell of doc.scan!.results) { const e = LabEngine.from(doc.scan!.source); e.setParams(cell.params); e.step(100); assert.deepEqual(e.snapshot(), cell.state); } validateExperiment(doc);
  } finally { await worker.terminate(); }
});
