import { test } from 'node:test';
import assert from 'node:assert/strict';
import { canMove, moveBoard, spawnTile, validBoard } from '../src/lib/game2048.ts';
import { canTurn, newSnake, stepSnake, foodFor } from '../src/lib/snake.ts';
import { defaultTimer, secondsLeft, startTimer, pauseTimer, validTimer } from '../src/lib/timer.ts';
import { textStats } from '../src/lib/text.ts';
test('2048 merges pairs once per move and scores every pair',()=>{const result=moveBoard([2,2,2,2,...Array(12).fill(0)],'left');assert.deepEqual(result.board.slice(0,4),[4,4,0,0]);assert.equal(result.score,8);assert.equal(result.changed,true);});
test('2048 does not merge a freshly merged tile again',()=>{assert.deepEqual(moveBoard([2,2,4,0,...Array(12).fill(0)],'left').board.slice(0,4),[4,4,0,0]);});
test('2048 movement respects every direction',()=>{const b=[2,0,0,0,2,...Array(11).fill(0)];assert.equal(moveBoard(b,'down').board[12],4);assert.equal(moveBoard(b,'up').board[0],4);assert.equal(moveBoard(b,'right').board[3],2);});
test('2048 unchanged moves do not request a spawn',()=>{assert.equal(moveBoard([2,...Array(15).fill(0)],'left').changed,false);});
test('2048 full boards distinguish loss and possible merge',()=>{const b=[2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2];assert.equal(canMove(b),false);b[0]=4;assert.equal(canMove(b),true);});
test('2048 spawn uses an empty cell without mutating input',()=>{const b=Array(16).fill(2);b[7]=0;const result=spawnTile(b,()=>.99);assert.equal(result.index,7);assert.equal(result.board[7],4);assert.equal(b[7],0);});
test('2048 rejects corrupt persisted boards',()=>{assert.equal(validBoard([2]),false);assert.equal(validBoard(Array(16).fill(3)),false);assert.equal(validBoard(Array(16).fill(0)),true);});
test('snake cannot reverse or cross a wall',()=>{assert.equal(canTurn('right','left'),false);const s=newSnake();s.body=[{x:19,y:10},{x:18,y:10}];assert.equal(stepSnake(s).over,true);});
test('snake grows, scores, and spawns unoccupied food',()=>{const s=newSnake();s.food={x:10,y:10};const n=stepSnake(s,'right',20,()=>0);assert.equal(n.score,10);assert.equal(n.body.length,s.body.length+1);assert.ok(!n.body.some(p=>p.x===n.food!.x&&p.y===n.food!.y));});
test('snake can move into the vacating tail, but not its body',()=>{const s=newSnake();s.body=[{x:2,y:2},{x:2,y:3},{x:1,y:3},{x:1,y:2}];s.direction='up';assert.equal(stepSnake(s,'left').over,false);s.body=[{x:2,y:2},{x:2,y:3},{x:1,y:3},{x:1,y:2},{x:1,y:1}];assert.equal(stepSnake(s,'left').over,true);});
test('snake full board has no food position',()=>{assert.equal(foodFor([{x:0,y:0}],1),null);});
test('timer uses elapsed wall time after tab suspension',()=>{const s=startTimer(defaultTimer(),1000);assert.equal(secondsLeft(s,61000),1440);assert.equal(secondsLeft(s,2_000_000),0);});
test('timer pause and resume preserve remaining time',()=>{const s=pauseTimer(startTimer(defaultTimer(),1000),61000);assert.equal(s.end,null);assert.equal(s.remaining,1440);assert.equal(secondsLeft(startTimer(s,100000),101000),1439);});
test('timer rejects invalid persisted values',()=>{assert.equal(validTimer(defaultTimer()),true);assert.equal(validTimer({...defaultTimer(),focus:-1}),false);});
test('word count handles mixed languages, emoji and newlines',()=>{assert.deepEqual(textStats('Hello world!\n你好 🌍'),{characters:17,compact:14,words:2,chinese:2,lines:2});assert.equal(textStats('').lines,0);});
