import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import * as model from '../src/lib/windward/model.ts';
import * as controls from '../src/lib/windward/controls.ts';

/** DOM event adapters, not browser automation. Graphics are tested separately. */
function harness(options:{reduced?:boolean;deferView?:boolean;storageFails?:boolean;viewFails?:boolean;mode?:string}={}){
  let document:any,allowReplace=true,viewResolve:((value:any)=>void)|undefined,seq=0;const frames=new Map<number,(time:number)=>void>(),blobs:Blob[]=[],views:View[]=[],saved:any[]=[];
  class Element extends EventTarget {dataset:Record<string,string>={};children:Element[]=[];hidden=false;disabled=false;value='';textContent='';className='';files:any[]=[];attributes:Record<string,string>={};style={};append(...nodes:Element[]){this.children.push(...nodes);}replaceChildren(...nodes:Element[]){this.children=nodes;}setAttribute(k:string,v:string){this.attributes[k]=v;}click(){if(!this.disabled)this.dispatchEvent(new Event('click'));}focus(){document.activeElement=this;}setPointerCapture(){}getBoundingClientRect(){return{left:0,top:0,width:1000,height:800};}}
  const markup=readFileSync(new URL('../src/pages/worlds/windward.astro',import.meta.url),'utf8'),ids=new Map<string,Element>(),tools:Element[]=[];for(const [,id]of markup.matchAll(/id="(wind-[^"]+)"/g))ids.set(id,new Element());const el=(id:string)=>ids.get(`wind-${id}`)!;
  for(const tool of ['wind','sow','erase','observe']){const e=new Element();e.dataset.windTool=tool;tools.push(e);}for(const [id,value]of Object.entries({species:'flower',radius:'.7',quality:'auto',renderer:options.mode??'auto'}))el(id).value=value;
  document=Object.assign(new Element(),{hidden:false,documentElement:new Element(),getElementById:(id:string)=>ids.get(id),querySelectorAll:()=>tools,createElement:()=>new Element()});document.documentElement.dataset.motion=options.reduced?'reduced':'full';const window=new Element();
  class View {static failures=0;doc=model.garden();disposed=false;draws=0;constructor(){if(options.viewFails&&View.failures++===0)throw new Error('Failed to fetch dynamically imported module');views.push(this);}draw(d:model.Garden){this.doc=structuredClone(d);this.draws++;}resize(){}point(x:number,y:number){return{x:x/100,z:y/100};}mark(){}dispose(){this.disposed=true;}async snapshot(){return new Blob(['png'],{type:'image/png'});}}
  const viewModule=options.deferView?new Promise(resolve=>viewResolve=resolve):{GardenView:View};
  const dependencies:Record<string,any>={'../lib/windward/model.ts':model,'../lib/windward/controls.ts':controls,'../lib/windward/view.ts':viewModule,'../lib/windward/view-2d.ts':{Garden2DView:View},'../lib/windward/storage.ts':{listGardens:async()=>[],saveGarden:async(d:model.Garden)=>{if(options.storageFails)throw new Error('Storage failed. Export instead.');saved.push(d);},removeGarden:async()=>{}},'../lib/image/handoff.ts':{sendMedia:async()=> 'token'}};
  const context={exports:{},Error,require:(id:string)=>{assert.ok(id in dependencies,id);return dependencies[id];},document,window,Event,Blob,File,AbortController,TextEncoder,structuredClone,performance,innerWidth:1000,confirm:()=>allowReplace,matchMedia:()=>({matches:false}),localStorage:{setItem(){}},URL:{createObjectURL:(blob:Blob)=>{blobs.push(blob);return 'blob:test';},revokeObjectURL(){}},requestAnimationFrame:(fn:(time:number)=>void)=>{const id=++seq;frames.set(id,fn);return id;},cancelAnimationFrame:(id:number)=>frames.delete(id),setTimeout:()=>++seq,clearTimeout(){},ResizeObserver:class{observe(){}disconnect(){}},FileReader:class{result='data:image/png;base64,test';onload?:()=>void;readAsDataURL(){this.onload?.();}},location:{reload(){}}};
  const source=ts.transpileModule(readFileSync(new URL('../src/scripts/windward.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(source,context);
  const pointer=(type:string,x:number,y:number,id=1,pointerType='mouse',buttons=1)=>el('scene').dispatchEvent(Object.assign(new Event(type),{clientX:x,clientY:y,pointerId:id,pointerType,button:buttons===2?2:0,buttons}));
  return{el,tools,document,window,views,frames,blobs,saved,pointer,change:(id:string,value:string,event='change')=>{el(id).value=value;el(id).dispatchEvent(new Event(event));},key:(key:string,props={})=>el('scene').dispatchEvent(Object.assign(new Event('keydown',{cancelable:true}),{key,...props})),tick:(time:number)=>{const all=[...frames.values()];frames.clear();for(const f of all)f(time);},allowReplace:(allow:boolean)=>allowReplace=allow,resolveView:()=>viewResolve?.({GardenView:View}),close:()=>window.dispatchEvent(new Event('pagehide'))};
}
const flush=()=>new Promise<void>(resolve=>setImmediate(resolve));
test('windward UI: reduced motion starts static, step grows, hidden time is not simulated',async()=>{const h=harness({reduced:true});await flush();assert.equal(h.frames.size,0);h.el('step').click();assert.equal(h.views[0].doc.tick,30);h.el('motion').click();h.tick(0);h.tick(100);assert.equal(h.views[0].doc.tick,33);h.document.hidden=true;h.document.dispatchEvent(new Event('visibilitychange'));assert.equal(h.frames.size,0);h.document.hidden=false;h.document.dispatchEvent(new Event('visibilitychange'));h.tick(100000);assert.equal(h.views[0].doc.tick,33);h.close();assert.ok(h.views[0].disposed);assert.equal(h.frames.size,0);});
test('windward UI: mouse stroke is atomic, undo restores planting, observe never plants',async()=>{const h=harness({reduced:true});await flush();h.tools[1].click();h.pointer('pointerdown',0,0);h.pointer('pointermove',100,100);h.pointer('pointerup',100,100);assert.ok(h.views[0].doc.plants.length>65);h.el('undo').click();assert.equal(h.views[0].doc.plants.length,65);h.el('redo').click();const count=h.views[0].doc.plants.length;h.tools[3].click();h.pointer('pointerdown',0,0);h.pointer('pointermove',50,50);h.pointer('pointerup',50,50);assert.equal(h.views[0].doc.plants.length,count);assert.notEqual(h.views[0].doc.camera.azimuth,.55);h.close();});
test('windward UI: two-finger orbit does not accidentally sow, keyboard is scoped to the garden',async()=>{const h=harness({reduced:true});await flush();h.tools[1].click();h.pointer('pointerdown',0,0,1,'touch');h.pointer('pointerdown',100,0,2,'touch');h.pointer('pointermove',110,10,2,'touch');h.pointer('pointerup',110,10,2,'touch');h.pointer('pointerup',0,0,1,'touch');assert.equal(h.views[0].doc.plants.length,65);h.key('Enter');assert.ok(h.views[0].doc.plants.length>65);const count=h.views[0].doc.plants.length;h.el('name').dispatchEvent(Object.assign(new Event('keydown'),{key:'Enter'}));assert.equal(h.views[0].doc.plants.length,count);h.close();});
test('windward UI: invalid import and declined replacement preserve edited garden',async()=>{const h=harness({reduced:true});await flush();h.change('name','My meadow');h.el('file').files=[new File(['{bad'],'bad.json')];h.el('file').dispatchEvent(new Event('change'));await flush();assert.equal(h.views[0].doc.name,'A place in the wind');h.el('export').click();assert.equal(JSON.parse(await h.blobs[0].text()).name,'My meadow');h.change('name','Keep this');h.allowReplace(false);h.change('seed','92');h.el('new').click();h.el('export').click();assert.equal(JSON.parse(await h.blobs[1].text()).seed,17);h.close();});
test('windward UI: failed save stays unsaved and editable export remains available',async()=>{const h=harness({reduced:true,storageFails:true});await flush();h.change('name','A keeper');h.el('save').click();await flush();assert.match(h.el('status').textContent,/Storage failed/);const event=new Event('beforeunload',{cancelable:true});h.window.dispatchEvent(event);assert.ok(event.defaultPrevented);h.el('export').click();assert.equal(JSON.parse(await h.blobs[0].text()).name,'A keeper');h.close();});
test('windward UI: late renderer load cannot create a scene after leaving',async()=>{const h=harness({deferView:true});h.close();h.resolveView();await flush();assert.equal(h.views.length,0);assert.equal(h.frames.size,0);});
test('windward UI: failed 3D construction automatically switches to editable 2D',async()=>{const h=harness({viewFails:true,reduced:true});await flush();assert.equal(h.document.documentElement.dataset.gardenRenderer,'2d');assert.match(h.el('status').textContent,/now running in 2D/);assert.equal(h.el('save').disabled,false);h.tools[1].click();h.key('Enter');assert.ok(h.views[0].doc.plants.length>65);h.el('export').click();assert.ok(JSON.parse(await h.blobs[0].text()).plants.length>65);h.close();});
test('windward UI: manual 2D mode never waits for the 3D module and switches without losing planting',async()=>{const h=harness({mode:'2d',deferView:true,reduced:true});await flush();assert.equal(h.views.length,1);assert.equal(h.document.documentElement.dataset.gardenRenderer,'2d');h.tools[1].click();h.key('Enter');const count=h.views[0].doc.plants.length;h.change('quality','low');await flush();assert.ok(h.views[0].disposed);assert.equal(h.views[1].doc.plants.length,count);h.close();});

test('windward UI: right-click release never plants and quick undo handles the final endpoint',async()=>{
  const h=harness({reduced:true,mode:'2d'});try{await flush();h.tools[1].click();
    const count=h.views[0].doc.plants.length;h.pointer('pointerdown',400,400,1,'mouse',2);h.pointer('pointerup',400,400,1,'mouse',2);assert.equal(h.views[0].doc.plants.length,count);
    h.pointer('pointerdown',0,0);h.pointer('pointerup',400,300);assert.ok(h.views[0].doc.plants.some(p=>Math.hypot(p.x-4,p.z-3)<.7));
    h.el('quick-undo').click();assert.equal(h.views[0].doc.plants.length,count);
  }finally{h.close();}
});
