export const LIMIT=1024,STEP=1/30;
export type Species='grass'|'flower'|'plume';
export interface Plant {id:number;x:number;z:number;kind:Species;age:number;variation:number}
export interface Garden {format:'ortunate-windward';version:1;name:string;seed:number;tick:number;nextId:number;plants:Plant[];environment:{direction:number;strength:number;light:'morning'|'noon'|'evening'};camera:{azimuth:number;polar:number;distance:number}}
export interface Pulse {x:number;z:number;age:number;strength:number}
export const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export function random(seed:number){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
export function heightAt(x:number,z:number,seed:number){const p=(seed%1000)*.01;return .3+Math.cos(x*.43+p)*.38+Math.sin(z*.55-p)*.28+Math.cos((x+z)*.7)*.12;}
export function inside(x:number,z:number){return Number.isFinite(x)&&Number.isFinite(z)&&x*x+z*z<=7.6**2;}
export function garden(seed=17):Garden {const r=random(seed),plants:Plant[]=[];for(let i=0;i<65;i++){const a=r()*Math.PI*2,d=Math.sqrt(r())*6.8;plants.push({id:i,x:Math.cos(a)*d,z:Math.sin(a)*d,kind:i%3===0?'plume':'flower',age:8,variation:r()});}return{format:'ortunate-windward',version:1,name:'A place in the wind',seed:seed>>>0,tick:0,nextId:65,plants,environment:{direction:35,strength:.45,light:'morning'},camera:{azimuth:.55,polar:1.04,distance:20}};}
export function validate(value:unknown):asserts value is Garden {const d=value as Garden,n=(v:unknown,a:number,b:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b,integer=(v:unknown,a:number,b:number)=>n(v,a,b)&&Number.isInteger(v);if(!d||d.format!=='ortunate-windward'||d.version!==1||typeof d.name!=='string'||d.name.length>80||!integer(d.seed,0,4294967295)||!integer(d.tick,0,Number.MAX_SAFE_INTEGER)||!integer(d.nextId,0,Number.MAX_SAFE_INTEGER-1)||!Array.isArray(d.plants)||d.plants.length>LIMIT||!d.environment||!n(d.environment.direction,0,360)||!n(d.environment.strength,0,1)||!['morning','noon','evening'].includes(d.environment.light)||!d.camera||!n(d.camera.azimuth,-Math.PI*2,Math.PI*2)||!n(d.camera.polar,.3,1.32)||!n(d.camera.distance,10,32))throw new Error('Choose a valid version 1 Windward garden.');const ids=new Set<number>();for(const p of d.plants){if(!p||!integer(p.id,0,d.nextId-1)||ids.has(p.id)||!inside(p.x,p.z)||!['grass','flower','plume'].includes(p.kind)||!n(p.age,0,8)||!n(p.variation,0,1))throw new Error('Invalid plant in garden file.');ids.add(p.id);}}
export function encode(d:Garden){validate(d);return JSON.stringify(d);}
export function decode(text:string){if(new TextEncoder().encode(text).length>1048576)throw new Error('Garden files are limited to 1 MiB.');const value:unknown=JSON.parse(text);validate(value);return value;}
export function sow(d:Garden,x:number,z:number,radius:number,kind:Species){if(!inside(x,z))return 0;const r=random((d.seed+d.nextId*13)>>>0);let added=0;for(let i=0;i<Math.ceil(radius*3);i++){if(d.plants.length>=LIMIT)break;const a=r()*Math.PI*2,s=Math.sqrt(r())*radius,px=x+Math.cos(a)*s,pz=z+Math.sin(a)*s;if(!inside(px,pz)||d.plants.some(p=>(p.x-px)**2+(p.z-pz)**2<.035))continue;d.plants.push({id:d.nextId++,x:px,z:pz,kind,age:0,variation:r()});added++;}return added;}
export function erase(d:Garden,x:number,z:number,radius:number){const before=d.plants.length;d.plants=d.plants.filter(p=>(p.x-x)**2+(p.z-z)**2>radius*radius);return before-d.plants.length;}
export function advance(d:Garden,pulses:Pulse[]){d.tick++;for(const p of d.plants)p.age=Math.min(8,p.age+STEP);for(const p of pulses)p.age+=STEP;return pulses.filter(p=>p.age<3);}
export function pulse(pulses:Pulse[],x:number,z:number,strength=1){if(inside(x,z)){pulses.push({x,z,age:0,strength:clamp(strength,0,2)});if(pulses.length>8)pulses.shift();}}
export function bend(x:number,z:number,time:number,env:Garden['environment'],pulses:Pulse[]){const a=env.direction*Math.PI/180,w=(.5+Math.sin(time*1.8+x*.6+z*.4)*.22+Math.sin(time*.7-z*.7)*.15)*env.strength;let bx=Math.cos(a)*w,bz=Math.sin(a)*w;for(const p of pulses){const dx=x-p.x,dz=z-p.z,dist=Math.hypot(dx,dz),fall=Math.exp(-dist*dist/5)*Math.exp(-p.age*1.8)*Math.sin(p.age*8+.6)*p.strength;bx+=(dist>.01?dx/dist:1)*fall;bz+=(dist>.01?dz/dist:0)*fall;}const length=Math.hypot(bx,bz),scale=length>1.1?1.1/length:1;return{x:bx*scale,z:bz*scale};}
export class History {undoStack:Garden[]=[];redoStack:Garden[]=[];private start?:Garden;begin(d:Garden){if(!this.start)this.start=structuredClone(d);}commit(d:Garden){if(!this.start)return false;const before=this.start;this.start=undefined;const editable=(g:Garden)=>JSON.stringify({...g,tick:0,plants:g.plants.map(p=>({...p,age:0}))});if(editable(before)===editable(d))return false;this.undoStack.push(before);if(this.undoStack.length>50)this.undoStack.shift();this.redoStack=[];return true;}undo(d:Garden){const old=this.undoStack.pop();if(old){this.redoStack.push(structuredClone(d));return structuredClone(old);}return d;}redo(d:Garden){const next=this.redoStack.pop();if(next){this.undoStack.push(structuredClone(d));return structuredClone(next);}return d;}clear(){this.start=undefined;this.undoStack=[];this.redoStack=[];}}
