import * as THREE from 'three';
import {heightAt,random,bend,STEP,type Garden,type Pulse,type Species} from './model.ts';
type Quality='high'|'low';
interface Blade {x:number;z:number;variation:number;kind:Species;age:number}
const colors={morning:{sky:0xc5ddd9,fog:0xdce4cb,sun:0xffebbc,ground:0x8f9c65},noon:{sky:0xb5d4df,fog:0xe0ead8,sun:0xfff5dd,ground:0x88a16a},evening:{sky:0xd6c6ba,fog:0xe5d8bd,sun:0xffc987,ground:0x9c9460}};
export function bladeGeometry(kind:Species){const vertices:number[]=[],indices:number[]=[];const segments=5,height=kind==='plume'?1.35:kind==='flower'?.7:.65;for(let plane=0;plane<2;plane++)for(let i=0;i<=segments;i++){const y=i/segments,width=(kind==='flower'?.025:kind==='plume'?.045:.045)*(1-y*.9),curve=.16*Math.sin(y*Math.PI);for(const side of [-1,1])vertices.push(plane?curve:curve+side*width,height*y,plane?side*width:0);if(i<segments){const n=plane*(segments+1)*2+i*2;indices.push(n,n+1,n+2,n+1,n+3,n+2);}}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;}
export function groundGeometry(seed:number){// A regular polar lattice follows the same height function as planting.
  const positions:number[]=[0,heightAt(0,0,seed),0],indices:number[]=[];const rings=32,segments=96;for(let r=1;r<=rings;r++)for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,d=8*r/rings,x=Math.cos(a)*d,z=Math.sin(a)*d;positions.push(x,heightAt(x,z,seed),z);}for(let i=0;i<segments;i++)indices.push(0,1+(i+1)%segments,1+i);for(let r=1;r<rings;r++)for(let i=0;i<segments;i++){const a=1+(r-1)*segments+i,b=1+(r-1)*segments+(i+1)%segments,c=a+segments,d=b+segments;indices.push(a,d,c,a,b,d);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;}
export function createGardenScene(seed:number,quality:Quality){
  const scene=new THREE.Scene();scene.background=new THREE.Color(colors.morning.sky);scene.fog=new THREE.FogExp2(colors.morning.fog,.025);
  const camera=new THREE.PerspectiveCamera(38,1,.1,120);const hemi=new THREE.HemisphereLight(0xe7f3e8,0x7c7954,2.4);scene.add(hemi);const sun=new THREE.DirectionalLight(colors.morning.sun,3.1);sun.position.set(-9,15,8);sun.castShadow=true;sun.shadow.mapSize.set(quality==='high'?1024:512,quality==='high'?1024:512);sun.shadow.camera.left=sun.shadow.camera.bottom=-12;sun.shadow.camera.right=sun.shadow.camera.top=12;sun.shadow.camera.far=45;sun.shadow.normalBias=.08;scene.add(sun);
  const ground=new THREE.Mesh(groundGeometry(seed),new THREE.MeshStandardMaterial({color:colors.morning.ground,roughness:1,vertexColors:true}));ground.geometry.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(ground.geometry.getAttribute('position').count*3).fill(1),3));ground.receiveShadow=true;scene.add(ground);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0xdce0c6,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.85;floor.receiveShadow=true;scene.add(floor);
  const skirt=new THREE.CylinderGeometry(8,7.5,1,96,1,true),skirtPositions=skirt.getAttribute('position');for(let i=0;i<skirtPositions.count;i++){const x=skirtPositions.getX(i),z=skirtPositions.getZ(i);skirtPositions.setY(i,skirtPositions.getY(i)>0?heightAt(x,z,seed):-.85);}skirt.computeVertexNormals();const earth=new THREE.Mesh(skirt,new THREE.MeshStandardMaterial({color:0x8b8663,roughness:1}));earth.castShadow=true;scene.add(earth);
  // Soft horizon silhouettes add depth without textures or network assets.
  const hillMaterial=new THREE.MeshStandardMaterial({color:0xb3c4a3,roughness:1});for(let i=0;i<7;i++){const hill=new THREE.Mesh(new THREE.SphereGeometry(1,24,12),hillMaterial);hill.position.set((i-3)*18,-2,-34-Math.abs(i-3)*3);hill.scale.set(15,3+(i%3)*1.5,8);scene.add(hill);}
  const cloudMaterial=new THREE.MeshBasicMaterial({color:0xf4f1dc,transparent:true,opacity:.17,depthWrite:false});const clouds:THREE.Mesh[]=[];for(let i=0;i<5;i++){const cloud=new THREE.Mesh(new THREE.SphereGeometry(1,24,12),cloudMaterial);cloud.position.set(i*15-30,12+i%2,-22-i*4);cloud.scale.set(9,1.1,3);clouds.push(cloud);scene.add(cloud);}
  const base:Blade[]=[],rand=random(seed);for(let i=0;i<6000;i++){const a=rand()*Math.PI*2,r=Math.sqrt(rand())*7.75;base.push({x:Math.cos(a)*r,z:Math.sin(a)*r,variation:rand(),kind:'grass',age:8});}
  const meshes={} as Record<Species,THREE.InstancedMesh>;for(const kind of ['grass','flower','plume'] as Species[]){const material=new THREE.MeshStandardMaterial({color:kind==='grass'?0x8fa765:0x8c995b,side:THREE.DoubleSide,roughness:1});const geometry=bladeGeometry(kind),capacity=kind==='grass'?7024:1024;geometry.setAttribute('meadowBend',new THREE.InstancedBufferAttribute(new Float32Array(capacity*2),2).setUsage(THREE.DynamicDrawUsage));const stemHeight=kind==='plume'?1.35:kind==='flower'?.7:.65;material.onBeforeCompile=shader=>{shader.vertexShader='attribute vec2 meadowBend;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\nfloat meadowWeight = clamp(position.y / ${stemHeight.toFixed(2)}, 0.0, 1.0);\ntransformed.xz += meadowBend * meadowWeight * meadowWeight * ${(stemHeight*.55).toFixed(4)};`).replace('#include <beginnormal_vertex>',`#include <beginnormal_vertex>\nobjectNormal.y -= dot(objectNormal.xz, meadowBend) * 1.1 * clamp(position.y / ${stemHeight.toFixed(2)}, 0.0, 1.0);\nobjectNormal = normalize(objectNormal);`);};material.customProgramCacheKey=()=>`windward-stem-${kind}`;const mesh=new THREE.InstancedMesh(geometry,material,capacity);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.frustumCulled=false;meshes[kind]=mesh;scene.add(mesh);}
  const flowerGeometry=new THREE.SphereGeometry(1,5,3),plumeGeometry=new THREE.SphereGeometry(1,6,5),heads={} as Record<'flower'|'plume',THREE.InstancedMesh>;for(const kind of ['flower','plume'] as const){const material=new THREE.MeshStandardMaterial({color:kind==='flower'?0xf5dfaf:0xe5d5a3,roughness:.95});const head=new THREE.InstancedMesh(kind==='flower'?flowerGeometry:plumeGeometry,material,1024);head.instanceMatrix.setUsage(THREE.DynamicDrawUsage);head.frustumCulled=false;head.castShadow=quality==='high';heads[kind]=head;scene.add(head);}
  const cursor=new THREE.Mesh(new THREE.RingGeometry(.92,1,48),new THREE.MeshBasicMaterial({color:0xf8f4d5,side:THREE.DoubleSide,transparent:true,opacity:.8,depthTest:false}));cursor.rotation.x=-Math.PI/2;cursor.renderOrder=10;cursor.visible=false;scene.add(cursor);
  const dummy=new THREE.Object3D(),color=new THREE.Color(),up=new THREE.Vector3(0,1,0),axis=new THREE.Vector3(),raycaster=new THREE.Raycaster();let lastTick=-1,lastEnv='',lastCount=-1,lastPulse='';
  function update(doc:Garden,pulses:Pulse[],dt:number,force=false){const target=colors[doc.environment.light],blend=dt>0?1-Math.exp(-dt*2):1;(scene.background as THREE.Color).lerp(color.set(target.sky),blend);(scene.fog as THREE.FogExp2).color.lerp(color.set(target.fog),blend);sun.color.lerp(color.set(target.sun),blend);(ground.material as THREE.MeshStandardMaterial).color.lerp(color.set(target.ground),blend);for(let i=0;i<clouds.length;i++)clouds[i].position.x=i*15-30+Math.sin(doc.tick*STEP*.015+i)*3;
    const {azimuth,polar,distance}=doc.camera;camera.position.set(Math.sin(azimuth)*Math.sin(polar)*distance,Math.cos(polar)*distance+1,Math.cos(azimuth)*Math.sin(polar)*distance);camera.lookAt(0,1,0);camera.updateMatrixWorld();
    const env=JSON.stringify(doc.environment),pk=pulses.map(p=>`${p.x},${p.z},${p.age}`).join(';');if(!force&&lastTick===doc.tick&&lastEnv===env&&lastCount===doc.plants.length&&lastPulse===pk)return;lastTick=doc.tick;lastEnv=env;lastCount=doc.plants.length;lastPulse=pk;
    const shade=(x:number,z:number)=>.86+.14*Math.sin(x*.23+z*.3+doc.tick*STEP*.055)**2,positions=ground.geometry.getAttribute('position'),tints=ground.geometry.getAttribute('color');for(let i=0;i<positions.count;i++){const s=shade(positions.getX(i),positions.getZ(i));tints.setXYZ(i,s,s,s);}tints.needsUpdate=true;
    const counts={grass:0,flower:0,plume:0},hc={flower:0,plume:0};const draw=(p:Blade)=>{const growth=.08+.92*Math.min(1,p.age/5),height=(p.kind==='plume'?1.35:p.kind==='flower'?.7:.65)*(.65+p.variation*.55)*growth,b=bend(p.x,p.z,doc.tick*STEP,doc.environment,pulses);dummy.position.set(p.x,heightAt(p.x,p.z,seed)+.01,p.z);dummy.quaternion.identity();dummy.scale.set(.8+p.variation,height/(p.kind==='plume'?1.35:p.kind==='flower'?.7:.65),1);dummy.updateMatrix();const mesh=meshes[p.kind],index=counts[p.kind]++;mesh.setMatrixAt(index,dummy.matrix);(mesh.geometry.getAttribute('meadowBend') as THREE.InstancedBufferAttribute).setXY(index,b.x*dummy.scale.y/dummy.scale.x,b.z*dummy.scale.y);color.setHSL(p.kind==='grass'?.21+p.variation*.035:.19,.28+p.variation*.12,.34+p.variation*.19);color.multiplyScalar(shade(p.x,p.z));mesh.setColorAt(index,color);
      if(p.kind!=='grass'){const head=heads[p.kind],hi=hc[p.kind]++;dummy.position.add(new THREE.Vector3(b.x*.55*height,height,b.z*.55*height));axis.set(b.x*1.1,1,b.z*1.1).normalize();dummy.quaternion.setFromUnitVectors(up,axis);const size=p.kind==='flower'?.12:.09;dummy.scale.set(size*growth,p.kind==='flower'?.055*growth:.25*growth,size*growth);dummy.updateMatrix();head.setMatrixAt(hi,dummy.matrix);color.set(p.kind==='plume'?0xe4d5aa:p.variation<.35?0xebece0:p.variation<.7?0xe9c679:0xd5a4a0);head.setColorAt(hi,color);}};
    const max=quality==='high'?6000:1800;for(let i=0;i<max;i++)draw(base[i]);for(const p of doc.plants)draw(p);for(const kind of ['grass','flower','plume'] as Species[]){meshes[kind].count=counts[kind];meshes[kind].instanceMatrix.needsUpdate=true;meshes[kind].geometry.getAttribute('meadowBend').needsUpdate=true;if(meshes[kind].instanceColor)meshes[kind].instanceColor!.needsUpdate=true;}for(const kind of ['flower','plume'] as const){heads[kind].count=hc[kind];heads[kind].instanceMatrix.needsUpdate=true;if(heads[kind].instanceColor)heads[kind].instanceColor!.needsUpdate=true;}
  }
  function point(x:number,y:number){scene.updateMatrixWorld();raycaster.setFromCamera(new THREE.Vector2(x,y),camera);return raycaster.intersectObject(ground)[0]?.point;}
  function mark(x:number,z:number,radius:number,visible=true){cursor.visible=visible;cursor.position.set(x,heightAt(x,z,seed)+.03,z);cursor.scale.setScalar(radius);}
  function dispose(){const geometries=new Set<THREE.BufferGeometry>(),mats=new Set<THREE.Material>();scene.traverse(object=>{const mesh=object as THREE.Mesh;if(mesh.geometry)geometries.add(mesh.geometry);if(mesh.material)for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material])mats.add(material);if(object instanceof THREE.InstancedMesh)object.dispose();});geometries.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());sun.shadow.dispose();scene.clear();}
  return{scene,camera,ground,meshes,heads,update,point,mark,dispose};
}
export class GardenView {
  renderer:THREE.WebGLRenderer;world!:ReturnType<typeof createGardenScene>;private host:HTMLElement;private quality:Quality;private seed:number;private lost=false;private abort=new AbortController();
  constructor(host:HTMLElement,doc:Garden,quality:Quality,onLost:()=>void){this.host=host;this.quality=quality;this.seed=doc.seed;this.renderer=new THREE.WebGLRenderer({antialias:quality==='high',alpha:false,powerPreference:'default'});try{this.renderer.debug.onShaderError=(gl,program)=>{throw new Error(`3D shader failed: ${gl.getProgramInfoLog(program)??'unknown graphics error'}`);};this.renderer.shadowMap.enabled=quality==='high';this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,quality==='high'?1.75:1));this.world=createGardenScene(doc.seed,quality);host.prepend(this.renderer.domElement);this.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;onLost();},{signal:this.abort.signal});this.resize();this.draw(doc,[],0,true);}catch(error){this.abort.abort();this.world?.dispose();this.renderer.dispose();this.renderer.domElement.remove();throw error;}}
  resize(){const r=this.host.getBoundingClientRect();this.renderer.setSize(r.width,r.height);this.world.camera.aspect=r.width/Math.max(1,r.height);this.world.camera.fov=Math.min(85,2*Math.atan(Math.tan(19*Math.PI/180)*Math.max(1,1.2/this.world.camera.aspect))*180/Math.PI);this.world.camera.updateProjectionMatrix();}
  draw(doc:Garden,pulses:Pulse[],dt=0,force=false){if(this.lost)return;if(doc.seed!==this.seed){this.world.dispose();this.world=createGardenScene(doc.seed,this.quality);this.seed=doc.seed;this.resize();force=true;}this.world.update(doc,pulses,dt,force);this.renderer.render(this.world.scene,this.world.camera);}
  point(clientX:number,clientY:number){const r=this.host.getBoundingClientRect();return this.world.point((clientX-r.left)/r.width*2-1,-(clientY-r.top)/r.height*2+1);}
  mark(x:number,z:number,radius:number,visible=true){this.world.mark(x,z,radius,visible);}
  async snapshot(doc:Garden,size=1600){if(this.lost)throw new Error('The view is unavailable. Export a garden file instead.');const r=this.host.getBoundingClientRect(),ratio=this.renderer.getPixelRatio(),aspect=this.world.camera.aspect,fov=this.world.camera.fov,visible=this.world.scene.children.filter(o=>o.renderOrder===10).map(o=>[o,o.visible] as const);try{visible.forEach(([o])=>o.visible=false);this.renderer.setPixelRatio(1);this.renderer.setSize(size,Math.round(size/1.6),false);this.world.camera.aspect=1.6;this.world.camera.fov=38;this.world.camera.updateProjectionMatrix();this.draw(doc,[],0,true);const copy=document.createElement('canvas');copy.width=size;copy.height=Math.round(size/1.6);copy.getContext('2d')!.drawImage(this.renderer.domElement,0,0);return await new Promise<Blob>((resolve,reject)=>copy.toBlob(blob=>blob?resolve(blob):reject(new Error('PNG export failed.')),'image/png'));}finally{visible.forEach(([o,v])=>o.visible=v);this.renderer.setPixelRatio(ratio);this.renderer.setSize(r.width,r.height,false);this.world.camera.aspect=aspect;this.world.camera.fov=fov;this.world.camera.updateProjectionMatrix();this.draw(doc,[],0,true);}}
  dispose(){this.abort.abort();this.world.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
