import {random,heightAt,bend,inside,STEP,type Garden,type Pulse,type Plant} from './model.ts';
export interface GardenRenderer {resize():void;draw(doc:Garden,pulses:Pulse[],dt?:number,force?:boolean):void;point(x:number,y:number):{x:number;z:number}|undefined;mark(x:number,z:number,radius:number,visible?:boolean):void;snapshot(doc:Garden,size?:number):Promise<Blob>;dispose():void}
export function projection(doc:Garden,width:number,height:number){const angle=doc.camera.azimuth-.55,c=Math.cos(angle),s=Math.sin(angle),scale=Math.min(width/18,height/11)*20/doc.camera.distance,tilt=.22+(1.32-doc.camera.polar)*.36,cx=width*.53,cy=height*.68;return{scale,tilt,cx,cy,project(x:number,z:number){return{x:cx+(x*c-z*s)*scale,y:cy+(x*s+z*c)*scale*tilt-heightAt(x,z,doc.seed)*scale*.5,depth:x*s+z*c};},unproject(px:number,py:number){const rx=(px-cx)/scale;if(Math.abs(rx)>7.6)return undefined;let low=-8,high=8;const target=(py-cy)/scale;for(let i=0;i<30;i++){const mid=(low+high)/2,x=rx*c+mid*s,z=-rx*s+mid*c;if(mid*tilt-heightAt(x,z,doc.seed)*.5<target)low=mid;else high=mid;}const rz=(low+high)/2,x=rx*c+rz*s,z=-rx*s+rz*c;return inside(x,z)?{x,z}:undefined;}};}
const palettes={morning:{sky:'#b8d5d5',haze:'#edf0d7',sun:'#fff8d8',hill:'#a5bb92',near:'#78966b'},noon:{sky:'#a9cfe0',haze:'#eff0d1',sun:'#fffde6',hill:'#9ab793',near:'#709565'},evening:{sky:'#cdbac4',haze:'#f0d5ad',sun:'#ffe3a6',hill:'#b2ac86',near:'#88855a'}};
export class Garden2DView implements GardenRenderer {
  private canvas:HTMLCanvasElement;private context:CanvasRenderingContext2D;private backdrop:HTMLCanvasElement;private host:HTMLElement;private quality:'high'|'low';private width=1;private height=1;private ratio=1;private backgroundKey='';private lastFrameKey='';private lastPlants?:Plant[];private seed=-1;private base:Plant[]=[];private doc:Garden;private marker={x:0,z:0,radius:1,visible:false};private disposed=false;private visualTime=0;private projectedKey='';private layoutPlants?:Plant[];private projected:{index:number;x:number;y:number;depth:number}[]=[];
  constructor(host:HTMLElement,doc:Garden,quality:'high'|'low'){this.host=host;this.doc=doc;this.quality=quality;this.canvas=document.createElement('canvas');const context=this.canvas.getContext('2d');if(!context)throw new Error('Canvas 2D could not start. Reload the page or export your garden file.');this.context=context;this.backdrop=document.createElement('canvas');host.prepend(this.canvas);this.resize();}
  resize(){const r=this.host.getBoundingClientRect();this.width=Math.max(1,r.width);this.height=Math.max(1,r.height);this.ratio=Math.min(devicePixelRatio||1,this.quality==='high'?1.5:1);this.canvas.width=Math.round(this.width*this.ratio);this.canvas.height=Math.round(this.height*this.ratio);this.backdrop.width=this.canvas.width;this.backdrop.height=this.canvas.height;this.backgroundKey='';}
  private background(doc:Garden,width:number,height:number){const c=this.backdrop.getContext('2d')!,p=palettes[doc.environment.light];c.setTransform(this.ratio,0,0,this.ratio,0,0);const sky=c.createLinearGradient(0,0,0,height);sky.addColorStop(0,p.sky);sky.addColorStop(.55,p.haze);sky.addColorStop(1,p.near);c.fillStyle=sky;c.fillRect(0,0,width,height);const glow=c.createRadialGradient(width*.75,height*.27,0,width*.75,height*.27,width*.4);glow.addColorStop(0,p.sun+'cc');glow.addColorStop(.3,p.sun+'33');glow.addColorStop(1,p.sun+'00');c.fillStyle=glow;c.fillRect(0,0,width,height);c.fillStyle=p.sun;c.beginPath();c.arc(width*.75,height*.27,Math.min(width,height)*.045,0,Math.PI*2);c.fill();
    for(let layer=0;layer<4;layer++){const y=height*(.49+layer*.07),r=random(doc.seed+layer*173);c.beginPath();c.moveTo(-width*.1,height);c.lineTo(-width*.1,y);for(let i=0;i<5;i++){const x=width*(i+1)/4;c.quadraticCurveTo(x-width*.15,y-height*(.07+r()*.08),x,y+Math.sin(i+layer)*height*.045);}c.lineTo(width*1.2,height);c.closePath();c.globalAlpha=.26+layer*.16;c.fillStyle=layer<2?p.hill:p.near;c.fill();}c.globalAlpha=1;
    // A restrained paper grain is baked into the backdrop, never rebuilt per frame.
    const r=random(doc.seed+999);c.fillStyle='#fff8da';c.globalAlpha=.045;for(let i=0;i<2200;i++)c.fillRect(r()*width,r()*height,1,1);c.globalAlpha=1;
  }
  draw(doc:Garden,pulses:Pulse[],_dt=0,_force=false){if(this.disposed)return;this.doc=doc;this.visualTime=_dt>0?Math.max(Math.max(0,(doc.tick-1)*STEP),Math.min(doc.tick*STEP,this.visualTime+_dt)):doc.tick*STEP;const frameKey=JSON.stringify([doc.seed,this.visualTime,doc.environment,doc.camera,doc.plants.length,this.marker,this.width,this.height,pulses]);if(!_force&&frameKey===this.lastFrameKey&&doc.plants===this.lastPlants)return;this.lastFrameKey=frameKey;this.lastPlants=doc.plants;const c=this.context,w=this.width,h=this.height,project=projection(doc,w,h),key=`${doc.seed}:${doc.environment.light}:${w}:${h}`;if(key!==this.backgroundKey){this.background(doc,w,h);this.backgroundKey=key;}c.setTransform(1,0,0,1,0,0);c.drawImage(this.backdrop,0,0);c.setTransform(this.ratio,0,0,this.ratio,0,0);
    if(this.seed!==doc.seed){this.seed=doc.seed;const r=random(doc.seed);this.base=[];for(let i=0;i<(this.quality==='high'?1600:650);i++){const a=r()*Math.PI*2,d=Math.sqrt(r())*7.85;this.base.push({id:-i-1,x:Math.cos(a)*d,z:Math.sin(a)*d,age:8,kind:'grass',variation:r()});}}
    const layoutKey=`${doc.seed}:${w}:${h}:${doc.camera.azimuth}:${doc.camera.polar}:${doc.camera.distance}:${doc.plants.length}`;
    if(layoutKey!==this.projectedKey||this.layoutPlants!==doc.plants){this.projectedKey=layoutKey;this.layoutPlants=doc.plants;this.projected=[...this.base,...doc.plants].map((p,index)=>({index,...project.project(p.x,p.z)})).sort((a,b)=>a.depth-b.depth);}
    const plants=this.projected,time=this.visualTime,ageOffset=time-doc.tick*STEP,smoothPulses=pulses.map(p=>({...p,age:Math.max(0,p.age+ageOffset)})),angle=doc.camera.azimuth-.55,cos=Math.cos(angle),sin=Math.sin(angle);
    // Broad, translucent streaks of pollen; deliberately few and no blur filters.
    c.fillStyle='#fffbe4';for(let i=0;i<12;i++){const x=((i*137.3+Math.sin(time*.07+i)*45+w)%w),y=h*(.4+(i%5)*.065)+Math.sin(time*.3+i)*8;c.globalAlpha=.13+(i%3)*.05;c.beginPath();c.ellipse(x,y,1.5,.8,0,0,Math.PI*2);c.fill();}c.globalAlpha=1;
    for(const item of plants){const p=item.index<this.base.length?this.base[item.index]:doc.plants[item.index-this.base.length],{x,y}=item,depth=(item.depth+8)/16,growth=.08+.92*Math.max(0,Math.min(1,(p.age+ageOffset)/5)),length=project.scale*(p.kind==='plume'?1.3:p.kind==='flower'?.78:.55)*(.7+p.variation*.55)*growth,wind=bend(p.x,p.z,time,doc.environment,smoothPulses),lean=wind.x*cos-wind.z*sin,tipX=x+lean*length*.5,tipY=y-length,width=Math.max(.6,project.scale*.023)*(p.kind==='grass'?1.2:.5);if(x+length<0||x-length>w||y+length<0||y-length>h)continue;
      c.globalAlpha=.58+depth*.42;c.fillStyle=`hsl(${83+p.variation*20} 23% ${35+p.variation*15+depth*4}%)`;c.beginPath();c.moveTo(x-width,y);c.bezierCurveTo(x-width,y-length*.4,tipX-width,tipY+length*.27,tipX,tipY);c.bezierCurveTo(tipX+width*.4,tipY+length*.3,x+width,y-length*.35,x+width,y);c.fill();
      if(p.kind==='flower'){const radius=Math.max(.7,project.scale*.105*growth);c.globalAlpha=.9;c.fillStyle=p.variation<.35?'#f7f4dc':p.variation<.7?'#e9c682':'#d9a6a0';for(let i=0;i<5;i++){const a=i*Math.PI*2/5;c.beginPath();c.ellipse(tipX+Math.cos(a)*radius*.68,tipY+Math.sin(a)*radius*.48,radius*.67,radius*.45,a,0,Math.PI*2);c.fill();}c.fillStyle='#a28945';c.beginPath();c.ellipse(tipX,tipY,radius*.3,radius*.24,0,0,Math.PI*2);c.fill();}else if(p.kind==='plume'){c.strokeStyle='#dcd8ae';c.lineWidth=Math.max(.6,project.scale*.014);for(let i=0;i<9;i++){const t=i/9,py=tipY+length*.29*t,px=tipX+(x-tipX)*t*.2,spread=Math.sin(t*Math.PI)*length*.09;c.globalAlpha=.55+t*.35;c.beginPath();c.moveTo(px-spread,py-length*.08);c.quadraticCurveTo(px,py-length*.025,px+spread,py-length*.08);c.stroke();}}}
    c.globalAlpha=1;for(const pulse of smoothPulses){const pos=project.project(pulse.x,pulse.z),r=(.35+pulse.age*1.5)*project.scale;c.strokeStyle='#fff8dc';c.globalAlpha=Math.exp(-pulse.age*2)*.13*pulse.strength;c.lineWidth=.8;c.beginPath();c.ellipse(pos.x,pos.y,r,r*project.tilt,0,Math.PI*.12,Math.PI*1.4);c.stroke();}c.globalAlpha=1;if(this.marker.visible){const pos=project.project(this.marker.x,this.marker.z);c.strokeStyle='#fff8daba';c.lineWidth=1.2;c.setLineDash([3,5]);c.beginPath();c.ellipse(pos.x,pos.y,this.marker.radius*project.scale,this.marker.radius*project.scale*project.tilt,0,0,Math.PI*2);c.stroke();c.setLineDash([]);}
  }
  point(clientX:number,clientY:number){const r=this.host.getBoundingClientRect();return projection(this.doc,this.width,this.height).unproject(clientX-r.left,clientY-r.top);}
  mark(x:number,z:number,radius:number,visible=true){this.marker={x,z,radius,visible};}
  async snapshot(doc:Garden,size=1600){const canvas=this.canvas,context=this.context,backdrop=this.backdrop,w=this.width,h=this.height,ratio=this.ratio,key=this.backgroundKey,visible=this.marker.visible;const image=document.createElement('canvas');image.width=size;image.height=Math.round(size/1.6);try{this.canvas=image;this.context=image.getContext('2d')!;this.backdrop=document.createElement('canvas');this.backdrop.width=size;this.backdrop.height=image.height;this.width=size;this.height=image.height;this.ratio=1;this.backgroundKey='';this.marker.visible=false;this.draw(doc,[],0,true);}finally{this.canvas=canvas;this.context=context;this.backdrop=backdrop;this.width=w;this.height=h;this.ratio=ratio;this.backgroundKey=key;this.marker.visible=visible;}return new Promise<Blob>((resolve,reject)=>image.toBlob(blob=>blob?resolve(blob):reject(new Error('PNG export failed.')),'image/png'));}
  dispose(){this.disposed=true;this.canvas.remove();this.canvas.width=this.canvas.height=this.backdrop.width=this.backdrop.height=1;this.base=[];this.projected=[];}
}
