import {createWorldRuntime,type Command,type Frame,type Reply,type Request} from './runtime.ts';
import type {World} from './model.ts';
export class WorldClient {
  private worker?:Worker;private local?:ReturnType<typeof createWorldRuntime>;private generation=0;private serial=0;private disposed=false;private latest?:World;private pending=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();private onFrame:(f:Frame)=>void;private onFallback:()=>void;
  constructor(onFrame:(f:Frame)=>void,onFallback:()=>void){this.onFrame=onFrame;this.onFallback=onFallback;try{if(typeof Worker==='undefined')throw new Error('Worker unavailable');this.worker=new Worker(new URL('../../scripts/worlds.worker.ts',import.meta.url),{type:'module'});this.worker.onmessage=e=>this.receive(e.data);this.worker.onerror=()=>this.fallback();}catch{this.local=createWorldRuntime(reply=>this.receive(reply));}}
  lastPaintChanged=false;
  private receive(reply:Reply){if(this.disposed||reply.generation!==this.generation)return;if(reply.frame){if(reply.frame.state)this.latest=reply.frame.state;if(this.latest)this.onFrame({...reply.frame,state:this.latest});}if(reply.id!==undefined){this.lastPaintChanged=reply.changed??false;const p=this.pending.get(reply.id);if(p){clearTimeout(p.timer);this.pending.delete(reply.id);reply.error?p.reject(new Error(reply.error)):p.resolve(reply.result);}}}
  private fallback(){if(this.disposed||this.local)return;this.worker?.terminate();this.worker=undefined;this.local=createWorldRuntime(reply=>this.receive(reply));const requests=[...this.pending.values()];this.pending.clear();for(const p of requests){clearTimeout(p.timer);p.reject(new Error('Worker interrupted. The last displayed state is preserved in the local fallback. Try the action again.'));}if(this.latest)this.local.handle({id:0,generation:this.generation,command:'init',data:this.latest});this.onFallback();}
  async load(state:World){this.generation++;this.latest=structuredClone(state);for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error('World replaced.'));}this.pending.clear();try{await this.request('init',state);}catch(error){if(this.local&&!this.disposed){await this.request('init',state);}else throw error;}}
  request(command:Command,data?:unknown):Promise<any>{if(this.disposed)return Promise.reject(new Error('World closed.'));const id=++this.serial,message:Request={id,generation:this.generation,command,data};return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(this.worker)this.fallback();else{this.pending.delete(id);reject(new Error('World operation timed out.'));}},8000);this.pending.set(id,{resolve,reject,timer});if(this.local)this.local.handle(message);else try{this.worker!.postMessage(message);}catch{this.fallback();}});}
  dispose(){this.disposed=true;this.worker?.terminate();this.local?.dispose();for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error('World closed.'));}this.pending.clear();}
}
