import {N,base,clamp,type Ember,type Brush} from './model.ts';
export function createEmber(seed:number):Ember {const size=N*N,d:Ember={...base('ember',seed),world:'ember',base:new Float64Array(size),mass:new Float64Array(size),heat:new Float64Array(size),solid:new Uint8Array(size),crack:new Float64Array(size),params:{cooling:.3,fluidity:.55}};const phase=(seed%1000)*.01;for(let y=0;y<N;y++)for(let x=0;x<N;x++){const i=y*N+x;d.base[i]=clamp(.45+.15*Math.sin(x*.06+phase)+.12*Math.cos(y*.065-phase)+.06*Math.sin((x+y)*.13));const r=Math.hypot(x-N*.48,y-N*.48);if(r<10){d.mass[i]=.7*(1-r/12);d.heat[i]=.95;}}return d;}
export function paintEmber(d:Ember,b:Brush){let changed=false;const r=Math.max(1,b.radius*N),cx=b.x*(N-1),cy=b.y*(N-1);for(let y=Math.max(0,Math.floor(cy-r));y<=Math.min(N-1,cy+r);y++)for(let x=Math.max(0,Math.floor(cx-r));x<=Math.min(N-1,cx+r);x++){const distance=Math.hypot(x-cx,y-cy)/r;if(distance>1)continue;const i=y*N+x,w=(1-distance)*b.strength,oldHeat=d.heat[i],oldMass=d.mass[i],oldSolid=d.solid[i],oldCrack=d.crack[i];if(b.tool==='lava'){const amount=Math.min(4-d.mass[i],w*.3),mass=d.mass[i]+amount;d.heat[i]=mass?(d.heat[i]*d.mass[i]+amount)/mass:0;d.mass[i]=mass;}else if(b.tool==='heat')d.heat[i]=clamp(d.heat[i]+w*.22);else if(b.tool==='cool')d.heat[i]=clamp(d.heat[i]-w*.3);else if(b.tool==='remove'){d.mass[i]=Math.max(0,d.mass[i]-w*.5);if(!d.mass[i]){d.heat[i]=0;d.solid[i]=0;d.crack[i]=0;}}if(d.mass[i]&&d.heat[i]>.56)d.solid[i]=0;else if(d.mass[i]&&d.heat[i]<.32)d.solid[i]=1;if(b.tool==='cool'&&d.solid[i])d.crack[i]=clamp(d.crack[i]+Math.max(0,oldHeat-d.heat[i])*.65);changed ||= oldHeat!==d.heat[i]||oldMass!==d.mass[i]||oldSolid!==d.solid[i]||oldCrack!==d.crack[i];}return changed;}
// Scratch data is intentionally outside the portable document and undo history.
const scratch=new WeakMap<Ember,{next:Float64Array;energy:Float64Array;transported:Float64Array;heat:Float64Array}>();
const neighbors=new Int32Array(N*N*4);for(let y=0;y<N;y++)for(let x=0;x<N;x++){const i=y*N+x;neighbors.set([x?i-1:-1,x<N-1?i+1:-1,y?i-N:-1,y<N-1?i+N:-1],i*4);}
export function stepEmber(d:Ember){const length=N*N;let work=scratch.get(d);if(!work){work={next:new Float64Array(length),energy:new Float64Array(length),transported:new Float64Array(length),heat:new Float64Array(length)};scratch.set(d,work);}const {next,energy,transported,heat}=work;next.set(d.mass);for(let i=0;i<length;i++)energy[i]=d.mass[i]*d.heat[i];
  // Source-limited, capacity-limited transfers preserve mass, with no edge wrap.
  for(let i=0;i<length;i++){if(d.solid[i]||d.mass[i]<1e-9)continue;let remaining=d.mass[i]*.18*d.params.fluidity;const surface=d.base[i]+d.mass[i]*.22;for(let k=0;k<4;k++){const j=neighbors[i*4+k];if(j<0)continue;const difference=surface-(d.base[j]+d.mass[j]*.22),amount=Math.min(remaining,Math.max(0,difference)*.12*d.params.fluidity,Math.max(0,4-next[j]));if(amount<=0)continue;next[i]-=amount;next[j]+=amount;energy[i]-=amount*d.heat[i];energy[j]+=amount*d.heat[i];remaining-=amount;}}
  for(let i=0;i<length;i++)transported[i]=next[i]>1e-12?clamp(energy[i]/next[i]):d.heat[i];for(let i=0;i<length;i++){let sum=0,count=0,gradient=0;for(let k=0;k<4;k++){const j=neighbors[i*4+k];if(j>=0){sum+=transported[j];count++;gradient=Math.max(gradient,Math.abs(transported[i]-transported[j]));}}heat[i]=clamp(transported[i]+.035*(sum/count-transported[i])-d.params.cooling*.003);if(next[i]<1e-10){next[i]=Math.max(0,next[i]);d.solid[i]=0;d.crack[i]=0;continue;}if(heat[i]<.32)d.solid[i]=1;else if(heat[i]>.56)d.solid[i]=0;if(d.solid[i]){const cooling=Math.max(0,d.heat[i]-heat[i]);d.crack[i]=clamp(d.crack[i]+cooling*(.5+gradient*10));}else d.crack[i]=Math.max(0,d.crack[i]-.012);}
  work.next=d.mass;work.heat=d.heat;d.mass=next;d.heat=heat;d.tick++;
}
