export type WorldId='pelagic'|'ember';
export const N=128,DT=1/30,FILE_LIMIT=2*1024*1024;
export const clamp=(n:number,a=0,b=1)=>Math.max(a,Math.min(b,n));
export interface Base {format:'ortunate-world';version:1;world:WorldId;name:string;seed:number;rng:number;tick:number}
export interface Creature {id:number;kind:'jelly'|'fish'|'plankton';x:number;y:number;vx:number;vy:number;depth:number;phase:number}
export interface Flow {x:number;y:number;dx:number;dy:number;age:number}
export interface Pelagic extends Base {world:'pelagic';nextId:number;creatures:Creature[];lights:{x:number;y:number}[];flows:Flow[];params:{direction:number;strength:number;brightness:number}}
export interface Ember extends Base {world:'ember';base:Float64Array;mass:Float64Array;heat:Float64Array;solid:Uint8Array;crack:Float64Array;params:{cooling:number;fluidity:number}}
export type World=Pelagic|Ember;
export interface Brush {tool:string;x:number;y:number;radius:number;strength:number;kind?:Creature['kind'];dx?:number;dy?:number}
export function random(d:Base){d.rng=(Math.imul(d.rng,1664525)+1013904223)>>>0;return d.rng/4294967296;}
export function base(world:WorldId,seed:number):Base {return{format:'ortunate-world',version:1,world,name:world==='pelagic'?'A pocket of deep blue':'Where the earth remembers',seed:seed>>>0,rng:seed>>>0,tick:0};}
const finite=(v:unknown,a:number,b:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b;
function keys(value:object,allowed:string[]){if(Object.keys(value).some(k=>!allowed.includes(k)))throw new Error('Unexpected world fields.');}
export function validate(value:unknown,expected?:WorldId):asserts value is World {const d=value as World;if(!d||d.format!=='ortunate-world'||d.version!==1||!['pelagic','ember'].includes(d.world)||expected&&expected!==d.world||typeof d.name!=='string'||d.name.length>80||![d.seed,d.rng].every(v=>Number.isInteger(v)&&finite(v,0,4294967295))||!Number.isSafeInteger(d.tick)||d.tick<0||!d.params)throw new Error('Choose a valid version 1 file for this world.');
  keys(d,['format','version','world','name','seed','rng','tick','params',...(d.world==='pelagic'?['nextId','creatures','lights','flows']:['base','mass','heat','solid','crack'])]);keys(d.params,d.world==='pelagic'?['direction','strength','brightness']:['cooling','fluidity']);
  if(d.world==='pelagic'){if(!Number.isSafeInteger(d.nextId)||d.nextId<0||d.nextId>Number.MAX_SAFE_INTEGER-1024||!Array.isArray(d.creatures)||d.creatures.length>424||!Array.isArray(d.lights)||d.lights.length>6||!Array.isArray(d.flows)||d.flows.length>12||!finite(d.params.direction,0,360)||!finite(d.params.strength,0,1)||!finite(d.params.brightness,0,1))throw new Error('Invalid sea settings.');const ids=new Set<number>(),counts={jelly:0,fish:0,plankton:0};for(const c of d.creatures){if(!c||!['jelly','fish','plankton'].includes(c.kind)||!Number.isSafeInteger(c.id)||c.id<0||c.id>=d.nextId||ids.has(c.id)||!finite(c.x,0,1)||!finite(c.y,0,1)||!finite(c.vx,-.3,.3)||!finite(c.vy,-.3,.3)||!finite(c.depth,0,1)||!finite(c.phase,0,Math.PI*2))throw new Error('Invalid creature.');keys(c,['id','kind','x','y','vx','vy','depth','phase']);ids.add(c.id);counts[c.kind]++;}if(counts.jelly>24||counts.fish>160||counts.plankton>240)throw new Error('Sea population exceeds its limits.');for(const p of [...d.lights,...d.flows])if(!p||!finite(p.x,0,1)||!finite(p.y,0,1))throw new Error('Invalid sea position.');for(const l of d.lights)keys(l,['x','y']);for(const f of d.flows){keys(f,['x','y','dx','dy','age']);if(!finite(f.dx,-1,1)||!finite(f.dy,-1,1)||!finite(f.age,0,4))throw new Error('Invalid current.');}}
  else{if(!finite(d.params.cooling,0,1)||!finite(d.params.fluidity,0,1))throw new Error('Invalid thermal settings.');for(const [key,max]of [['base',1],['mass',4],['heat',1],['crack',1]] as const){const a=d[key];if(!(a instanceof Float64Array)||a.length!==N*N||!a.every(v=>finite(v,0,max)))throw new Error('Invalid material field.');}if(!(d.solid instanceof Uint8Array)||d.solid.length!==N*N||!d.solid.every(v=>v===0||v===1))throw new Error('Invalid solid field.');}}
function pack(a:Float64Array|Uint8Array){const bytes=new Uint8Array(a instanceof Float64Array?a.length*8:a.length),view=new DataView(bytes.buffer);if(a instanceof Float64Array)for(let i=0;i<a.length;i++)view.setFloat64(i*8,a[i],true);else bytes.set(a);let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);}
function unpack(text:unknown,bytesPerElement:number){const size=N*N*bytesPerElement;if(typeof text!=='string'||text.length!==4*Math.ceil(size/3)||!/^[A-Za-z0-9+/]*={0,2}$/.test(text))throw new Error('Invalid material encoding.');const binary=atob(text);if(binary.length!==size)throw new Error('Invalid material length.');const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));if(bytesPerElement===1)return bytes;const a=new Float64Array(N*N),v=new DataView(bytes.buffer);for(let i=0;i<a.length;i++)a[i]=v.getFloat64(i*8,true);return a;}
export function encode(d:World){validate(d);const data=d.world==='ember'?{...d,encoding:'f64le-base64',base:pack(d.base),mass:pack(d.mass),heat:pack(d.heat),solid:pack(d.solid),crack:pack(d.crack)}:d;const text=JSON.stringify(data);if(new TextEncoder().encode(text).length>FILE_LIMIT)throw new Error('World files are limited to 2 MiB.');return text;}
export function decode(text:string,expected:WorldId){if(new TextEncoder().encode(text).length>FILE_LIMIT)throw new Error('World files are limited to 2 MiB.');const d=JSON.parse(text);if(d?.world!==expected)throw new Error('This file belongs to another world.');if(d.world==='ember'){if(d.encoding!=='f64le-base64')throw new Error('Unsupported material encoding.');for(const k of ['base','mass','heat','crack'])d[k]=unpack(d[k],8);d.solid=unpack(d.solid,1);delete d.encoding;}validate(d,expected);return d;}
export function stateBytes(d:World){return d.world==='ember'?N*N*33+1024:d.creatures.length*96+d.flows.length*64+2048;}
