import {base,random,clamp,DT,type Pelagic,type Brush,type Creature} from './model.ts';
export const CAPS={jelly:24,fish:160,plankton:240};
export function createPelagic(seed:number):Pelagic {const d:Pelagic={...base('pelagic',seed),world:'pelagic',nextId:0,creatures:[],lights:[{x:.7,y:.36}],flows:[],params:{direction:15,strength:.25,brightness:.4}};for(let i=0;i<5;i++)add(d,'jelly',.25+random(d)*.5,.25+random(d)*.45);for(let i=0;i<6;i++)add(d,'fish',.2+random(d)*.6,.2+random(d)*.6);for(let i=0;i<7;i++)add(d,'plankton',random(d),random(d));return d;}
function add(d:Pelagic,kind:Creature['kind'],x:number,y:number){const count=d.creatures.filter(c=>c.kind===kind).length,max=Math.min(CAPS[kind]-count,kind==='fish'?8:kind==='plankton'?12:1);for(let i=0;i<max;i++)d.creatures.push({id:d.nextId++,kind,x:clamp(x+(random(d)-.5)*.08,.02,.98),y:clamp(y+(random(d)-.5)*.08,.02,.98),vx:(random(d)-.5)*.04,vy:(random(d)-.5)*.02,depth:random(d),phase:random(d)*Math.PI*2});return max>0;}
export function paintPelagic(d:Pelagic,b:Brush){if(b.tool==='add'){const kind=b.kind??'jelly';if(!add(d,kind,b.x,b.y))return `${kind} limit reached (${CAPS[kind]}). Remove some to make room.`;}else if(b.tool==='light'){if(d.lights.length>=6)return 'Six lights are already placed. Remove one first.';d.lights.push({x:b.x,y:b.y});}else if(b.tool==='remove'){d.creatures=d.creatures.filter(c=>Math.hypot(c.x-b.x,c.y-b.y)>b.radius);d.lights=d.lights.filter(c=>Math.hypot(c.x-b.x,c.y-b.y)>b.radius);}else if(b.tool==='flow'){const dx=clamp(b.dx??.4,-1,1)*b.strength,dy=clamp(b.dy??0,-1,1)*b.strength;d.flows.push({x:b.x,y:b.y,dx,dy,age:0});if(d.flows.length>12)d.flows.shift();}return '';}
export function stepPelagic(d:Pelagic){const next:Creature[]=[],fish=d.creatures.filter(c=>c.kind==='fish'),angle=d.params.direction*Math.PI/180,t=d.tick*DT;for(const c of d.creatures){let ax=Math.cos(angle)*d.params.strength*.04,ay=Math.sin(angle)*d.params.strength*.04;for(const f of d.flows){const w=Math.exp(-((c.x-f.x)**2+(c.y-f.y)**2)/.025)*Math.exp(-f.age*1.3);ax+=f.dx*w*.22;ay+=f.dy*w*.22;}if(c.kind==='fish'){let n=0,cx=0,cy=0,vx=0,vy=0;for(const o of fish){if(o.id===c.id)continue;const dx=o.x-c.x,dy=o.y-c.y,dist=dx*dx+dy*dy;if(dist<.013){n++;cx+=o.x;cy+=o.y;vx+=o.vx;vy+=o.vy;if(dist<.0006){ax-=dx*.003/(dist+.0001);ay-=dy*.003/(dist+.0001);}}}if(n){ax+=(cx/n-c.x)*.35+(vx/n-c.vx)*.6;ay+=(cy/n-c.y)*.35+(vy/n-c.vy)*.6;}for(const l of d.lights){const dx=l.x-c.x,dy=l.y-c.y;ax+=dx*.02;ay+=dy*.02;}}else if(c.kind==='jelly'){ay-=.012*(1+Math.sin(t*1.5+c.phase));for(const l of d.lights){const dx=c.x-l.x,dy=c.y-l.y,w=Math.exp(-(dx*dx+dy*dy)/.016);ax+=dx*w*.8;ay+=dy*w*.8;}}ax+=Math.sin(t*.7+c.phase)*.008;ay+=Math.cos(t*.4+c.phase)*.006;
    // Soft walls steer inward before a final reflective safety boundary.
    ax+=Math.max(0,.09-c.x)*1.5-Math.max(0,c.x-.91)*1.5;ay+=Math.max(0,.09-c.y)*1.5-Math.max(0,c.y-.91)*1.5;
    let vx=(c.vx+ax*DT)*.99,vy=(c.vy+ay*DT)*.99;const speed=Math.hypot(vx,vy),max=c.kind==='fish'?.09:c.kind==='jelly'?.04:.055;if(speed>max){vx*=max/speed;vy*=max/speed;}let x=c.x+vx*DT,y=c.y+vy*DT;if(x<.01||x>.99)vx*=-.7;if(y<.01||y>.99)vy*=-.7;next.push({...c,x:clamp(x,.01,.99),y:clamp(y,.01,.99),vx,vy});}d.creatures=next;d.flows=d.flows.map(f=>({...f,age:f.age+DT})).filter(f=>f.age<4);d.tick++;}
