export type ModelId = 'reaction' | 'sand' | 'lenia';
export type Params = Record<string, number>;
export interface Parameter { key: string; label: string; min: number; max: number; step: number; value: number }
const p = (key: string, label: string, min: number, max: number, step: number, value: number): Parameter => ({ key, label, min, max, step, value });
export const models = {
  reaction: { title: 'Growth textures', subtitle: 'Order, emerging from chemistry.', description: 'A Gray–Scott reaction–diffusion system. Feed two chemicals, interrupt their diffusion, and watch structure emerge.', tag: '01 / REACTION–DIFFUSION', boundary: 'Periodic boundary · Gray–Scott · dt = 1', size: 256, presets: ['Coral', 'Mitosis', 'Stripes'], views: ['Concentration', 'Embossed'], brushes: ['Seed', 'Erase', 'Barrier'], metrics: ['meanA', 'meanB', 'change'], axes: ['feed', 'kill'], params: [p('feed', 'Feed F', .01, .09, .0001, .0545), p('kill', 'Kill K', .03, .075, .0001, .062), p('da', 'Diffusion A', .1, 1, .01, 1), p('db', 'Diffusion B', .01, .5, .01, .5)] },
  sand: { title: 'Sand ecology', subtitle: 'A tiny world with consequences.', description: 'Build dams, release water, and ignite forests. A deterministic cellular sandbox — not a precision fluid or thermal simulator.', tag: '02 / MATERIAL SYSTEMS', boundary: 'Sealed boundary · discrete cellular rules', size: 256, presets: ['Hourglass', 'Dam', 'Combustion'], views: ['Materials'], brushes: ['Sand', 'Water', 'Stone', 'Wood', 'Fire', 'Steam', 'Smoke', 'Erase'], metrics: ['sand', 'water', 'stone', 'wood', 'fire', 'steam', 'smoke', 'moving', 'reactions'], axes: ['gravity', 'spread'], params: [p('gravity', 'Gravity passes', 1, 4, 1, 1), p('spread', 'Water spread probability', 0, 1, .01, .8), p('burn', 'Ignition probability', 0, 1, .01, .15)] },
  lenia: { title: 'Lenia culture', subtitle: 'Somewhere between math and life.', description: 'Continuous cellular life with a radial kernel and Gaussian growth. Seed an organism, perturb its habitat, and follow the outcome.', tag: '03 / CONTINUOUS LIFE', boundary: 'Periodic boundary · FFT convolution · single channel', size: 128, presets: ['Orbium', 'Encounter', 'Random density'], views: ['Density', 'Potential', 'Growth'], brushes: ['Orbium', 'Density', 'Erase'], metrics: ['mass', 'area', 'change'], axes: ['mu', 'sigma'], params: [p('radius', 'Kernel radius R', 5, 32, 1, 13), p('ring1', 'Ring 1 weight', 0, 1, .05, 1), p('ring2', 'Ring 2 weight', 0, 1, .05, 0), p('ring3', 'Ring 3 weight', 0, 1, .05, 0), p('mu', 'Growth center μ', .05, .3, .001, .15), p('sigma', 'Growth width σ', .005, .06, .001, .015), p('dt', 'Time step', .01, .2, .01, .1)] }
} as const;
export function defaults(model: ModelId): Params { return Object.fromEntries(models[model].params.map(p => [p.key, p.value])); }
export function validateParams(model: ModelId, params: Params) {
  if (!params || Object.keys(params).length !== models[model].params.length) throw new Error('Invalid parameter set.');
  for (const p of models[model].params) if (!Number.isFinite(params[p.key]) || params[p.key] < p.min || params[p.key] > p.max || (p.step === 1 && !Number.isInteger(params[p.key]))) throw new Error(`Invalid ${p.label}.`);
  if (model === 'lenia' && params.ring1 + params.ring2 + params.ring3 === 0) throw new Error('At least one kernel ring must have weight.');
}
